### ISSUE TITLE
Some content on the front page is VERY dated

### ISSUE THREAD

**Issue by williamstein** [jupyter/nbviewer#1011]
I was just browsing the front page (https://nbviewer.org/), and the notebook link **right in the middle** (maybe the most central one that a person browsing might be drawn to) is very dated.  If you click and browse the notebooks, you just see they use Python 2.  If you actually look at the github repo itself -- https://github.com/ptwobrussell/Mining-the-Social-Web-2nd-Edition -- there is a huge warning at the top **HTTP 301: Don't Use This Repository - 17 Jan 2019**, and there is a recommendation to use https://github.com/mikhailklassen/Mining-the-Social-Web-3rd-Edition instead.  So the central main nbviewer link has been deprecated for 3.5 years.     I have no comments about other content, but when fixing this, it may be worth checking that the other content hasn't been deprecated for years...

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/1276278/176705227-a21b5bb8-150e-4616-aee6-ad99931f9eed.png">

**Comment by williamstein** [comment]
Done - PR created.

**Comment by krinsman** [comment]
@williamstein  Perfect! Thank you so much for contributing to NBViewer 

As I mentioned on the PR thread, feel free to ping me, say in a couple of weeks, if no one else has the time to check and merge the PR -- it does look like the correct changes though
