### ISSUE TITLE
nbviewer not working on Heroku

### ISSUE THREAD

**Issue by ryanswanstrom** [jupyter/nbviewer#103]
I have followed the steps in the Readme file.  It successfully deploys the app to heroku, but it will not render any ipython files.  Here is the app http://ipynb.herokuapp.com/

Here is a very basic ipython notebook. https://gist.github.com/swGooF/6057503/raw/1de4d993da0bb8ab4e758d4af05c1f1c5a81ba87/first_ipython.ipynb

**Comment by Carreau** [comment]
Closing as we pretty much don't use heroku anymore.
