### ISSUE TITLE
Encode URL to deal with '?'

### ISSUE THREAD

**Issue by giotta** [jupyter/nbviewer#104]
I have this notebook URL :
http://git.auf.org/?p=davin.git;a=blob_plain;f=ateliers/debian-python-virtualenv/mtlpy-workshop-debian-dev-env-fr.ipynb

that I wanted to render in this nbviewer :
http://nbviewer.ipython.org/

I've got an error :
http://nbviewer.ipython.org/url/git.auf.org/?p=davin.git;a=blob_plain;f=ateliers/debian-python-virtualenv/mtlpy-workshop-debian-dev-env-fr.ipynb

If I encode manually the ? of the query string in the URL address bar of my browser, it works :
http://nbviewer.ipython.org/url/git.auf.org/%3Fp=davin.git;a=blob_plain;f=ateliers/debian-python-virtualenv/mtlpy-workshop-debian-dev-env-fr.ipynb

**Comment by bollwyvl** [comment]
We are reserving the right to at some point use `GET` params for the nbviewer itself, so ? and & will have to be escaped.

The text box on the front page will do the escaping for you: it's basically doing a `POST` with your URL as a param. If you need to do this in an automated fashion, you could use that... or just keep doing the escaping.
