### ISSUE TITLE
Error 503 Backend is unhealthy on Dec 19, 2023

### ISSUE THREAD

**Issue by DougEbel** [jupyter/nbviewer#1054]
Running URLs that previously worked for nbviewer now yields:

Error 503 Backend is unhealthy
Backend is unhealthy
Error 54113
Details: cache-bur-kbur8200152-BUR 1702996184 3914895651
________________________________________
Varnish cache server

First discovered around 9:15 AM (EST) and not cleared as of this reporting at 11:15 AM.  Same result with Chrome or Edge Browser

**Comment by DougEbel** [comment]
Dec 20, 2023 8:15 AM - Backend is still unhealthy

**Comment by minrk** [comment]
The cluster hosting nbviewer is unhealthy, hopefully fixed soon.

**Comment by DougEbel** [comment]
Working again.  Thank-you
