### ISSUE TITLE
plotly.js not found

### ISSUE THREAD

**Issue by ReenigneArcher** [jupyter/nbviewer#1063]
Hi! Thanks for using Jupyter Notebook Viewer (nbviewer) and taking the time to report a bug you've encountered. Please use the template below to tell us about the problem.

If you've found a bug in a different Jupyter project (e.g., [Jupyter Notebook](http://github.com/jupyter/notebook), [JupyterLab](http://github.com/jupyterlab/jupyterlab), [JupyterHub](http://github.com/jupyterhub/jupyterhub), etc.), please open an issue using that project's issue tracker instead.

If you need help using or installing Jupyter Notebook Viewer, please use the [jupyter/help](https://github.com/jupyter/help) issue tracker instead.

**Describe the bug**
When loading a notebook with plotly interactive graphs, the page gives errors.

```
Loading failed for the <script> with source “https://nbviewer.org/github/LizardByte/dashboard/blob/feat%2Finitial-version/notebook/plotly.js”. dashboard.ipynb:1:1
Uncaught Error: Script error for "plotly"
http://requirejs.org/docs/errors.html#scripterror
    makeError https://nbviewer.org/static/components/requirejs/require.js:165
    onScriptError https://nbviewer.org/static/components/requirejs/require.js:1732
require.js:165:17
```

I can replicate this locally by running the command `jupyter nbconvert --to html notebook/dashboard.ipynb`, as suggested here: https://github.com/jupyter/nbviewer/issues/806#issuecomment-557300780

But, locally I can place the `plotly.js` file from `https://cdn.plot.ly/plotly-2.34.0.min.js` and then the rendering will work successfully. I placed the file in my repo, and it still cannot be rendered by nbviewer.org.

**Expected behavior**
Option 1: provide a `plotly.js` for everyone to use.
Option 2: allow utilizing a `plotly.js` file that is in the same repo as the notebook.

**Screenshots**
Actual:
![image](https://github.com/user-attachments/assets/d311173e-a841-475c-beb8-48d82c246533)

Expected:
![image](https://github.com/user-attachments/assets/5ca8b131-7184-47ef-95af-5a949fe861a8)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 129

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RanjanRavi2398** [comment]
@ReenigneArcher ,can you check require.js configuration? Ensure that the require.js configuration in your notebook is set correctly if you're using require.js to load the modules

**Comment by ReenigneArcher** [comment]
I actually moved to just publishing my notebook via gh-pages and supplying the `plotly.js` file myself. Everything is working okay that way. I'm not using `require.js` directly, but plotly.js may be using it indirectly.

Anyway, I'll close this as I'm no longer using nbviewer. Thank you!
