### ISSUE TITLE
Responsive to mobile viewing

### ISSUE THREAD

**Issue by jkmacc** [jupyter/nbviewer#111]
As nbviewer is web-facing, and not just an ipython notebook, I'd love to see a mobile-optimized rendering available.  In my experience, these are not readable on mobile.  I do most of my browsing on small screens these days, as do many folks trying to learn about Python, and I think it'd be a great addition.

**Comment by bollwyvl** [comment]
Please review the site now: we've upgraded the CSS a great deal over the last while, and are interested in helping improve the experience on mobile further!
