### ISSUE TITLE
Embedding nbviewer in secure pages raises a message

### ISSUE THREAD

**Issue by aboSamoor** [jupyter/nbviewer#119]
I maintain this page (https://bit.ly/embeddings). Google sites require the pages to be served under https.

Embedding a nbviewer page through iframe trigger a secure warning in firefox 23+ and latest chrome versions.

I think the certificate used by the nbviewer website is not trusted or something like that.

I would like to hear your advice on such issue.

**Comment by parente** [comment]
I think this can be closed as we're using a CloudFlare certificate and SNI to cover nbviewer.jupyter.org and jupyter.org these days. https://codepen.io/anon/pen/YjqKmG includes an iframe pointing to a notebook served by nbviewer over https. Neither Chrome nor Firefox complain about this setup and show the iframe properly.

Feel free to open a new issue if you're still hitting a problem using or embedding nbviewer over https.
