### ISSUE TITLE
Github API change

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbviewer#161]
github might [change it's API response](http://developer.github.com/changes/2014-01-07-upcoming-change-to-default-media-type/#cutover-test) in a month or so. 

One of [the differences](http://developer.github.com/v3/versions/#differences-from-beta-version) will be that `user` wlll becommes `owner` for gists. I think it might affect or redirect for `gist number` to `user/gist-number`.

**Comment by bollwyvl** [comment]
Since we haven't seen any issues related to this, I think we're ok with v3.
