### ISSUE TITLE
required pixel width for unpacked menu display

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbviewer#180]
Is it really necessary to require a 980 pixel wide window to have the nice menu of the nbviewer displayed 'unpacked' instead of in a sub-menu? I see a lot of white space on the right hand side of the last menu item "Bookmarklet", so I think it's possible to shrink this down a bit, don't you agree?

From @ michaelaye here: https://github.com/ipython/ipython/issues/4801

**Comment by minrk** [comment]
It's moved to 767 now. On the index it still seems wide, but it's close enough when there are more controls on the actual viewer page.
