### ISSUE TITLE
Setup webhooks to trigger events in salt 

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/nbviewer#186]
This will probably belong somewhere else, but I might as well list it here.

Travis, GitHub can post to webhooks and salt can be fired off programmatically. Just sat in on a talk by @whiteinge (repo: https://github.com/whiteinge/testrepo), where he fired an event off based on build success. These are the next steps for automation I'm looking forward to.

**Comment by bollwyvl** [comment]
Do we even use salt anymore?

**Comment by minrk** [comment]
ha, no.

**Comment by rgbkrk** [comment]
Most stable deployment we ever had. Much easier to reason with Ubuntu vs CoreOS.

**Comment by bollwyvl** [comment]
Yeah, i do like deployments made of YAML state machines. What's some of the
thinking about moving away from that pattern?

**Comment by rgbkrk** [comment]
Most of the desire to migrate was the complexity of deployment, management of secrets, etc. It wasn't very newcomer friendly. We tried out Docker and CoreOS which has been nice, but we're missing the smart things we did for zero-downtime rolling deployments (even making sure connections fully dropped).
