### ISSUE TITLE
investigate webhooks

### ISSUE THREAD

**Issue by minrk** [jupyter/nbviewer#190]
GitHub's web hooks have just been [cleaned up](https://github.com/blog/1778-webhooks-level-up). We might be able to use web hooks to better inform our cache policy (invalidate on push, cache forever until next push, etc.).

[The API](http://developer.github.com/webhooks/)

**Comment by Carreau** [comment]
Should we close as now notebooks render on github ?

**Comment by bollwyvl** [comment]
+1 for closing

**Comment by damianavila** [comment]
>Should we close as now notebooks render on github ?

Yep, probably...
