### ISSUE TITLE
Does not handle URLs with explicit ports

### ISSUE THREAD

**Issue by cancan101** [jupyter/nbviewer#205]
For example, this does not work:
http://nbviewer.ipython.org/urls/gist.githubusercontent.com:443/glebkuznetsov/9063958/raw/f4ab6ec0703ae790e111a5411f432faf8edfd29a/pandas_join?create=1

but this does: http://nbviewer.ipython.org/urls/gist.githubusercontent.com/glebkuznetsov/9063958/raw/f4ab6ec0703ae790e111a5411f432faf8edfd29a/pandas_join?create=1

**Comment by bollwyvl** [comment]
Potentially fixed by #481.

**Comment by bollwyvl** [comment]
Fixed for listed example. If you continue to experience problems with your local hosting, please reopen! Thanks for using nbviewer!
