### ISSUE TITLE
How can one get the cell output collapsed, or within a scrolling text box ...

### ISSUE THREAD

**Issue by Pellarin** [jupyter/nbviewer#208]
... as it is displayed in ipython notebook? Especially for long output it is quite annoying to have all that text around. Thanks!

**Comment by parente** [comment]
XRe: #750

**Comment by parente** [comment]
I'm going to close this issue in favor of #750. I know this report one was opened much earlier, but I happened upon the other first and put in both a `<style>` cell workaround and commentary about updates required in nbviewer there.

Please feel free to comment if I've incorrectly associated the two issues.
