### ISSUE TITLE
Design explorations for nbviewer

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbviewer#218]
I have been playing with some design ideas for nbviewer while watching a movie tonight.  This is based on the discussion from this weeks dev meeting. Here are the goals:

* A top nav bar that contains provides a clear and unambiguous branding for the website.
* A simplified frontpage design that places more emphasis on example notebook content rather than oversized "IPython Notebook Viewer" banner text.
* Removed redundant sub-banners.

I wanted to get feedback about the broad strokes of the idea before I code this up.

Here is a screenshot.

![screen shot 2014-03-14 at 9 33 15 pm](https://f.cloud.github.com/assets/27600/2427629/cbf27a62-abfb-11e3-9623-57e996729202.png)

**Comment by bollwyvl** [comment]
Mostly implemented as of #413.
