### ISSUE TITLE
[css] add media print target

### ISSUE THREAD

**Issue by pierriko** [jupyter/nbviewer#221]
This is a feature request for a print media target in the style sheet [1].
The basic would be to hide header and footer, and avoid cutting images [2].

[1] http://coding.smashingmagazine.com/2011/11/24/how-to-set-up-a-print-style-sheet/
[2] http://stackoverflow.com/questions/2649169/print-styles-how-to-ensure-image-doesnt-span-a-page-break

Thanks!

**Comment by parente** [comment]
I think @pierriko resolved this issue with PR #225 some time ago and it's probably safe to close. @pierriko would you agree?

Looking at nbviewer today, I see the breadcrumbs have snuck into the print view which may or may not be what we want. I can open a new issue about that.

**Comment by pierriko** [comment]
Yes, thanks!
