### ISSUE TITLE
Noob, I got my service going but where do I put my notebooks?

### ISSUE THREAD

**Issue by pyrrhus429** [jupyter/nbviewer#249]
Hey I'm a noob with getting my own local nbviewer service going.  I got the server running, but was unclear from the instructions where I put my notebooks.  Can you provide more guidance on it?

**Comment by dvreed77** [comment]
I to would like to do this, but don't know how to point to the local files.  Could you provide some extra steps?  Thanks

**Comment by minrk** [comment]
@dvreed77  `python -m nbviewer --localfiles="/path/to/notebooks"`

**Comment by dvreed77** [comment]
Thanks, but then whats the proper URL in the browser?

**Comment by minrk** [comment]
ah, sorry, `[nbviewer-host]/localfile/relative/notebook/path`

so if you have:

    /my/notebooks/subdir/foo.ipynb

and start nbviewer with:

    python -m nbviewer --localfiles=/my/notebooks

You can see foo.ipynb at

    http://localhost:5000/localfile/subdir/foo.ipynb

**Comment by dvreed77** [comment]
Great!  Thank you!
