### ISSUE TITLE
Notebook plot does not render

### ISSUE THREAD

**Issue by kdodia** [jupyter/nbviewer#253]
I developed an IPython notebook locally and uploaded it to GitHub [here](https://github.com/kdodia/drought-stats-tx/blob/master/Texas_Drought_Stats.ipynb), then tried to view it with NBViewer [here](http://nbviewer.ipython.org/github/kdodia/drought-stats-tx/blob/master/Texas_Drought_Stats.ipynb). The last cell output should contain a plot that looks like this:

![rendered](https://cloud.githubusercontent.com/assets/4944634/2726477/ac6baa54-c5bb-11e3-9fef-b9d48137d96e.png)

However, NBViewer does not render it.

Peeking into the console reveals this error: 
![error](https://cloud.githubusercontent.com/assets/4944634/2726488/e958a3c2-c5bb-11e3-9c4d-eac8865fe356.png)

A quick google search on that suggests [this](http://stackoverflow.com/questions/10291693/cannot-read-property-getcontext-of-null-using-canvas) as the issue, namely that the script is attempting to reference a canvas element before it is loaded into the DOM.

Is it possible to address this behavior in NBViewer?

**Comment by bollwyvl** [comment]
The originally-linked notebook now renders fine! Closing.
