### ISSUE TITLE
Set max-height: px and overflow:scroll in nbviewer (like it is in a notebook)

### ISSUE THREAD

**Issue by theengineear** [jupyter/nbviewer#260]
When you generate long output in a notebook, the output cell will hit an overflow and turn into a scroll box. However, there is no scroll box when you view this on nbviewer.

To get around this right now, I'm just adding the following to the html header after running `ipython nbconvert the_notebook.ipynb`:

```
<style>
    div.output_area{
        max-height:600px;
        overflow:scroll;
    }
</style>
```

It seems like what i'm looking at when I make a notebook should be the same as what viewers to see when they look at the same notebook on nbviewer.

I'm not sure if there was a reason for having it in its current state, but I hope you'll consider this! Thanks!!

**Comment by dhimmel** [comment]
I also think it would be nice for the local display behavior (in terms of collapsing cells with copious output) would apply to http://nbviewer.ipython.org hosted notebooks.

**Comment by dhimmel** [comment]
Here is [another open issue](https://github.com/jupyter/nbviewer/issues/208) on this topic.

**Comment by tristanreid** [comment]
+1 on this.  The lack of horizontal scroll means that wide tables are not completely viewable, which is more than an inconvenience.

**Comment by parente** [comment]
XRef: #750

**Comment by parente** [comment]
I'm going to close this issue in favor of #750. I know this report one was opened much earlier, but I happened upon the other first and put in both a `<style>` cell workaround and commentary about updates required in nbviewer there.

Please feel free to comment if I've incorrectly associated the two issues.
