### ISSUE TITLE
Unicode characters  in identifiers, are wrongly *red boxed* as errors (Python3, Julia).

### ISSUE THREAD

**Issue by Ismael-VC** [jupyter/nbviewer#303]
This happens with both Python 3 and Julia:

![falseo_errror](https://cloud.githubusercontent.com/assets/4594825/3344888/810a4dc0-f8b0-11e3-9a36-b18ae30178b2.jpg)

http://bit.ly/1lSrFKk

**Comment by bollwyvl** [comment]
This is an upstream [issue in pygments](https://bitbucket.org/birkenfeld/pygments-main/issue/1074/square-boxes-around-unicode-characters-in).

I've hacked some on pygments on the past, and have occasionally made use of greek, etc. characters in my source, so maybe I will check it out... but nbviewer isn't going to be where it gets fixed. I'm sure PRs or whatever mercurial uses would be accepted, if you are so inclined, @Ismael-VC!
