### ISSUE TITLE
slideviewer doesn't show svg image

### ISSUE THREAD

**Issue by diegozea** [jupyter/nbviewer#331]
I'm using a markdown cell with HTML code:
```
<img src="imagen_microarray.svg" \>
```
[The slide with the problem](http://slideviewer.herokuapp.com/github/diegozea/ClasesBioInfo/blob/master/NGS/Introducci%C3%B3n%20a%20la%20secuenciaci%C3%B3n.ipynb?create=1#/40)

**Comment by bollwyvl** [comment]
Slides are live on nbviewer.Here's your deck:
http://nbviewer.ipython.org/format/slides/github/diegozea/ClasesBioInfo/blob/master/NGS/Introducci%C3%B3n%20a%20la%20secuenciaci%C3%B3n.ipynb#/40

Looks pretty good! I love the embedded pages, 

This is a brand new, not-really-publicized-yet feature. Please open any new issues about things that you find!
