### ISSUE TITLE
widget support

### ISSUE THREAD

**Issue by arsenovic** [jupyter/nbviewer#349]
any plans for this?

**Comment by parente** [comment]
I think this can be closed as resolved. nbviewer supports the frontend, JavaScript elements of ipywidgets today. Example: http://nbviewer.jupyter.org/github/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Widget%20List.ipynb

For anything involving ipywidgets that requires interaction with a backend  kernel, there's mybinder.org.
