### ISSUE TITLE
no div#notebook

### ISSUE THREAD

**Issue by minrk** [jupyter/nbviewer#352]
The structure doesn't match the live notebook because there is no `div#notebook` element. Migrating from ipython/ipython#5109

**Comment by bollwyvl** [comment]
Added this on #413... What else do we  to look out for?

**Comment by bollwyvl** [comment]
This is now live on the site!
![2015-03-03_1233](https://cloud.githubusercontent.com/assets/45380/6468208/88dd8048-c1a1-11e4-98fb-4674e02b2c0b.png)
