### ISSUE TITLE
nbviewer https/http issue?

### ISSUE THREAD

**Issue by petrushy** [jupyter/nbviewer#369]
Hi,

A notebook set that used to work I'm now getting: 
The error was: SSL certificate problem: unable to get local issuer certificate

I'm accessing it on the http address, but maybe nbviewer is using https instead?

The notebook is at:
http://www.orekit.org/forge/projects/orekit-python-wrapper/repository/revisions/master/raw/examples/TLE%20Propagation.ipynb

The nbviewer url becomes:
http://nbviewer.ipython.org/url/www.orekit.org/forge/projects/orekit-python-wrapper/repository/revisions/master/raw/examples/TLE%20Propagation.ipynb

Many thanks.

**Comment by bollwyvl** [comment]
Appears to work now with either http or https:
http://nbviewer.ipython.org/url/www.orekit.org/forge/projects/orekit-python-wrapper/repository/revisions/master/raw/examples/TLE%20Propagation.ipynb

http://nbviewer.ipython.org/urls/www.orekit.org/forge/projects/orekit-python-wrapper/repository/revisions/master/raw/examples/TLE%20Propagation.ipynb
