### ISSUE TITLE
nbviewer produces wrong .svg image links (it's throwing away the files subdirectory)

### ISSUE THREAD

**Issue by mwiebe** [jupyter/nbviewer#370]
Here's the notebook:

http://nbviewer.ipython.org/github/mwiebe/libdynd/blob/doc_intro/docs/intro-01/HowDyNDViewsMemory.ipynb

An example .svg url in the notebook is:

http://nbviewer.ipython.org/github/mwiebe/libdynd/blob/doc_intro/docs/intro-01/python_float.svg

but, this is missing the files/ part of it, it should be pointing here:

http://nbviewer.ipython.org/github/mwiebe/libdynd/blob/doc_intro/docs/intro-01/files/python_float.svg

**Comment by bollwyvl** [comment]
All of the referenced URLs have changed for this, and it seems like it has been solved.

We have upgraded to IPython 3 for nbviewer, which is doing upconversion of all found notebooks to v4. Hopefully this will avoid future issues!
