### ISSUE TITLE
reporting what should be a working ipython notebook.

### ISSUE THREAD

**Issue by flamingbear** [jupyter/nbviewer#373]
Error message pointed me to here.  I have several working Ipython Notebooks in my gist list, but this one has something incorrect.

https://gist.github.com/flamingbear/66bb6b08ecdb8daaf6a9

One thing that shouldn't matter is that I've reordered the information so that the image at the top will only work if the code below is executed (so that I can show the output to others without them having to look at code).  But as I understand the notebook .ipynb format should contain all of the information to render a static image.

I'd love some help.

Thanks
Matt

**Comment by bollwyvl** [comment]
Notebook appears to render fine. Please reopen if you experience additional issues with this notebook. Thanks for using nbviewer!
