### ISSUE TITLE
invalid notebook

### ISSUE THREAD

**Issue by jschueller** [jupyter/nbviewer#381]
hi,
this notebook did not work:
https://gist.github.com/jschueller/c8c11826c0cd29ffed95
using ipython 2.3.1, matplotlib 1.4.2

**Comment by bollwyvl** [comment]
For reference, here is the [nbviewer link](http://nbviewer.ipython.org/gist/jschueller/c8c11826c0cd29ffed95).

The real error:
> The error was: Error reading JSON notebook

Running it back a bit further:

`ValueError: Invalid control character at: line 88 column 4096 (char 6398)`

Apparently, its not lying: the JSON is not well-formed
  - according to plain old python `json.load`, line 598 and 88 (png outputs) both have weird encoding issues
    the encoding it serves from gist is `windows-1252` or `ISO-8859-1`
     - i tried a few different type of encoding/decoding, and it was fairly incooperative

If I take out the offending pngs, it [will render](http://nbviewer.ipython.org/gist/bollwyvl/c1959fc938d11ac327da).

Did you perhaps copy and paste it from a windows-only editor (i.e. notepad)? If you have the original file around somewhere, try just dragging and dropping that into the gist, and it may work.

Good luck!

**Comment by bollwyvl** [comment]
That file is still not valid JSON. Going to close this, hopefully the suggestion helped!
