### ISSUE TITLE
Latex partially rendering in light gray font

### ISSUE THREAD

**Issue by rlabbe** [jupyter/nbviewer#391]
I noticed this morning that latex equations are rendering in light gray fonts, whereas they didn't used to. 

It looks bad, because numbers are still rendered in the old style, so equations contain a mix of light gray and black text.

This is not happening in the IPython Notebook (I have version 2.3.0, on Windows and xubuntu 14.04), only on the nbviewer site.

Examples:

http://nbviewer.ipython.org/github/unpingco/Python-for-Signal-Processing/blob/master/Confidence_Intervals.ipynb

http://nbviewer.ipython.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/07_Kalman_Filter_Math/Kalman_Filter_Math.ipynb

**Comment by rgbkrk** [comment]
That is ugly. I'm not sure where that's coming from. /cc @bollwyvl

**Comment by bollwyvl** [comment]
Just to be clear: we're talking the flash of latex before it gets rendered?
![screenshot from 2015-01-10 15 40 50](https://cloud.githubusercontent.com/assets/45380/5693180/c88613da-98df-11e4-943c-2b7f31f35f74.png)
![screenshot from 2015-01-10 15 45 32](https://cloud.githubusercontent.com/assets/45380/5693181/c89a3018-98df-11e4-9149-76c2db7ca5f0.png)

It looks like `.MathJax_Preview` gets colored `#888`. Presumably, this can be coded around... but in both chrome and ff (albeit, on fedora) i am eventually seeing rendered, black math.

**Comment by rlabbe** [comment]
I'm not sure I understand your (bollwyvl) comment. Your second image depicts the problem. For example, the first equation with the 1/n - the 1 is black, the n is gray. That is not how is used to render a few days ago. Both the 1 and n would be the same font and blackness, and both the same blackness as the 1, not the n.

The flash of the raw latex code is irrelevant to me (maybe it is relevant to others?); my bug report is about the rendered output only.

**Comment by bollwyvl** [comment]
Ah, ok: i am on a laptop and it is tough to see the difference between the two shades (`#666` and `#000`). You must have better eyes/a bigger monitor than I!

This is a result of using pygments off bower. The [old one](https://github.com/jupyter/nbviewer/blob/24339854a810970df29c34259081cd16f7f4a4ef/nbviewer/static/css/pygments.css) had a namespace selector `.highlight` for everything, while the [one from bower](https://github.com/xavierdutreilh/bower-pygments/blob/master/css/default.css) does not.

While we could back to to packaging pygments.css, I've been dinking around with a less build PR which would solve this. I'll try to polish it up and get something out!

**Comment by rgbkrk** [comment]
Thanks @bollwyvl, that's my fault for how I used the pygments package on bower. Thanks for digging that out.

**Comment by bollwyvl** [comment]
@rlabbe have a look: looks good from here! thanks for the report, helped upgrade an infrastructure improvement from a "nice to have" to "user needs it".

**Comment by rlabbe** [comment]
Yup, looks great. Thanks so much!
