### ISSUE TITLE
slideviewer doesn't work (displays 400: Bad Request)

### ISSUE THREAD

**Issue by jason-s** [jupyter/nbviewer#394]
test slideshow on github gist:
https://gist.github.com/jason-s/271f74e721c6d163cc5c

It works fine in nbviewer: http://nbviewer.ipython.org/gist/jason-s/271f74e721c6d163cc5c
It does not work in slideviewer: https://slideviewer.herokuapp.com/urls/gist.github.com/jason-s/271f74e721c6d163cc5c?create=1

**Comment by Carreau** [comment]
Slideviewer is nothing official from this repo. (it's hosted on heroku, IIRC by damian avila on free account) 

We are working on integrating slides into main nbviewer (see https://github.com/jupyter/nbviewer/pull/390)

**Comment by jason-s** [comment]
OK, do you know where I submit a bug report? the website says:

>We couldn't render your notebook
>
>Perhaps it is not valid JSON, or not the right URL?
>
>If this should be a working notebook, please send us a bug report! Don't forget to read the FAQ if >you are not sure !
>
>The error was: Error reading JSON notebook

and I'm just trying to follow through on that.

**Comment by jason-s** [comment]
Argh, the site just creates the wrong URL; this URL works fine:

https://slideviewer.herokuapp.com/gist/jason-s/271f74e721c6d163cc5c

**Comment by damianavila** [comment]
Because slides are being part of nbviewer very soon, I will deperecate/remove slideviewer soon... and it will not be updates so far on slideviewer anymore... you will be able to use nbviewer to render your slides.
