### ISSUE TITLE
github APi changes: 

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbviewer#395]
https://developer.github.com/changes/2015-01-07-prepare-for-organization-permissions-changes/

**Comment by bollwyvl** [comment]
So pushing up 
```python
        kwargs.setdefault(
            'headers',
            {}
        )['Accept'] = 'application/vnd.github.moondragon+json'
```
which was accepted with this response:
```http
X-Github-Media-Type: github.moondragon; format=json
```
in 0c9a3f7 as per the GH post yielded [no errors](https://travis-ci.org/bollwyvl/nbviewer/builds/51498730). So there's that.

I didn't add any tests as I couldn't think of a case where we are constructing urls directly from user + repo-pulled-off-api, which is I think the only place this could hurt us...

Any other thoughts here?

**Comment by bollwyvl** [comment]
The day has come and gone. Let's close this and see if we get any issues!
