### ISSUE TITLE
The cookbook's nbviewer is down :(

### ISSUE THREAD

**Issue by dirkjobosman** [jupyter/nbviewer#396]
http://nbviewer.ipython.org/github/jvns/pandas-c%7C%2055ookbook/blob/v0.1/cookbook/A%20quick%20tour%20of%20IPython%20Notebook.ipynb

**Comment by Carreau** [comment]
You url seem to be wrong.

http://nbviewer.ipython.org/github/jvns/pandas-cookbook/blob/v0.1/cookbook/A%20quick%20tour%20of%20IPython%20Notebook.ipynb

did you copied and past it with a new line ? in it ? the `%7c%2055` seem to be escape sequence of `| 55` (pipe-space-55) that has nothing to do here.

**Comment by dirkjobosman** [comment]
Please view attachement :)

![nbviewer](https://cloud.githubusercontent.com/assets/2715723/5788422/dfa20e84-9e34-11e4-94d5-1196292a8516.png)

**Comment by rgbkrk** [comment]
Where is this URL coming from? This is definitely a bad link. There's an extra `%7C%2055` between `c` and `ookbook` when it should read `pandas-cookbook`.

**Comment by Carreau** [comment]
And the correct link renders great:
![capture d ecran 2015-01-17 a 16 34 23](https://cloud.githubusercontent.com/assets/335567/5789333/e516122a-9e66-11e4-8f52-b38601a90b78.png)

**Comment by Carreau** [comment]
from [here](https://github.com/Black-Milk/Dash-Docset/blob/master/HTML/pandas%200.13.1/_sources/tutorials.txt) URL is bad on source.

**Comment by dirkjobosman** [comment]
Thanks guys. I could access the link now :)
D

**Comment by Carreau** [comment]
Happy codding.

**Comment by dirkjobosman** [comment]
:)
