### ISSUE TITLE
Mention fastly as part of sponsorship

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/nbviewer#397]
Fastly now provides CDN support for nbviewer. Yay!

My idea for how we list it could be:

```
Delivered by Fastly, Rendered by Rackspace
```

Or something to that effect.

**Comment by damianavila** [comment]
Sounds good.

**Comment by rgbkrk** [comment]
Thanks to @ejgreenberg for setting us up. Fastly has been amazing.

We'll also want to post the fastly logo to the sponsors page on the main ipython website.

![image](https://cloud.githubusercontent.com/assets/836375/6049784/1ed5e0f4-ac80-11e4-8d7f-88a8f5a93915.png)
