### ISSUE TITLE
python and ruby ipynb in nbviewer cannot be displayed

### ISSUE THREAD

**Issue by wushengzhong** [jupyter/nbviewer#401]
These two links below seem not working. The ijulia example can be opened still though. I tried other ipython notebook link saved and all links not working so far.

http://nbviewer.ipython.org/github/ipython/ipython/blob/2.x/examples/Index.ipynb
http://nbviewer.ipython.org/github/minad/iruby/blob/master/IRuby-Example.ipynb

**Comment by Carreau** [comment]
Yeah, it seam we had some issues with github API yesterday. Thanks for the heads up.
