### ISSUE TITLE
Build search functionality 

### ISSUE THREAD

**Issue by danabauer** [jupyter/nbviewer#405]
This is a high-level issue to add search functionality to nbviewer. Some of the steps are:
- [ ] detect robots.txt from the originating URL so we can regard some as private
- [ ] determine how to index content in elasticsearch
- [ ] figure out how to strip out base64 encoded images so they are not indexed
- [ ] slurp in all markdown and code cells
- [ ] expose an api for the search box proposed in #252 

Feedback @rgbkrk?

**Comment by rgbkrk** [comment]
Looking great! I just updated the list into a checklist and we can flesh it out a bit more.
