### ISSUE TITLE
github links not working

### ISSUE THREAD

**Issue by btel** [jupyter/nbviewer#406]
nbviewer does not open the github-hosted notebooks anymore:

http://nbviewer.ipython.org/github/ipython/ipython/blob/2.x/examples/Notebook/User%20Interface.ipynb

renders 400 error.

is is related to #395?

**Comment by damontallen** [comment]
It's not all github notebooks just some.  I had three notebooks work then the fourth didn't.  When I tried to reload one of the loaded notebooks it failed the second time.  [My error page](http://i.imgur.com/pbfYCUx.png) was 400 as well but it also gave a 403 Forbidden message as the subtype.  That notebook rendered on previous occasions and nbconvert converts it locally to HTML without any issues.  I think it is a server issue.

**Comment by rhiever** [comment]
AFAICT, all of my notebooks hosted on GitHub are having this issue.

**Comment by rgbkrk** [comment]
Gah.

**Comment by damianavila** [comment]
Right now I can open the above link...

**Comment by rhiever** [comment]
Try this one: http://nbviewer.ipython.org/github/rhiever/big-data-hw/blob/master/K-means%20clustering.ipynb

**Comment by mjbommar** [comment]
Likewise with this repo that hadn't even had any commits:
http://nbviewer.ipython.org/github/mjbommar/cscs-530-w2015/tree/master/

**Comment by shayanjm** [comment]
Same with newly made gists - http://puu.sh/fy9Eh/eaa8b771c5.png

**Comment by tloredo** [comment]
I'm experiencing the same thing, only sometimes some of the notebooks render, and minutes later the same notebook displays a "400 : Bad Request" page, which says "The error was: HTTP 403: Forbidden".

**Comment by rgbkrk** [comment]
I'm digging into it now, would love if others try debugging locally.

**Comment by rgbkrk** [comment]
It's definitely seeming like an issue with our tokens or rate limiting. I can load all the listed notebooks locally with no auth.

**Comment by rgbkrk** [comment]
Tried with the old tokens and the new tokens, no issues. I need to launch new systems anyway as I'm on a fresh box right now, will keep you all posted.

**Comment by errcricket** [comment]
I am not really adding anything new to the conversation. Just letting GH know there is an issue rendering my notebooks and I am getting the '400: Bad Request Error'.

**Comment by rgbkrk** [comment]
Alright, we're back on track now. Sorry about the outage today. Took a bit of head scratching to make sure changes propagated across Fastly.

**Comment by rgbkrk** [comment]
How is your notebook now @errcricket?

**Comment by mjbommar** [comment]
My class notebooks look good now, and just in time to teach! (http://nbviewer.ipython.org/github/mjbommar/cscs-530-w2015/tree/master/).  Thank you!

**Comment by rhiever** [comment]
:+1:

**Comment by errcricket** [comment]
rgbkrk, my notebooks look great. Thank you very much.

**Comment by elnjensen** [comment]
I'm not 100% sure this is the same issue, but it seems like it - I tried to open http://nbviewer.ipython.org/github/adrn/ipython/blob/2.x/examples/Interactive%20Widgets/Index.ipynb and I get an http 400 error (also listing http error 403 in the message text); similar issue with some of the links above in other comments.

**Comment by mattgiguere** [comment]
Seems like a similar problem to what happened 15 days ago, @elnjensen and @rgbkrk. I'm getting a "400: Bad Request" on my notebooks and some of the examples from the nbviewer main page (e.g. http://nbviewer.ipython.org/github/unpingco/Python-for-Signal-Processing/tree/master/).

**Comment by Carreau** [comment]
@elnjensen  @mattgiguere you can get that if github Api does not respond or is down. Try to force refresh, both of your link worked for me.

**Comment by JamesSample** [comment]
Does anyone have any tips or workarounds for this, please? Is there anything I might be doing at my end to make the problem worse?

I've been seeing this error quite a lot recently, both with my own notebooks and with some of those linked from the nbviewer frontpage (e.g. http://nbviewer.ipython.org/github/unpingco/Python-for-Signal-Processing/tree/master/ ).

Thanks.

**Comment by minrk** [comment]
@JamesSample There have been intermittent issues, but it's working right now. GitHub renders notebooks on its own pages, so a workaround would be to visit the GitHub page, directly. Alternately, you can make html files yourself with nbconvert: `jupyter nbconvert --to html yournotebook.ipynb`. Most of nbviewer is downloading notebooks from the internet and caching. Turning a notebook into HTML is a single call to nbconvert that you can do yourself.

**Comment by JamesSample** [comment]
Thanks minrk, that's helpful. For some reason equations in my notebooks don't render properly when I view them directly on GitHub. Whether this is my fault or something to do with GitHub I'm not sure. Your suggestion of converting them directly to html should do the trick though - thanks!

**Comment by minrk** [comment]
Do you use Firefox? I think there's a known issue on the GitHub renderer where they do something slightly different with MathJax on Firefox.

**Comment by JamesSample** [comment]
Ha, yes, that seems to be the problem - they render correctly using Chrome. Most of the folks in my organisation are on Firefox, so for now I'll stick with converting my notebooks to html, as you suggested above. It's good to know that I can view them directly on GitHub using a different browser, though. Thanks for your help!

**Comment by aishenri** [comment]
that's still the problem !)

**Comment by parente** [comment]
The original problem reported here, an outage of the public nbviewer service, was resolved long ago so I'm going to close out this issue.

**Comment by md12g12** [comment]
Im having the same issue I think. I deleted then reuploaded a file and now am unable to use nbviewer on any new pages in that repo.
Error code: 404 : Not Found Remote HTTP 404: ML_UK_university_funding.ipynb not found among 3 files.
Link: https://nbviewer.org/github/md12g12/ML_UK_university_funding_project/blob/main/ML_UK_university_funding.ipynb
