### ISSUE TITLE
Need way to display kernel information in rendered notebook

### ISSUE THREAD

**Issue by dsblank** [jupyter/nbviewer#407]
Currently, one has to download a notebook to see basic information, such as what kernel was used to create the nbviewer notebook. Suggestions:

* An "About this notebook..." link that would show popup dialog with kernel metadata in it
* Show the kernelspec name in header, eg: `Kernel: IRuby, 2.4`

Would also be handy to have a link to find and install kernel. But that would require that there be info in the notebook, or a kernel registration API.

**Comment by bollwyvl** [comment]
I like this idea.

nbviewer's top-left corner, where the kernel branding would be on the
notebook, is getting pretty crowded... but that seems like a good place to
add this info. perhaps we have to think about a better way to organize this
area:.Certainly need to put this into the design refactor that inevitably
should happen to better match the rest of the brand.

**Comment by bollwyvl** [comment]
Partially addressed in #413, feedback welcome!

**Comment by bollwyvl** [comment]
#413 adds this in its most basic way, with a hoverable icon that shows the display name.

I don't know how we would say anything else about it right now: there is no http://jupyter.org/kernels/<kernel> namespace we can look up.

**Comment by rgbkrk** [comment]
That namespacing issue I was thinking about earlier today.

You make me think we should have an API for listing available kernel types for a given language, etc.

**Comment by bollwyvl** [comment]
Yeah, that would be a great dimension for search, as well.

As for namespaces/URLs/URIs: This is one of the places where making the
notebook, or at least the metadata, linked data (json-ld) would be great.

{
  @context: "http://ld.jupyter.org/#",
  metadata: {
    kernel: {@id: "kernel:python2"}},
    cells:[...]
}

That context would contain the contract that strings that start "kernel:"
would be an identifier and (maybe) dereferenceable into a
location/resource.

{
  @context:{
    jupyter: "http://jupyter.org/",
   Kernel: "jupyter:kernel/"
  }
}

As an enlightened consumer, nbviewer could go pull the card for that
kernel, or access local data about that uri.

If critical parts of the doc like the kernelspec were still constrained by
a json schema, then a consumer wouldn't even care about the linked data
part, so win all around you slice off the namespace.
