### ISSUE TITLE
500: Internal server error

### ISSUE THREAD

**Issue by tortarantola** [jupyter/nbviewer#410]
nbviewer is throwing an internal server error when trying to read a notebook from a Gist:
https://gist.github.com/tortarantola/cb7efd0911719a1b2688

**Comment by bollwyvl** [comment]
Looking at the gist, it appears to be in a pretty old version of the notebook format... perhaps try upgrading IPython to the most recent [2.x line](https://pypi.python.org/pypi/ipython/2.4.1) or try out the new [3.0 line](https://pypi.python.org/pypi/ipython/3.0.0rc1)?

That being said, it may be worth inserting the appropriate machinery to upgrade and render older nbformats: however, this may not happen until 3.0 stable is released.

**Comment by tortarantola** [comment]
Looks like it was a problem with the notebook extension I was using, which didn't grab the JSON code properly when posting to Gist. It works when I post it manually. Thanks!

**Comment by bollwyvl** [comment]
Great!
