### ISSUE TITLE
My inability to build from source.

### ISSUE THREAD

**Issue by pelson** [jupyter/nbviewer#419]
I'm trying to get to grips with lots of new technologies (for me), including invoke, less and even node.js, so suspect I'm doing something wrong, but I'm getting an error when invoking the less task.

```
$> invoke bower
.... everything up to date
$> invoke less 
FileError: '../components/animate.css/source/sliding_entrances/slideInDown.css' wasn't found. Tried - nbviewer/static/components/animate.css/source/sliding_entrances/slideInDown.css,/nbviewer/static/components/animate.css/source/sliding_entrances/slideInDown.css,envs/nbviewer/lib/python2.7/site-packages/IPython/html/components/animate.css/source/sliding_entrances/slideInDown.css,../components/animate.css/source/sliding_entrances/slideInDown.css in nbviewer/static/less/styles.less on line 6, column 1:
5 @import (less) "../components/animate.css/source/_base.css";
6 @import (less) "../components/animate.css/source/sliding_entrances/slideInDown.css";
7 @import (less) "../components/animate.css/source/sliding_exits/slideOutUp.css";
```

I decided to delete my static/components directory and start afresh, now:

```
$> invoke less 
FileError: '../components/font-awesome/less/font-awesome.less' wasn't found. Tried - nbviewer/static/components/font-awesome/less/font-awesome.less,nbviewer/static/components/font-awesome/less/font-awesome.less,envs/nbviewer/lib/python2.7/site-packages/IPython/html/components/font-awesome/less/font-awesome.less,../components/font-awesome/less/font-awesome.less in nbviewer/static/less/styles.less on line 3, column 1:
2 @import "bootstrap";
3 @import "../components/font-awesome/less/font-awesome";
4 
```

I've been able to successfully run ``invoke bower`` followed by ``invoke less`` before, but that was probably ~2 weeks ago.

Any advice?

**Comment by pelson** [comment]
P.S. My node modules were created with

```npm install bower less less-plugin-autoprefix less-plugin-clean-css```

**Comment by bollwyvl** [comment]
There has been a lot of churn recently on the bower components, and some of the changes are pretty significant. Bower is also notorious for cache issues... perhaps a [`bower cache clean`](http://bower.io/docs/api/#cache) is in order?

While I don't think we are super sensitive to any of the packages, we also added a `package.json`, which may help. We should probably add an `invoke npm` just to be consistent.

Here's what I am pulling off `bower list` in the Docker build (i do some node development, so don't trust my local install):
```
Step 27 : RUN cd /srv/nbviewer/nbviewer/static/ && ../../node_modules/.bin/bower --allow-root list
 ---> Running in f0c6ffbbd322
bower check-new     Checking for new versions of the project dependencies..
static#0.0.0 /srv/nbviewer/nbviewer/static
├── animate.css#3.2.3
├─┬ bootstrap#3.3.2
│ └── jquery#2.1.3
├── font-awesome#4.3.0
├── headroom.js#0.7.0
├── moment#2.8.4 (latest is 2.9.0)
├── pygments#2.0.0 (latest is 2.0.2)
├── requirejs#2.1.16
└── reveal.js#3.0.0
 ---> a37992ec9783
```
Give us a list of that, and maybe we can see what's up!

**Comment by bollwyvl** [comment]
We now have a `package.json` which should make this easier.

The invoke tasks are expecting local installs (i..e "node_modules/.bin/less") which is not exactly the norm for less and bower.

Please let us know if you have any other issues!
