### ISSUE TITLE
display-mode ($$ ... $$) equations in nbviewer

### ISSUE THREAD

**Issue by stevengj** [jupyter/nbviewer#420]
At the top of [this Matrix-multiplication-experiments.ipynb notebook](http://nbviewer.ipython.org/url/math.mit.edu/~stevenj/18.335/Matrix-multiplication-experiments.ipynb), the first markdown cell uses a "display-mode" LaTeX equation delimited by ``$$ .... $$`` (as opposed to inline equations `$ ... $`).  It renders fine in IPython (IJulia) 2.x, but nbviewer displays it as text.

(Also, nbviewer gives up on displaying subsequent equations in that markdown cell.)

Are display-mode equations (which are useful to display large equations on their own centered line) not supported by nbviewer

**Comment by minrk** [comment]
Any difference in mathjax config from the live notebook is a bug, either in nbconvert or nbviewer.

**Comment by Carreau** [comment]
It seem like mistune is making  thinks italic between C_ and \sum_  ...
-- 
M

**Comment by stevengj** [comment]
Here is [another example notebook](http://nbviewer.ipython.org/url/math.mit.edu/~stevenj/18.335/Wilkinson-Polynomial.ipynb) with a problem in display-mode equations.   Scroll down to the *Companion matrices* section: in the text there is a `begin{pmatrix} ... \end{pmatrix}` equation that displays fine in the notebook, but whose formatting is screwed up in nbviewer.

**Comment by empet** [comment]
This [IPython Notebook](http://nbviewer.ipython.org/github/empet/geom_modeling/blob/master/FP-Bezier-Bspline.ipynb) was displayed correctly when I uploaded it on github, early in february. Now some LaTeX formulas are displayed verbatim. There are two triangular matrices both delimited by $$...$$  The first one is displayed verbatim, but the second it's OK.

**Comment by bollwyvl** [comment]
I'll take a look at getting mistune to behave...

**Comment by bollwyvl** [comment]
So there's mistune_contrib:

https://github.com/lepture/mistune-contrib/blob/master/mistune_contrib/math.py

Will investigate...

**Comment by bollwyvl** [comment]
The upstream ipython/ipython#8066 was merged, so the next time nbviewer is deployed (from the upstream docker image) this should be fixed. Bits of those notebooks ended up in the tests!

Stay tuned!

**Comment by damianavila** [comment]
Nice!

**Comment by bollwyvl** [comment]
The deployment fairy came at some point and built against the upstream. This now appears to be fixed, but there are some concern about the fix's elegance. Be vigilant, we may see some regressions if our assumptions were incorrect. Or, we may hear back from mistune about a better way, and revisit. In any event, thanks all, for the report and samples!

**Comment by stevengj** [comment]
Thanks!
