### ISSUE TITLE
Inconsistency between jupyter and nbviewer rendering

### ISSUE THREAD

**Issue by celiasmith** [jupyter/nbviewer#422]
As shown with this notebook:
http://nbviewer.ipython.org/github/celiasmith/syde556/blob/master/bugs.ipynb

nbviewer can't compile the latex.  However, if you download that and view it in jupyter directly, it renders fine.  (I take it that this kind of discrepancy is a bug).

**Comment by bollwyvl** [comment]
Very possible related to #420.

**Comment by bollwyvl** [comment]
ipython/ipython#8066 should fix this on next deploy. Stay tuned!

**Comment by bollwyvl** [comment]
More detail on #420 but tl: dr; fixed and deployed! keep an eye out for more problems, and thanks!
