### ISSUE TITLE
nbviewer not synching with github

### ISSUE THREAD

**Issue by nejohnson2** [jupyter/nbviewer#425]
I received a 400 error on a notebook that had rendered fine in the past.  Then looking at some older notebooks, the nbviewer notebook is not the same as what is on github.  Even downloading a notebook from nbviewer is different from what is displayed on nbviewer.  It seems that nbviewer is not synching with github...

Example notebook from nbviewer:

http://nbviewer.ipython.org/github/nejohnson2/modeling-waste/blob/master/notebooks/CT_Income.ipynb

**Comment by Carreau** [comment]
There is a 10 minutes caching+CDN, so you might get a bit of delay between pushing to github and seeing new page. But we don't store or sync notebook. What I see now seem in sync to me... have you a local chaching ?

**Comment by nejohnson2** [comment]
Thanks!  That seemed to be the issue with the notebook.  Though I'm still receiving a 400 Bad Request error from another notebook.  There have been a couple of github issues related but I can't seem to find a good explanation on what's going on and how to fix it.

http://nbviewer.ipython.org/github/nejohnson2/trash-itp-2015/blob/master/syllabus/syllabus.ipynb

**Comment by bollwyvl** [comment]
No longer appears to be an issue. Please reopen if you have additional problems. Thanks for using nbviewer!
