### ISSUE TITLE
Restore scroll for long slides

### ISSUE THREAD

**Issue by bollwyvl** [jupyter/nbviewer#433]
So I thought _ever having_ the scroll was a bug... Clutter, certainly won't ever print out, breaks the metaphor, etc. I like the alternative proposal that allows output cells to be turned into sub/fragments. But many people on the list have cried out for the scroll, so we should put it back.

Probably a one line change!

**Comment by damianavila** [comment]
>So I thought ever having the scroll was a bug... 

Was extensively discussed in the past :wink:

>Clutter, certainly won't ever print out, 

I did not test the printing lately, but we, eventually we can modify the css to fix the printing...

>breaks the metaphor, etc. 

How?

>I like the alternative proposal that allows output cells to be turned into sub/fragments. 

Me too... this is way almost all my slides does not use the scroll... but I can understand the use case for other people, mainly in slideshows derived from IPython notebook...

>But many people on the list have cried out for the scroll, so we should put it back.

I agree...

**Comment by bollwyvl** [comment]
>> breaks the metaphor, etc.
> How?
Just Tufte, information architecture kinda stuff: the "wall of text" slide that nobody can process in the amount of time that one would want to spend on talking about it is bad enough, but the "Great Wall of Text" that just keeps scrolling is particularly inimical to getting one's point across.

Further, we can presently hyperlink to a particular slide with the `#<hslide>/<vslide>` anchors (and should add the slide ID for custom anchors eventually!) but I am pretty sure reveal woudn't honor inside-the-page scrolling for anchors, since it owns hashchange and ignores things that don't fit its scheme.

**Comment by damianavila** [comment]
>Just Tufte, information architecture kinda stuff: the "wall of text" slide that nobody can process in the amount of time that one would want to spend on talking about it is bad enough, but the "Great Wall of Text" that just keeps scrolling is particularly inimical to getting one's point across.

Yeah, I see your point...

>  I am pretty sure reveal woudn't honor inside-the-page scrolling for anchors, since it owns hashchange and ignores things that don't fit its scheme.

Yep, probably that's the case...

**Comment by damontallen** [comment]
Playing devil's advocate for the "wall of text" there are circumstances where having a scrolling slide is not necessarily a bad thing.  For instance if the slides are used as the primary information for an online class being able to keep both the a description and example on one slide is beneficial to students (think page in a book).  This may require a slide that is bigger than what can fit on a single screen.  

This is not uncommon in engineering and I can think of at least one example where it would be better to have a scrolling slide than multiple slides.  The showing of beam loading, shear diagram, moment diagram, curvature diagram, and deflection diagrams need to be vertically aligned to really get an understanding of the interactions between them and they would not fit on a single non-scrolling slide.

**Comment by bollwyvl** [comment]
Sure, all good stuff. Timeline.js is a fine horizontally scrolling slide!

Actually would love something like bulletjournal.com, and use the scroll as
an actual unit to update widgets i.e wavelength in an exploration of the
spectrum... Very gimmicky, but again, slides _are_ a gimmick. And we have
some limitations given how the upstream works re: slide size.

For example, i really want to get the print-pdf css working... I know, i
know, PDF/ppt is where data goes to die. But i still want it.

Making printing work with scrolling content is probably going to be
hard/hacky... But haven't started yet, so i can't tell.

Gh was ddos all weekend, but will circle back soon!

**Comment by damianavila** [comment]
>Making printing work with scrolling content is probably going to be
hard/hacky... But haven't started yet, so i can't tell.

We can be a little Spartan here and say to people: "if you want pdf, just do slides without scrolling".
I don't think we should provide printing support for scrolling slides, but per the reasons exposed by @damontallen, I think we need to support the scrolling in the html and just be happy with the limitations...
