### ISSUE TITLE
403 (Forbidden) error for notebook in a github repo

### ISSUE THREAD

**Issue by dkirkby** [jupyter/nbviewer#434]
The following is giving me a 403 error:

http://nbviewer.ipython.org/github/desihub/desispec/blob/%236/doc/nb/SpectroPerfectCoadds.ipynb

Could it be a problem with my branch name '#6' which requires escaping in the URL?

**Comment by bollwyvl** [comment]
Yeah, my usual tricks don't work. Rawgit, etc.

Linking the current commit itself is fine:
http://nbviewer.ipython.org/github/desihub/desispec/blob/4435140ac225b2a6120831618d806b428d38eedb/doc/nb/SpectroPerfectCoadds.ipynb

So it's not the notebook json.

We have an open PR (#411) for slashes, but pounds may be a bit more
difficult... and will always, always have to be escaped, even if they did
work.

**Comment by rbu** [comment]
should this be working? The ipynb url loads fine
http://nbviewer.ipython.org/github/ResearchComputing/Meetup-Fall-2013/blob/master/python/lecture_12_pandas_groupby.ipynb

**Comment by bollwyvl** [comment]
Works fine for me! We are aware of an ongoing issue with github API access
which causes intermittent 403s... Well, we're aware we have it. Not sure
what to do about it!

**Comment by Sjnjerak** [comment]
I'm having the same problem as rub. I'm using minrk's extension to make notebooks into secret gists https://github.com/minrk/ipython_extensions.

**Comment by bollwyvl** [comment]
Should be fixed by #572. Please reopen, perhaps linking to this ticket, should the problems persist!
