### ISSUE TITLE
Error 403 with gist of notebook (ipython 3.x)

### ISSUE THREAD

**Issue by LunarLanding** [jupyter/nbviewer#438]
Said gist is : https://gist.github.com/LunarLanding/5f8d568c41670e3fefc2
Linbk given to nbviewer is: http://nbviewer.ipython.org/5f8d568c41670e3fefc2
It resolves to: http://nbviewer.ipython.org/gist/LunarLanding/5f8d568c41670e3fefc2
And gives:
"400 : Bad Request
We couldn't render your notebook
Perhaps it is not valid JSON, or not the right URL.
If this should be a working notebook, please let us know.
The error was: HTTP 403: Forbidden"

**Comment by bollwyvl** [comment]
That is a strange, hand-made document.

It claims it is in the [v3](https://gist.github.com/LunarLanding/5f8d568c41670e3fefc2#file-untitled-ipynb-L34) notebook format, but doesn't have the `worksheets` key, which was required.

Manually changing it to v4 makes it work:
http://nbviewer.ipython.org/gist/bollwyvl/bcc7512ac09509eb06b0

How did you create this file?

**Comment by Carreau** [comment]
We should raise a NaN (Not a Notebook) and have a special page for that.

**Comment by bollwyvl** [comment]
Here's the [stack trace](https://gist.github.com/anonymous/ccce5e528aebafbbeb17).

Should nbformat raise the `NotANotebook`, or is this entirely a downstream thing?

**Comment by Carreau** [comment]
We can probably raise some things in nbformat, like depending on wether
it's not json, or not valid Json format.

**Comment by LunarLanding** [comment]
I created this by using the gist notebook extension: https://github.com/minrk/ipython_extensions/blob/master/nbextensions/gist.js
I've traced the issue to the notebook format number hard-coded in it. I changed it to 4 and it fixed it. Thanks for the intel!

**Comment by bollwyvl** [comment]
Ah! Sounds good!

**Comment by Carreau** [comment]
That does not explain how the 3was here in the first place...

**Comment by minrk** [comment]
> That does not explain how the 3was here in the first place...

The gist.js used to hardcode `nbformat = 3`. It was fixed a while ago.

**Comment by LunarLanding** [comment]
Uh. I must have downloaded a fork or something :p . Below isn't hard coded.
Thanks again!
https://github.com/minrk/ipython_extensions/blob/master/nbextensions/gist.js
