### ISSUE TITLE
How to render ipython slide.html? 

### ISSUE THREAD

**Issue by Tashitso** [jupyter/nbviewer#441]
It worked for me to render .ipynb in nbviewier, but now after I converted my .ipynb to slides that is not in JSON and I can't render it in nbviewier.  How can I render ipython slide.html ? 
Thanks for your help!

**Comment by damianavila** [comment]
You only need to point to the ipynb file as with nbviewer and once loaded you have a button at the top right (present icon, the third one from the right) you have to press it to get the slides mode.

![present](https://cloud.githubusercontent.com/assets/1640669/7022463/84a140c4-dd02-11e4-8e75-05169e069d0a.png)

**Comment by bollwyvl** [comment]
Probably need some doc, too, though!

**Comment by Tashitso** [comment]
![screen shot 2015-04-07 at 11 50 52 am](https://cloud.githubusercontent.com/assets/4327881/7028581/5d0d4480-dd1c-11e4-8f53-fa5e44345d03.png)
This is a screenshot of ipython slides on my local machine but how I can share it with others or publish it? I tried to render it in nbveiwer but after it converted to slides.html did not work.

**Comment by Carreau** [comment]
don't convert to html, just publish the .ipynb.

**Comment by Tashitso** [comment]
Thanks it worked!

**Comment by bollwyvl** [comment]
Yup.

Here's a gist of your slide:
https://gist.github.com/bollwyvl/54453b856d27301e60d8

Here's the link to the slides on nbviewer: note how the end of the URLs are the same, after the `/gist/` provider:
http://nbviewer.ipython.org/format/slides/gist/bollwyvl/54453b856d27301e60d8

Gist is just an example: anywhere where you can publicly store the `.ipynb` file will work.

**Comment by bollwyvl** [comment]
Heh, too late to the party.

Closing this.
