### ISSUE TITLE
"404: Not Found"

### ISSUE THREAD

**Issue by kubu4** [jupyter/nbviewer#445]
Getting the following error message when I try to view NBviewer links to my notebooks:
"404 : Not Found
You are requesting a page that does not exist!
The remote resource was not found."

All of my notebooks are hosted here:
http://eagle.fish.washington.edu/Arabidopsis/iPythonNotebooks

My notebooks were rendering just fine as of last week, so I'm not sure why all of my NBviewer links are now giving me the 404 error. 

Going to that link above, you can access all of my notebooks, suggesting that the URLs are working URLs and are publicly accessible.

Any thoughts/suggestions/help would be greatly appreciated.

Thanks!

**Comment by rgbkrk** [comment]
Uh oh, I think this is nbviewer failing when it doesn't find a robots.txt...

Hopping on it now.

**Comment by rgbkrk** [comment]
Hey @kubu4, this has been [fixed and shipped](http://nbviewer.ipython.org/url/eagle.fish.washington.edu/Arabidopsis/iPythonNotebooks/InstallingBLAST.ipynb). Thanks for reporting it. Sorry about your notebooks being off for a bit there.

**Comment by kubu4** [comment]
Sweet! Thanks for the quick response and fix!
