### ISSUE TITLE
support for plain .nb?

### ISSUE THREAD

**Issue by Pomax** [jupyter/nbviewer#451]
I read the announcement that notebooks render via nbviewer on github, which is awesome! but is there also support for plain .nb files? It would be great to see https://github.com/Pomax/Pomax.github.io/blob/master/gh-weblog/downloads/canonical-curve.nb as a notebook, instead of plain text, for instance.

**Comment by bollwyvl** [comment]
What generates `.nb` files? Ah, just read the commit: mathematica.

I don't foresee us (nbconvert t/f nbviewer) or github supporting mathematica notebooks... maybe ever. To be sure, the wolfram toolchain is one of the most beautiful pieces of software engineering ever, but it departs from the "open" manifesto in so many ways.

One thing I *could* see is writing an [nbconvert importer](https://github.com/ipython/ipython/issues/4930) to generate an `ipynb` from an `nb`, but a great deal would be lost in translation: we have many fewer cell types, for example.

**Comment by Carreau** [comment]
You can also write a mathematica kernel.

**Comment by bollwyvl** [comment]
right, but it still wouldn't speak `.nb`...

**Comment by Carreau** [comment]
Who need `.nb` when you have `.ipynb` it's `ipy` more awesome.

**Comment by Carreau** [comment]
@takluyver agrees.

**Comment by ellisonbg** [comment]
I agree that it is very unlikely *we* will ever build support for Mathematica ourselves. That isn't to say *someone* couldn't tackle that with a full Mathematica Kernel, etc. Would be interesting to think about...

**Comment by Carreau** [comment]
Well I don't see why we would not write a Mathematica kernel once we buy them.

**Comment by damianavila** [comment]
:trollface: ^^^
