### ISSUE TITLE
Plots from IRkernel not displayed on Github

### ISSUE THREAD

**Issue by takluyver** [jupyter/nbviewer#453]
https://github.com/IRkernel/IRkernel/blob/master/Demo.ipynb (scroll to bottom)

We think this is because nbconvert prefers svg to png, and then Github strips SVG after it has chosen. Github should configure the `display_data_priority` to choose png before svg.

**Comment by flying-sheep** [comment]
actually i like that we uncover bugs in other products by using SVG by default :laughing:

**Comment by rgbkrk** [comment]
Love me some svg.

**Comment by flying-sheep** [comment]
i contacted github regarding this, let’s see what happens.

**Comment by parente** [comment]
This issue has been inactive for a few years now. If it was reported upstream, are we OK to close?

**Comment by flying-sheep** [comment]
Well, nothing came back from them. Does someone else want to ask?

**Comment by parente** [comment]
@flying-sheep do you recall how you asked originally? I'd like to list in the issue template where folks should send requests about the github rendering.

**Comment by flying-sheep** [comment]
Oh! seems like it was fixed, so this can be closed anyway!

https://gist.github.com/flying-sheep/07b28faf15ed3d32d0a5404e78a56879
