### ISSUE TITLE
Notebook download fails

### ISSUE THREAD

**Issue by odebroqueville** [jupyter/nbviewer#454]
I couldn't download the notebook from the following page:
http://nbviewer.ipython.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Chapter1.ipynb

I just got a 'Ignore alert/Go back' dialog box which wouldn't do anything when selecting either option!

**Comment by damianavila** [comment]
I could download it w/o problem. Can you report more info about browser, platform, etc. Cheers.

**Comment by odebroqueville** [comment]
I'm using Safari Version 8.0.6 (10600.6.3) on Mac OS X Yosemite 10.10.3.

I tried disabling the usual suspects, i.e. Safari extensions Ghostery, Blur and AdBlock Plus, but it doesn't change a thing!

AH! I found the problem! I had Kaspersky Anti-virus installed, which itself installs the Safari extension "URL Advisor 15.0". After disabling it, the dialog box disappeared and the following file (which looks like a JSON file) was rendered in my browser. It doesn't download anything but it renders that file in my browser (would be nicer if it actually downloaded the file, but not a must!).

https://raw.githubusercontent.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/master/Chapter1_Introduction/Chapter1.ipynb

I'll report this to Kaspersky and now close this issue.

Thanks & cheers

**Comment by bollwyvl** [comment]
Thanks @odebroqueville! Thanks for following up on this.

**Comment by odebroqueville** [comment]
The latest update to Kaspersky Internet Security for Mac 2015 (15.0.1.378 at time of writing, which includes the Safari extension URL Advisor 15.4) solves the issue.

**Comment by rgbkrk** [comment]
Yay for a vendor fixing things!
