### ISSUE TITLE
Pandas Cookbook notebook chapter 5 is not working

### ISSUE THREAD

**Issue by michaelreinhard** [jupyter/nbviewer#460]
I am really new to all this and I may be wrong, but it seems that the notebook for Pandas Cookbook chapter 5, the one on Canadian weather, is not working. I have been working through them and having not problems but when I got to the In[4] line of code, executing it leads to a long and--to me at least--incomprehensible error message. 

Here is the URL of the notebook:
http://localhost:8888/tree/pandas-cookbook/cookbook#
The specific notebook is: 
Chapter 5 - Combining dataframes and scraping Canadian weather data

Any ideas?

**Comment by Carreau** [comment]
> http://localhost:8888/tree/pandas-cookbook/cookbook#

Hum this is the url on your local machine, so I cannot see it. 
Are you talking about [this](https://github.com/jvns/pandas-cookbook) pandas cookbook ? If so It would ask on the linked repo, the author will probably be more able to respond to you than us.

**Comment by michaelreinhard** [comment]
Ah, thanks, that makes sense. I’ll get in touch with him. Thanks for your help.

**Comment by Carreau** [comment]
> Ah, thanks, that makes sense. I’ll get in touch with him

I think it's a her. (just FYI)
