### ISSUE TITLE
IPython Latex math problem display

### ISSUE THREAD

**Issue by odadoun** [jupyter/nbviewer#461]
There is a problem to convert ipynb to html with Latex formula (then my slides are not well displayed). This problem is know and can be fixed by modifying   mathjax.tpl (c328740.ssl.cf1.rackcdn.com by cdn.mathjax.org).

**Comment by rgbkrk** [comment]
Can you share a link to the notebook you're talking about?

**Comment by odadoun** [comment]
http://slideviewer.herokuapp.com/github/odadoun/Ipython-Notebook/blob/master/Slides/slides_fe55_dadoun_May2015.ipynb#/
go to slide 3 : \(K_{\alpha}\)  is not well display

**Comment by rgbkrk** [comment]
That's what I suspected. That's @damianavila's original slide viewer. `K_{\alpha}` appears fine at http://nbviewer.ipython.org/format/slides/github/odadoun/Ipython-Notebook/blob/master/Slides/slides_fe55_dadoun_May2015.ipynb#/2 (though it appears the entire slide is lowered).

**Comment by odadoun** [comment]
Yes perfect ! thank a lot ;)

**Comment by odadoun** [comment]
So good address is not anymore http://slideviewer.herokuapp.com/ , what is the good one ?

**Comment by rgbkrk** [comment]
Use nbviewer.ipython.org, paste your URL in, click Go!, then click the little present: 
![screenshot 2015-05-27 08 48 27](https://cloud.githubusercontent.com/assets/836375/7837514/1236d158-044d-11e5-9b7a-7d76f7f21a49.png)

Alternatively, add `/format/slides/` after the nbviewer domain and before your URL `github/odadoun/Ipython-Notebook/blob/master/Slides/slides_fe55_dadoun_May2015.ipynb`:

**Comment by odadoun** [comment]
Can you please have a look on this slide: http://nbviewer.ipython.org/format/slides/github/odadoun/Ipython-Notebook/blob/master/Slides/slides_fe55_dadoun_May2015.ipynb#/6
It seems that the scrolling menu is not working :(

**Comment by rgbkrk** [comment]
@bollwyvl perhaps that's an issue with our navbar on slides?

**Comment by odadoun** [comment]
I don't think so. I have tried under Chrome, Safari & Firefox ...

**Comment by odadoun** [comment]
it seems ok here
http://slideviewer.herokuapp.com/github/odadoun/Ipython-Notebook/blob/master/Slides/slides_fe55_dadoun_May2015.ipynb#/5/4

**Comment by damianavila** [comment]
The scroll issue will be fixed here: https://github.com/jupyter/nbviewer/pull/439

@bollwyvl is waiting for another pair of eyes... @rgbkrk? :wink:

**Comment by bollwyvl** [comment]
Can't see the issue on phone... Will try later when at computer. Hopefully the fix works from that pr, but it hadn't deployed yet.

Sadly, restoring scrolling long slides will break mobile even more. :sigh:

**Comment by odadoun** [comment]
I see . Maybe the scrolling can be apply only if we don't use mobile ....

**Comment by damianavila** [comment]
> I see . Maybe the scrolling can be apply only if we don't use mobile ....

It could be a good compromise...

**Comment by bollwyvl** [comment]
Scrolling fix has been deployed! Reopen, with a link to the notebook in question, if the problems persists!
