### ISSUE TITLE
Allow startup flags from docker container

### ISSUE THREAD

**Issue by log0ymxm** [jupyter/nbviewer#463]
We'd like to be able to deploy using the dockerfile, but it doesn't look like there's a way to include startup flags doing it this way. In our case we want to add "--no-cache" to the running nbviewer.

**Comment by bollwyvl** [comment]
Near term, you could just specify your own command to override EXEC...
Either at the command line,  in your own docker-compose.yml or as your own
dockerfile.

Over on the wip providers pull request, I'm making the new config flags
configurable via environment variables, in  the style of nose. Once that
lands, we should probably make all of the switches configurable through env.

**Comment by log0ymxm** [comment]
Yeah, I realized I could just override the command in the dockerfile, right after I posted this. I didn't get around to checking that it would work, but it should. Setting the config option with an env variable will probably be the long term preferred method, especially for docker deployments. Thanks.

**Comment by rgbkrk** [comment]
Well, you could run it as

```
docker run python -m nbviewer --port=8080 --no-cache
```

since it's defined as a `CMD`, not an `ENTRYPOINT`
