### ISSUE TITLE
slides broken

### ISSUE THREAD

**Issue by cranmer** [jupyter/nbviewer#469]
I'm looking at 
http://nbviewer.ipython.org/format/slides/github/glouppe/tutorial-sklearn-lhcb/blob/master/An%20introduction%20to%20Machine%20Learning%20with%20Scikit-Learn.ipynb#/

that points to this notebook
https://github.com/glouppe/tutorial-sklearn-lhcb/blob/master/An%20introduction%20to%20Machine%20Learning%20with%20Scikit-Learn.ipynb

That works. Now I try to do the same for this notebook

http://nbviewer.ipython.org/github/cranmer/parametrized-learning/tree/master/DecomposingTestsOfMixtureModels.ipynb

using this URL

http://nbviewer.ipython.org/format/slides/github/cranmer/parametrized-learning/tree/master/DecomposingTestsOfMixtureModels.ipynb#/

but it's not working.

**Comment by bollwyvl** [comment]
Same as #466. Looking into it! Thanks for the data points!

**Comment by bollwyvl** [comment]
Fixed in production. Please open new issues if you experience additional problems! Thanks for using nbviewer!
