### ISSUE TITLE
XSS in GitHub directory listings

### ISSUE THREAD

**Issue by bburky** [jupyter/nbviewer#471]
nbviewer allows browsing directory listings of the files in GitHub repositories. These directory listings do not properly sanitize the filenames and enable an XSS attack when rendered into HTML.

The the following URL and GitHub repository demonstrate the issue:
http://nbviewer.ipython.org/github/bburky/xss/tree/%3Cscript%3Ealert(1)%3C%2fscript%3E/
https://github.com/bburky/xss

See also #472

**Comment by Carreau** [comment]
Thanks for the report.

For information this has been posted after the OP did report the security issue on security@ipython.org, which is the right thing to do. As the point of nbviewer is to allow arbitrary html/js this was not considered as needing to stay private. Hence this issue.

**Comment by bburky** [comment]
The same issue also exists in the directory listing of gists too:

http://nbviewer.ipython.org/gist/bburky/c020825874798a6544a7

**Comment by bollwyvl** [comment]
Fix deployed!
