### ISSUE TITLE
XSS in GitHub Gist file not found error message

### ISSUE THREAD

**Issue by bburky** [jupyter/nbviewer#472]
The error message for files not found in a gist includes the missing filename to be included in the 404 response. This filename is unsanitized for HTML and enables an XSS. 

Chrome's XSS auditor will hide this simple XSS, look in the devtools console to see the error.

http://nbviewer.ipython.org/gist/bburky/7763555/%3Cimg%20src%3Dx%20onerror%3Dalert%281%29%3E

See also #471

**Comment by Carreau** [comment]
For information this has been posted after the OP did report the security issue on security@ipython.org, which is the right thing to do. As the point of nbviewer is to allow arbitrary html/js this was not considered as needing to stay private. Hence this issue.

**Comment by bollwyvl** [comment]
Thanks for the issue! There are likely other places where things are not
escaped correctly... I suppose we can't hide behind, "but there point is
_enabling_ xss!" On everything.

**Comment by bburky** [comment]
Yeah, there are some other escaping issues. This same bug I think has weird behavior with `%0a`  (a newline) getting uneacaped and producing multiple lines of output in the log.

And a separate bug I forgot to report: go to the directory listing linked in #471 and click the "filetypes" link to get a 404 error. That branch name has a slash in it which gets accidentally unescaped.

**Comment by bollwyvl** [comment]
The slash situation is another story, #411 :) But would certainly like to
knock out, "people might make bad urls on <provider>" in a consistent way

**Comment by rgbkrk** [comment]
As I said in a private thread, I'd suggest starting with setting `autoescape=True` in the jinja2 environment:

https://github.com/jupyter/nbviewer/blob/7c530ee028c78ce522be4c1f422f47775d364460/nbviewer/app.py#L158

**Comment by bollwyvl** [comment]
Fix deployed!
