### ISSUE TITLE
localfile directory traversal

### ISSUE THREAD

**Issue by bburky** [jupyter/nbviewer#473]
The localfile provider allows directory traversals. A root directory is accepted as a command line argument to nbviewer, but requests are not prevented from escaping this root.

For example, when running using the Docker configuration and the `-localfiles=/srv/nbviewer/nbviewer/static` argument added to the nbviewer command, it is possible to access the notebook at `/srv/nbviewer/tests/notebook.ipynb` using the URL http://docker.local:8080/localfile/%2e%2e/tests/notebook.ipynb

Use curl to test this (Chrome likes to remove `..` and `%2e%2e` from URLs):

```
$ curl http://192.168.99.100:8080/localfile/%2e%2e/tests/notebook.ipynb
```

The following is logged by nbviewer:

```
[I 150624 04:37:57 handlers:36] looking for file: '/srv/nbviewer/nbviewer/static/../tests/notebook.ipynb'
[I 150624 04:37:57 base:505] rendering 287 B notebook from ../tests/notebook.ipynb
[I 150624 04:37:57 log:53] 200 GET /localfile/%2e%2e/tests/notebook.ipynb (192.168.99.1) 157.38ms
```

I realize localfile is documented as "this can be a security risk", but it isn't sandboxed to the specified path. It could probably use a stronger warning too.

**Comment by Carreau** [comment]
Yeah, localfile is ment roughly only for debug purposes, like when you are fixing bug in a train or an a plane. Should be more explicit about that.

do you want to make a PR that use log.critical if people use localfile ?

**Comment by pelson** [comment]
> I realize localfile is documented as "this can be a security risk", but it isn't sandboxed to the specified path. It could probably use a stronger warning too.

Incidentally, I stood up an internal nbviewer over a year ago before localfile existed, and one of the goals of that was to view all files outside of the specified path. Just wanted to point out that that is a desirable thing sometimes, but I agree, a more specific warning might be a good idea here.

**Comment by Carreau** [comment]
I see the need for localfile, and it is oft requested, Though, if localfile
you have, you can likely nbconvert locally and have access to last modif
date-time to be much more efficient. so --localfile is probably no well
suited.

**Comment by bollwyvl** [comment]
While working on provider entry points (need to revisit, might be ready for
review), i added path checking to chain it to a location... URLs with ".."
in them are never, ever good in my mind.

**Comment by bollwyvl** [comment]
Fix deployed (not that production uses localfile anyway....)
