### ISSUE TITLE
wrong display of a mixture of markdown and html

### ISSUE THREAD

**Issue by empet** [jupyter/nbviewer#479]
Lately I noticed that  titles in my IPython Notebooks, written as
`##<center> Title < /center>##`, are  wrong displayed by nbviewer although some time ago they were displayed OK:
http://nbviewer.ipython.org/urls/gist.githubusercontent.com/empet/b1344d9bf0325bb4531b/raw/Random_Walk.ipynb

**Comment by bollwyvl** [comment]
If _some time_ was before we went to ipython3, then it is known. IPython went to mistune, and we pretty much just use what the upstream uses except in dire cases. Of course, in the notebook app, we use marked in its default, very permissive mode, which lets us get away with these things, much to the chagrin of those of us that have to use whatever comes out of nbconvert.

Mistune is a bit of a stickler for the markdown and html specs, and doesn't think very highly of [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center) tags like `center`. We have enough problems with getting latex, etc. working, and probably won't be doing any aggressive configuration to make that particular tag come back from the dead.

A `<span style="text-align:center">` would do the trick, verbose as that may be. Another option is to include your own css, and make all `h2`s centered, for example.

**Comment by empet** [comment]
Thank you very much for  suggesting alternatives!
