### ISSUE TITLE
Dropbox links for notebooks stopped working

### ISSUE THREAD

**Issue by cchwala** [jupyter/nbviewer#480]
The problem seems to be that nbviewer.ipython.org does something wrong when trying to get the "raw download" URL from the dropbox link I usually provide.

Example:
Working nbviewer link from maybe two month ago
http://nbviewer.ipython.org/urls/dl.dropbox.com/s/p9qyjmv06wglqsx/Read%20CSV%20data%20for%20Abidjan.ipynb?dl=0

Dropbox link from some minutes ago
https://www.dropbox.com/s/p9qyjmv06wglqsx/Read%20CSV%20data%20for%20Abidjan.ipynb?dl=0

Letting nbviewer do its job, I get
http://nbviewer.ipython.org/urls/dl.dropbox.com/s/p9qyjmv06wglqsx/Read%2520CSV%2520data%2520for%2520Abidjan.ipynb/%253Fdl%253D0
and a HTTP 403: Forbidden

The differences seem just to be the URL path encondings of the special characters (?, =, space).

**Comment by BjornFJohansson** [comment]
I have a problem that I think is caused by the same issue. I also serve IPyhton notebooks
from dropbox (this is a great way to share notebooks). I have local files in the same folder
as the notebook and I link to them in markdown cells:

    [file](file.ext)

This worked until a couple of days ago. See [example](http://nbviewer.ipython.org/urls/dl.dropboxusercontent.com/u/1263722/local_link2.ipynb?flush_cache=true)

This breaks nbviewer for me! Is this a bug or a feature?

**Comment by bollwyvl** [comment]
Curious indeed. I'll have a look into it, though probably this evening.

**Comment by BjornFJohansson** [comment]
Thanks! I am about to submit a paper that depends an app that produces a folder of notebooks
with links to files contained in the folder and other notebooks.

**Comment by satra** [comment]
same issue here.

**Comment by rgbkrk** [comment]
Hmmm, that's looking like double encoding to me.

**Comment by bollwyvl** [comment]
Yes, there is fairly naive url_encoding occuring in base that cam in from #421. Having Travis take a look, seeing what's going on...

**Comment by bollwyvl** [comment]
Yep, that was in there to fix unicode encoding issues which crop up in python 3. At this point, I think it's just in the tests, as the browsers seem to do the Right Thing... but not making tremendous headway.

**Comment by BjornFJohansson** [comment]
I use chrome on Linux, Firefox on windows show the same problem.
Thanks for the time you put in to this!

**Comment by bollwyvl** [comment]
Looks like this has been deployed. Reopen if there are issues! Thanks again!

**Comment by BjornFJohansson** [comment]
Perfect, my test notebook works now! 
Thanks for this fix.
/bjorn

**Comment by cchwala** [comment]
At first I still had problems in Firefox, probably due to the browser cache. But after refreshing the nbviewer page several times and/or trying the same link in Chrome, I can say, it works now. 
Thanks!
