### ISSUE TITLE
Add extra format

### ISSUE THREAD

**Issue by thomasyu888** [jupyter/nbviewer#483]
Hello,

We have an open source platform -> synapse.org, and it would be incredibly nice to be able to use nbviewer inside of this platform.  Every file in synapse has a syn ID, so if I stored: example.ipynb, it will also have a syn ID (ie. syn3048291).  Please kindly advise me where I need to add code to make it so that nbviewer accept something like: synapse: syn... which will then render the notebook. I have examined the code a bit and would want utils.transform_ipynb_uri("synapse syn...") to form u'/synapse/syn.../' then go forward from there.

**Comment by bollwyvl** [comment]
We've adopted the "provider" name for what you are describing: "formats"
are different views of what providers provider: slides, html, ???

Take a look in `providers`: the simplest one is dropbox, which just
rewrites dropbox share links into their cdn equivalent with uri_rewrites.
https://github.com/jupyter/nbviewer/blob/8aee4d40b5c14e3735eb20a3943ec1f66d0d604b/nbviewer/providers/dropbox/handlers.py

The uri rewrite is half the battle, as it just redirects. So it could turn
^syn\d+$
into

You'll also need a handler to actually go get the thing. If you want it to
be a "vanity" url, you might just copy-paste URLHandler:
https://github.com/jupyter/nbviewer/blob/8aee4d40b5c14e3735eb20a3943ec1f66d0d604b/nbviewer/providers/url/handlers.py#L34

Sorry, no examples of that yet.

A word of warning: never serve an nbviewer on the same domain as your
trusted application. We don't sanitize anything, so a bad notebook opened
by an admin... POOF.

synapse.org/nbviewer <- BAD
viewer.synapse.org/ <- GOOD

For this reason, we also don't (probably won't) support any form of
authentication, though I would be interested in collaborating on this as an
externally-managed project, preferably over OAuth.

**Comment by thomasyu888** [comment]
Apologies for the delayed response.  Thank you for your help.  I will let you know if I run into any trouble.

**Comment by bollwyvl** [comment]
Sounds great! Keep us posted. Near term, we'll start using Jupyter as our
upstream, but not much should change api-wise.
