### ISSUE TITLE
notebook 1 :  IOError on exercice 3,4,5,6 ( loading.data problem)

### ISSUE THREAD

**Issue by casdidier** [jupyter/nbviewer#485]
Hi guys, I imported the project on my workspace. Opened up cleanly. 

And i get error for , i checked all files, they're ok so what's the matter? 

air = np.loadtxt('holland_temperature.dat') 
sea = np.loadtxt('holland_seawater.dat')
plt.fill_between(range(1,13),air,color='b',alpha=0.3)
plt.fill_between(range(1,13),sea,color='r',alpha=0.3)
plt.xticks([0,1,2,3,4,5,6,7,8,9,10,11],['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'])
plt.xlim(1,12)
plt.ylim(0,20)
plt.xlabel('Month')
plt.ylabel('Temperature (Celcius)');

---------------------------------------------------------------------------IOError                                   Traceback (most recent call last)<ipython-input-62-7f583553f3fe> in <module>()
----> 1 air = np.loadtxt('holland_temperature.dat')
      2 sea = np.loadtxt('holland_seawater.dat')
      3 plt.fill_between(range(1,13),air,color='b',alpha=0.3)
      4 plt.fill_between(range(1,13),sea,color='r',alpha=0.3)
      5 plt.xticks([0,1,2,3,4,5,6,7,8,9,10,11],['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'])
C:\Users\didier\AppData\Roaming\Python\Python27\site-packages\numpy\lib\npyio.pyc in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin)
    736                 fh = iter(bz2.BZ2File(fname))
    737             elif sys.version_info[0] == 2:
--> 738                 fh = iter(open(fname, 'U'))
    739             else:
    740                 fh = iter(open(fname))
IOError: [Errno 2] No such file or directory: 'holland_temperature.dat'

**Comment by bollwyvl** [comment]
Reply to all
I think this might not be the right format for what you are looking!

From your traceback (always helpful!) you may want to go check out:
- https://github.com/numpy/numpy
- http://numpy-discussion.10968.n7.nabble.com/

Good luck!
