### ISSUE TITLE
Feature request: for blank cells only, after selecting heading level via keyboard, switch to edit mode immediately

### ISSUE THREAD

**Issue by DmitriR** [jupyter/nbviewer#489]
... and place the cursor **after** the hashmarks. 

Currently, it is necessary to 
(1) type (e.g.) 2 to select heading level 2
(2) type ENTER to get into editing mode
(3) move cursor to after hashmarks
before writing the title. Should be easy to implement.

**Comment by Carreau** [comment]
Did you ment to open that on jupyter/notebook ?
You can also just write the title and change to Heading 2 after, the hashes will be prepended. 
You can slo remap your keyboard if you like.

**Comment by DmitriR** [comment]
Yes, jupyter/notebook.
To type first and then change would take more keystrokes: fist get to editing mode, then out and change to heading. What's the point? 
Not sure how remapping the keyboard would help. 
I just want to hit (say) 2 and then continue typing in the editing mode, already in the correct place. 
Same goes for the Markdown mode more generally: why not directly allow input after switching to Markdown? I will add this as another request, I guess.

**Comment by Carreau** [comment]
> To type first and then change would take more keystrokes: fist get to editing mode, then out and change to heading. What's the point?

It depends on how you use the notebook, 
getting to edit mode after each cell type change will definitively be annoying for many people like me that edit the structure of the notebook more than they write. 

I will tend to write title in a code cell, go to command mode, change to title, and alt-enter to insert a new cell in edit-mode. 

The first prototype was actually change cell type then go into insert-mode. It was annoying. 

> Not sure how remapping the keyboard would help. 

remap in the sens that you can change what the shortcut are doing, if you want 1 - 6  to change to header, and get into insert mode, or even want Cmd-Shit-Number to change the cell type while in insert mode, nothing prevent you to do it. 

The default keyboard shortcut are only default one. There are more restriction that just what we would like, among other having something consistent, that work across OSes, and Browsers, not break the habits of people already used to shortcuts.

**Comment by DmitriR** [comment]
> It depends on how you use the notebook,
getting to edit mode after each cell type change will definitively be annoying for many people like me that edit the structure of the notebook more than they write.

OK, I can certainly understand that. I was only thinking about *empty* cells, not the ones with text already. Would immediate switch for empty cells *only* interfere with the type of workflow you described? In fact, what is the use case for changing the type of an empty cell and then not editing it?

> The first prototype was actually change cell type then go into insert-mode. It was annoying. 

I respect empirical data! But perhaps this was implemented for both filled and empty cells?

**Comment by Carreau** [comment]
I think the reason for not switching on empty cell is consistency. 
I do agree that in many case it make sens, but it might seem complicated as to when we switch to command mode and when not.

@ellisonbg might remember better, but I am one of the dev beeing relatively vocal on heuristics that try to do the right thing. 

My typical example is iOS keyboard, if you ever type using more than 2 keyboard, then you have no way of knowing what the "switch keyboard" button will do, as it depends of the history of previous keyboard you were using. In most case it switches to the previous layout (and autocorrect dictionary) except when it doesn't. Which make the user (me in this case) check at every switch which keyboard it is. I would much rather get 2 keypress and consistent switch in order French-> English -> Emoji-> French as then I can type without looking. 

Same goes for going to edit mode (IMHO), if the switch is context dependent, then it will completely break the though workflow of advance user, and totally confuse newcomers as to when it does what.

You are free to try it, and we can direct you on how to reconfigure your mapping to do that, and you can tell us what you think, that would be a data point. Maybe you will like it.

**Comment by DmitriR** [comment]
>I think the reason for not switching on empty cell is consistency.
I do agree that in many case it make sens, but it might seem complicated as to when we switch to command mode and when not.

>@ellisonbg might remember better, but I am one of the dev beeing relatively vocal on heuristics that try to do the right thing.

Consistency vs 'doing the right (most reasonably expected) thing' is a real dilemma... I (but that's just me) tend to prefer the DWIM approach, consistency be damned. (There's also this ripped-out-of-context quotation from Emerson regarding foolish consistency :)

> My typical example is iOS keyboard, if you ever type using more than 2 keyboard, then you have no way of knowing what the "switch keyboard" button will do, as it depends of the history of previous keyboard you were using. In most case it switches to the previous layout (and autocorrect dictionary) except when it doesn't. Which make the user (me in this case) check at every switch which keyboard it is. I would much rather get 2 keypress and consistent switch in order French-> English -> Emoji-> French as then I can type without looking.

I frequently use 2 keyboards (on OSX though) and I know exactly what you are referring to. 

> Same goes for going to edit mode (IMHO), if the switch is context dependent, then it will completely break the though workflow of advance user, and totally confuse newcomers as to when it does what.

*IF* this will break the flow, then of course this is a wrong idea. My question is, I guess: "are there any circumstances at all when somebody will change the type of an empty cell and then not start editing it immediately?" If this test is passed, then it would be an interesting case to find out, empirically, whether it confuses novices or not. But I completely acknowledge that this could be an issue, at least theoretically (basically there would be like 8 different ways to get into edit mode *on an empty cell*: all headings commands, switch-to-markdown command, and the standard way). 

> You are free to try it, and we can direct you on how to reconfigure your mapping to do that, and you can tell us what you think, that would be a data point. Maybe you will like it.

Yes, this will be perfect. I am happy to just keep this as a customization in my init files or something like that; please tell me how. Thanks!

If it does work the way I think it will though, I suspect others will want to have it as well. Maybe in that case it might become a (very simple) extension package, or a configuration note.

**Comment by ellisonbg** [comment]
One of the main ideas in efficient user interfaces is the idea of enabling users to build habitual patterns of usage that don't require thought. Anytime you make an action depend on hidden state, a user has to stop, think about that hidden state, and decide what to do. If users always choose the same decision branch there could be a benefit to having that hidden state, but if users end up choosing different branches, the hidden state just slows them down.

That is not to say that your own usage may actually benefit from the change you propose and its hidden state. I would just implement it in your config with a custom action or keyboard shortcut.

**Comment by DmitriR** [comment]
Brian - thank you for your comment!
> That is not to say that your own usage may actually benefit from the change you propose and its hidden state. I would just implement it in your config with a custom action or keyboard shortcut.
> 
Yes, I will do that. If you can point me to some examples on custom actions, I would appreciate that. 
> One of the main ideas in efficient user interfaces is the idea of enabling users to build habitual patterns of usage that don't require thought. Anytime you make an action depend on hidden state, a user has to stop, think about that hidden state, and decide what to do. If users always choose the same decision branch there could be a benefit to having that hidden state, but if users end up choosing different branches, the hidden state just slows them down.
> 
I very much agree with this general statement. I am not entirely sure how it is applicable to my proposal though: where is the hidden state? (perhaps whether the cell is blank or not?) In any case, it seems to me that the key issue is whether some habitual patterns of work would be disrupted. 

Let's consider specific examples: 

(1) The user hits 'M' to set the current BLANK cell to markdown type. In the current model, the cell type changes, but it does not become editable. To my mind, the natural next action is to start editing the cell; otherwise why change its type? And the next step is to edit it, why not put it into editing mode? I can't quite see what decision branching will be induced (and misdirected) by immediate switch to editing mode in this situation. 

(2) likewise, the user switches the current BLANK cell to heading 2. Currently, the hashmarks appear but the cell does not become editable. What is the expected or probable alternative to editing the cell immediately? 

I am not trying to broaden the discussion to whether modal interfaces are a good thing. I am merely saying that even within the confines of the chosen vi-type modal interface it may be possible, without breaking the overall coherence of the UI model, add some DWIM exceptions that will be generally useful. 

I fully admit that I may be wrong because I have failed to consider some usage patterns (in fact, prevalent usage patterns) where this would be a disruption. I am perfectly OK with just making the configuration changes locally (I assume there are accessible js APIs to do this). 

Dmitri

**Comment by Carreau** [comment]
http://carreau.gitbooks.io/jupyter-book/content/kerneljs.html and https://github.com/jupyter/scipy-advanced-tutorial/blob/master/Part1/extensions/hello-scipy-full.js#L111 will help you, the 2 have diverge but started with the same base, you'll find info. ping me if you have issues. 


The hidden state depend on the point of view and how you consider keyboard shortcut. 
From the muscle memory point of view the fact that the cell is empty or not is an hidden variable.
The action of the keys  m and 1 to 6 is to convert to header/markdown, the action is independant
from any other variable, it act only on the type.

**Comment by DmitriR** [comment]
> http://carreau.gitbooks.io/jupyter-book/content/kerneljs.html and https://github.com/jupyter/scipy-advanced-tutorial/blob/master/Part1/extensions/hello-scipy-full.js#L111 will help you, the 2 have diverge but started with the same base, you'll find info. ping me if you have issues.
> 
Thanks!

> The hidden state depend on the point of view and how you consider keyboard shortcut. 
> From the muscle memory point of view the fact that the cell is empty or not is an hidden variable.
> The action of the keys m and 1 to 6 is to convert to header/markdown, the action is independant
> from any other variable, it act only on the type.
> 
OK, I guess the element of muscle memory you are referring to is the need to *always* hit ENTER before editing anything. If that is the case, then this is the crux of the matter: it is that action (and the need to reposition the cursor afterwards, in the case of headings) that I found superfluous and annoying. Anyhow, I think this has been sufficiently discussed (and found to hit the conflict of DWIM vs formal consistency, which is a philosophical matter :). Thank you for responding. I will address this locally.

**Comment by DmitriR** [comment]
Hi @Carreau,
I think getting most of what I was referring to via keyboard shortcuts is straightforward (below); so far I just cannot figure out how to move the cursor to the end of the cell (past the hashmarks) once the cell is in heading mode and editable. Is this done via calling codemirror functions? Any pointers? 
Thanks!

    IPython.keyboard_manager.command_shortcuts.add_shortcut('ctrl-3', {
        help: 'set celll to Heading 3, editable',
        handler: function (event) {

            //c = IPython.notebook.get_selected_cell(); 
            IPython.notebook.to_heading(undefined, 3);
            IPython.notebook.edit_mode();
            return false;
        }
    });

**Comment by Carreau** [comment]
Hum, try something like

```
c.code_mirror.setCursor({line:0, ch:9})
```

and try not to refer the the global IPython in your handler:

```
handler: function (env) {
        var c = env.notebook.get_selected_cell(); 
        env.notebook.to_heading(undefined, 3);
        c.code_mirror.setCursor({line:0, ch:4})
        env.notebook.edit_mode();
        return false;
    }
```

(Not tested)

Codemirror manual is [here](http://codemirror.net/doc/manual.html) if it can help.

**Comment by DmitriR** [comment]
This looks like it should do exactly what I am looking for, but the cursor does not move. I tried entering edit_mode before or after setCursor(), and also tried to move the cursor by 2 chars (so I am not addressing beyond existing chars); does not work. 

The call to setCursor() appears correct per the docs, and c.code_mirror.setCursor is seen as a function object in the handler, so I'm not sure what's going on. 

There are keyboard shortcuts in the notebook to move to start/end of the line; are they implemented this way?

Thanks!

**Comment by Carreau** [comment]
If I enter that manually in notebook js console it does work. 

No the shortcut are handeled by codemirror itself, so i"m not sure how. 

I'll try to investigate when I have a bit more time.

**Comment by DmitriR** [comment]
Sounds good. 

In the meantime, could you please let me know how you ran the test in the notebook.js console? Are you referring to using %%javascript? I tried it (using global IPython object) and the cell type changes but the cursor does not move. 

I also tried to inject the handler using the Firefox console, and setting the cell type works but again the cursor does not move.

The cursor does move on the _second_ invocation of the shortcut on the same cell, when the ## are already inserted (in both Firefox and Chrome on OSX). It also moves if the cell is already in markdown mode. It does not move if the cell is code or raw.

Thanks!

**Comment by DmitriR** [comment]
I think I found a working combination. 
Cursor positioning works if get_selected_cell() is called _after_ setting the heading level.
So the code below works for me.

Thanks!


    IPython.keyboard_manager.command_shortcuts.add_shortcut('ctrl-3', {
        handler: function (env) {
            env.notebook.to_heading(undefined, 3);
            var c = env.notebook.get_selected_cell(); 
            env.notebook.edit_mode();
            c.code_mirror.setCursor({line:0, ch:4})
            return false;
        }
    });

**Comment by Carreau** [comment]
Ok, happy you figured it out !

And for js console I was refering to the developper tools/firebug.

Sorry I was away the last couple of days.

**Comment by DmitriR** [comment]
No problem! You provided 95% of the solution. 

Firebug - understood (that thing is amazing)
I thought that maybe there was a separate development console for the Notebook hiding somewhere

Thanks
