### ISSUE TITLE
Broken link: notebook tutorials / "JavaScript Notebook Extensions"

### ISSUE THREAD

**Issue by coej** [jupyter/nbviewer#490]
In: http://nbviewer.ipython.org/github/ipython/ipython/blob/3.x/examples/Notebook/Index.ipynb
the link: [JavaScript Notebook Extensions](http://nbviewer.ipython.org/github/ipython/ipython/blob/3.x/examples/Notebook/JavaScript%20Notebook%20Extensions.ipynb)
Is broken.

**Comment by bollwyvl** [comment]
Raised this as a PR on the upstream:
https://github.com/ipython/ipython/issues/8751

**Comment by bollwyvl** [comment]
And thanks, @coej!

**Comment by bollwyvl** [comment]
Fixed!
