### ISSUE TITLE
LaTeX rendering badly in Windows 10 via Edge & Firefox, on github rendered notebooks only

### ISSUE THREAD

**Issue by rlabbe** [jupyter/nbviewer#491]
I cannot reproduce this personally.

A user of my notebooks reports that if he uses nbviewer to view my notebooks in Windows 10 using either the Edge or firefox browsers all of the latex equations render incorrectly (screen capture attached). Chrome renders it accurately. This only started happening recently - of course that could mean a change on his machine, or a change in nbviewer. 

My notebooks do use custom css, so it is possible that it is my fault. 

All notebooks render fine in github and using a local copy of IPython (3.x) and Jupyter (4.0).  He has tested it on his IPad and it works fine. I've tested on several machines, including Windows 10, and it works for me. I've also tested in Edge using a free Windows 10 virtual machine downloaded from Microsoft this morning with nothing extra installed by me. All work for me.

I'm not a web developer and at a loss as to how to debug this.

Captures show configuration and the rendering of Edge,firefox, and chrome (in that order left to right).

This is the link to the Notebook that caused that rendering issue. however, the same problem happens with all of the notebooks in my repository: http://nbviewer.ipython.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/10-Unscented-Kalman-Filter.ipynb

![capture1](https://cloud.githubusercontent.com/assets/5308143/9499190/bf94e9d0-4bd2-11e5-993f-7868d343d2e6.PNG)
![capture](https://cloud.githubusercontent.com/assets/5308143/9499199/c7e152d6-4bd2-11e5-9288-9575298e2dd2.PNG)

**Comment by bollwyvl** [comment]
Thanks for the thorough report... though the screenshots show github... which is _not_ nbviewer.

I don't know if we officially support any Internet Explorer, since it's non-trivial for us to test on it, as not every user who hacks in some JavaScript or CSS will necessarily take its... special... features... into account. Github suggests that one should ensure that ["standards mode" is enabled](https://help.github.com/articles/supported-browsers/): perhaps have your user try that?

LaTeX support is hell, and the github folks have been pinged several times with respect to it.

**Comment by AlanTJohnstone** [comment]
I am the user that had the problem and I think I have been misleading you.
if I access the content using 
http://nbviewer.ipython.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/table_of_contents.ipynb
then I have no problems.
if I type "github kalman rlabbe" into a browser I find the github page and when I click on a chapter  when I am using Edge or Firefox I have the problem. I thought that this was opening nbviewer to do the reading but from what you say above I was wrong about that.

**Comment by bollwyvl** [comment]
Yeah, you only get the link to nbviewer from Github in the top right
(little circle with a line horizontal through it) when they strip
JavaScript from the page, i think. This is still a good place to report it!
Are you indeed in standards mode?

**Comment by AlanTJohnstone** [comment]
I cannot see the little circle with a line horizontal through it screen grab attached
![capture](https://cloud.githubusercontent.com/assets/3252205/9522650/b1a942f2-4ccd-11e5-9d73-e3662c416a92.PNG)

In Firefox the page is in standards mode.
I cannot find it in Edge. Right clicking on the page gives a choice of SelectAll,Inspect element and View Source. Clicking View Source freezes the program and I have to use Task manager to get rid of it so something is not right!( That happens on other pages not just Github)

**Comment by Carreau** [comment]
FYI, Should look like that on hover:

<img width="591" alt="screen shot 2015-08-27 at 16 18 49" src="https://cloud.githubusercontent.com/assets/335567/9522862/55a28dc4-4cd7-11e5-883e-4007402b4d7b.png">

**Comment by AlanTJohnstone** [comment]
Yes I suppose that was obvious. I have to select a file first!!
Then all the problems disappear - so nbviewer works just fine.
Limited rendering is the problem

**Comment by Carreau** [comment]
You canuse github's contact à human, and/or we can move/duplicate it on a private channel where we can pin the right github people. Can someone not traveling do it/check that it's not already reported there?
-- 
M

Envoyé de mon iPhone

**Comment by AlanTJohnstone** [comment]
For me I can use Chrome or nbviewer so this is not urgent for me. 

Alan

**Comment by jklymak** [comment]
Did someone submit a bug report for this?  I have this problem w/ github latex as well.  Happy to file a report.  

Also, I don't see the hover over (i.e. https://github.com/jklymak/Phy411/blob/master/lectures/Test.ipynb)

Thanks,  Jody

**Comment by rgbkrk** [comment]
I've reported it to them now, though I think they've heard about this one recently as well.

**Comment by AlanTJohnstone** [comment]
I had completely forgotten about this, Please close it.

Alan

**Comment by parente** [comment]
@AlanTJohnstone thanks. Just doing some issue tracker grooming. Closing now.
