### ISSUE TITLE
Any edit to a line of code causes an undefined Name error

### ISSUE THREAD

**Issue by bhc3** [jupyter/nbviewer#492]
I'm going through the Apache Spark Starter Tutorial 1: Load Data.ipynd  via the Bluemix portal. I decided to alter a line of code in the tutorial, to test the functionality. For the 'weather' element, there is a code line that prints the first record in the file: weather.first().

I decided to change that function to one that worked on the preceding code line: weather.count(). I made the change and clicked the Run arrow button to update the Notebook.  

Rather than print the record count, I got an error telling me the 'weather' name was not defined. Here's the actual text:

-------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-f5d4baa3f9b4> in <module>()
----> 1 print "The first line in the 2015.csv dataset:", weather.count()

NameError: name 'weather' is not defined
-------------------------------

I'm attaching a screenshot of the error. Not sure why the 'weather' name is recognized on initial load, but becomes undefined on a simple edit.

![jupyter notebook error - undefined name](https://cloud.githubusercontent.com/assets/4078075/9535644/6244881a-4cd8-11e5-9f24-4c333313ffaa.png)

**Comment by rgbkrk** [comment]
Howdy! This is the repository for a web app that renders static notebooks. In the future, you'd want to report this to github.com/jupyter/notebook

Looking at the code and the NameError, this seems like something I'd try to reproduce and report to the BlueMix team through their support channels.

**Comment by bollwyvl** [comment]
@bhc3 have you run all the cells above that cell? actual deletion of names is pretty tough, but if they haven't been defined yet...

**Comment by bhc3** [comment]
Hi @bollwyvl  -

Thanks for your response, you prompted me to try some new things. I did a number of individual Run and Run All commands on the notebook. I specifically clicked Run for the cell that was breaking, but I did so without making any changes. 

I then did the edit described in the bug. This time, it worked. No NameError. 

Thanks for your help.

Hutch

**Comment by bollwyvl** [comment]
Hooray!
