### ISSUE TITLE
url to localhost 

### ISSUE THREAD

**Issue by TomConlin** [jupyter/nbviewer#497]
When using juypter locally the local file 'foo' is accessible as
as a link in the notebook to:  http://localhost:8888/edit/foo

Viewed  on github with the notebook and file foo in the same repository the local link fails.
changing the url to make it work on github will break it when the repo is local.

Is having  nbviewer reinterpret http://localhost:8888/  to more a appropriate url  a viable option?

**Comment by Carreau** [comment]
Don't use absolute URL, use relative ones like [myfile](../foo.txt) it should works.
The `edit/` part will not work as what is delivered is the editor not the file, but we are thinking on how to do that.

**Comment by TomConlin** [comment]
it is a bit hackey but making a dummy directory named "edit" in the repo
and putting a copy of the files linked to in it is working.

relative linking without edit/ treated text as markup  ruining formatting  (locally)

**Comment by Carreau** [comment]
> relative linking without edit/ treated text as markup ruining formatting (locally)

Not sure what you mean by that,

**Comment by TomConlin** [comment]
when running jupyter locally, 
links omitting the "http://localhost:8888" part and the "edit/" part as suggested ,
are interpreted as html as far as I can tell, so carefully formatted text files 
loose their formatting when displayed that way.

which is what led to the 
(bound to come back and bite me with maintenance) 
copy/symlink of the file into th bogus "edit/" directory for display in nbviewer on GH.

**Comment by bollwyvl** [comment]
Relative links are indeed the jam.... nothing to fix here...
