### ISSUE TITLE
writing-a-new-provider docs - 404 error

### ISSUE THREAD

**Issue by epifanio** [jupyter/nbviewer#499]
Hi, on the main readme at the section :  [writing-a-new-provider](https://github.com/jupyter/nbviewer#writing-a-new-provider) i got a 404 error 

There are several already additional providers [proposed/requested](https://github.com/jupyter/nbviewer/blob/master/jupyter/nbviewer/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aprovider)

**Comment by minrk** [comment]
closed by #500
