### ISSUE TITLE
https not working ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbviewer#501]
https://nbviewer.org/ give me a dreamhost page. 

did we forget some migration ?

**Comment by minrk** [comment]
@fperez @rgbkrk can we migrate nbviewer.org to Jupyter's DNS, away from DreamHost?

**Comment by rgbkrk** [comment]
It's fine by me, as I've stated before. I just don't have access to that DNS record.

Here's what they need to be changed to:

```
Current Nameservers	Change Nameservers to:
ns1.dreamhost.com	marek.ns.cloudflare.com
ns2.dreamhost.com	vida.ns.cloudflare.com
ns3.dreamhost.com	Remove this nameserver
```

As soon as DNS propagates, it's all set. CloudFlare is already configured to point to our current setup.

**Comment by fperez** [comment]
Done!

**Comment by fperez** [comment]
Modulo DNS propagation, this should be good.
