### ISSUE TITLE
Latex error with strikethrough

### ISSUE THREAD

**Issue by kennysong** [jupyter/nbviewer#502]
Exporting as PDF gives an error when there's strikethroughs in the markdown text. The webpage displays the error "nbconvert failed: PDF creating failed", and the server displays the error,

```
(/usr/local/texlive/2014/texmf-dist/tex/latex/ucs/data/uni-0.def)
    ! Undefined control sequence.
    l.240 by \sout
                  {Matlab's} Python's \texttt{exp} function. For which of the
    ?
    ! Emergency stop.
    l.240 by \sout
                  {Matlab's} Python's \texttt{exp} function. For which of the
    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.
```

**Comment by bollwyvl** [comment]
This repository is for the web service that powers `nbviewer.jupyter.org`. At present, we don't support PDF generation, though it has been requested in the past in #279.

If you have started this integration, PR, and we'd love to explore adding this feature as `/format/pdf/`

However, You're probably looking for [jupyter/nbconvert](/jupyter/nbconvert)! Good luck!
