### ISSUE TITLE
"backend read error" on recent IJulia notebook

### ISSUE THREAD

**Issue by stevengj** [jupyter/nbviewer#503]
I got "Error 503 backend read error" when trying to [use nbviewer](http://nbviewer.ipython.org/url/math.mit.edu/~stevenj/18.303/lecture-2.ipynb) to display [this IJulia notebook](http://math.mit.edu/~stevenj/18.303/lecture-2.ipynb) saved by (Anaconda) IPython 3.2.

Any tips would be appreciated.

**Comment by bollwyvl** [comment]
Probably a github throttle hiccup.

Appears to be working for me...

**Comment by stevengj** [comment]
Ah, great, it works for me now too.  False alarm, sorry.
