### ISSUE TITLE
503 backend read error on github hosted notebooks

### ISSUE THREAD

**Issue by StuartLittlefair** [jupyter/nbviewer#504]
I have a series of notebooks hosted on github. Each notebook is <25MB in size but the directory containing them is 66MB in total, including associated data files.

I get *intermittent* "503 backend read errors" when trying to view these notebooks, or view the containing directory on nbviewer. Most attempts to view are unsuccessful.

e.g.

http://nbviewer.ipython.org/github/StuartLittlefair/python-teaching/blob/master/PHY241/release/Session2/01_plotting.ipynb

http://nbviewer.ipython.org/github/StuartLittlefair/python-teaching/blob/master/PHY241/

**Comment by willingc** [comment]
@StuartLittlefair Thanks for filing an issue on this. I've seen similar intermittent issues yesterday as well.

@minrk @rgbkrk Is this related to Fastly and Varnish (Varnish cache was mentioned in the error that I received yesterday)? Perhaps similar to #408.

**Comment by bollwyvl** [comment]
The Github 503s are a known issue with Github api  throttling. If an actual
asset you load (img, movie) is larger than the cutoff, you might still get
broken links.

The most reliable workaround is to use rawgit.com... Use the sha-based cdn
link when/if you publish!

**Comment by StuartLittlefair** [comment]
I'm not convinced this is a github throttling issue. To test this I uploaded my notebooks to my own work server. The notebook below loads basically no assets (except a style sheet of size 3.6 kB) but I almost always get a 503 backend read error...

https://nbviewer.ipython.org/url/slittlefair.staff.shef.ac.uk/teaching/notebooks/PHY241/release/Session1/00-intro.ipynb

**Comment by bollwyvl** [comment]
Most of these related to throttling should be fixed with #572. Please create a new issue (though feel free to link to this one) if such problems persist!

**Comment by gebetix** [comment]
http://nbviewer.jupyter.org/url/anytask.org/media/files/b1fe42df-08a3-457a-970c-b309d41dbacf/Lab_2.ipynb

Not only github hosted notebooks

![2016-03-09 18 26 56](https://cloud.githubusercontent.com/assets/4972649/13636746/5b7318f8-e625-11e5-9cbb-45c90ef6439f.png)
