### ISSUE TITLE
Slideshow option not available due to trailing number sign

### ISSUE THREAD

**Issue by knedlsepp** [jupyter/nbviewer#505]
I was trying to get nbviewer.ipython.org to show a test slideshow:

http://nbviewer.ipython.org/github/knedlsepp/cpp-anfaenger-kurs/blob/solutions/slides/00_Einfuehrung.ipynb#

but the "gift" icon is missing, so I can't change the view to slideshow.
It seems that the trailing number sign "#" in the link is the culprint, because the following link works as expected:

http://nbviewer.ipython.org/github/knedlsepp/cpp-anfaenger-kurs/blob/solutions/slides/00_Einfuehrung.ipynb

**Comment by bollwyvl** [comment]
No problem: thanks for using nbviewer!
