### ISSUE TITLE
Restore Scrolling Slides. Again.

### ISSUE THREAD

**Issue by bollwyvl** [jupyter/nbviewer#506]
It's #433, #439 all over again. My selective memory prevents me from noticing non-scrolling slides as a bug.

This somehow got broken again likely when we moved over to jupyter with #493.

See [this comment](https://github.com/jupyter/nbviewer/issues/466#issuecomment-142063405)

**Comment by damianavila** [comment]
Thanks for opening this one... please assign to me I will take a look during the week (I also detect some other css failures we need to fix)

**Comment by jakirkham** [comment]
Thanks for looking into this guys. Sorry to raise, what I have now found to be, a controversial topic.

**Comment by bollwyvl** [comment]
@jakirkham Thanks! We really do appreciate it, even if we/I seem a bit grumpy :trollface:
