### ISSUE TITLE
Cannot create empty figure

### ISSUE THREAD

**Issue by DanielLenz** [jupyter/nbviewer#510]
I was just wondering if the error was on my side or if something weird is going on:

    Anaconda 2.3.0
    Python 2.7.10
    matplotlib 1.4.3
    jupyter 1.0.0
    ipython 4.0.0

Starting notebook via `jupyter notebook`
    
    [In 1] %matplotlib inline
    [In 2] import matplotlib
    [In 3] fig = matplotlib.pyplot.figure()

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    /Users/dlenz/anaconda/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
        335                 pass
        336             else:
    --> 337                 return printer(obj)
        338             # Finally look for special method names
        339             method = _safe_get_formatter_method(obj, self.print_method)
    
    /Users/dlenz/anaconda/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in <lambda>(fig)
        207         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
        208     if 'retina' in formats or 'png2x' in formats:
    --> 209         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))
        210     if 'jpg' in formats or 'jpeg' in formats:
        211         jpg_formatter.for_type(Figure, lambda fig: print_figure(fig, 'jpg', **kwargs))
    
    /Users/dlenz/anaconda/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in retina_figure(fig,     **kwargs)
        124     """format a figure as a pixel-doubled (retina) PNG"""
        125     pngdata = print_figure(fig, fmt='retina', **kwargs)
    --> 126     w, h = _pngxy(pngdata)
        127     metadata = dict(width=w//2, height=h//2)
        128     return pngdata, metadata

    /Users/dlenz/anaconda/lib/python2.7/site-packages/IPython/core/display.pyc in _pngxy(data)
        607 def _pngxy(data):
        608     """read the (width, height) from a PNG header"""
    --> 609     ihdr = data.index(b'IHDR')
        610     # next 8 bytes are width/height
        611     w4h4 = data[ihdr+4:ihdr+12]
    
    AttributeError: 'NoneType' object has no attribute 'index'
    
    <matplotlib.figure.Figure at 0x1077d4250>

If I do instead

    [In 4] fig = matplotlib.pyplot.figure()
           matplotlib.pyplot.imshow(np.random.randn(100, 100))

it works like a charm.

**Comment by bollwyvl** [comment]
@DanielLenz this is the repo for nbviewer.jupyter.org, so I don't think we can be of much help to you here.

I'm not certain where this should go... very possibly [ipython/ipython](ipython/ipython), as that is where the magic lives, but it could be an matplotlib issue.

You could also try posting on [gitter](https://gitter.im/ipython/ipython), or on the [mailing list](mailto:ipython-dev@scipy.org)!

Good luck!
