### ISSUE TITLE
R kernel always dead: Jupyter and conda for R

### ISSUE THREAD

**Issue by RaymondChia** [jupyter/nbviewer#518]
I installed R-Essentials by following the steps in https://www.continuum.io/blog/developer/jupyter-and-conda-r. But when I run "Jupyter notebook" and start a R kernel, the kernel is always dead, and terminal feeds back: 
*[I 09:25:00.040 NotebookApp] KernelRestarter: restarting kernel (4/5)
/home/ray/anaconda3/lib/R/bin/exec/R: symbol lookup error: /home/ray/anaconda3/lib/R/bin/exec/../../lib/../../libreadline.so.6: undefined symbol: PC*

Does anyone know how to handle it? Thanks.

**Comment by rgbkrk** [comment]
You may want to report this over on the https://github.com/IRkernel/IRkernel issue tracker, this repo is for the notebook viewer.
