### ISSUE TITLE
Slideshow Service via nbviewer

### ISSUE THREAD

**Issue by damianavila** [jupyter/nbviewer#52]
Ok, this issue is mainly to discuss how we will deal with a service such as nbviewer2, but for reveal-based slideshow...

Some time ago with @Carreau and @ellisonbg we discuss a little bit about that...

Now, that we have nbviewer2 going strong, I came up to discuss about this issue... before implementing some things ;-)

What do you think about that? I would be easy to add a button (and the functionality to render...) for slideshows in the current nbviewer2, but maybe we want to keep it isolate, just nbviewer2, and get another domain with a twin "slideviewer".

Cheers.

Damián.

**Comment by bollwyvl** [comment]
Fixed with #390.
