### ISSUE TITLE
403 (Forbidden) error for notebook in a github repo

### ISSUE THREAD

**Issue by signalrunner831** [jupyter/nbviewer#524]
I'm trying to get this repo to open
https://github.com/deeplearningparis/dl-rnn/blob/master/minimal_RNN.ipynb

by copying it into the viewer search

and by typing it out as
http://nbviewer.ipython.org/github/deeplearningparis/dl-rnn/blob/master/minimal_RNN.ipynb

and the viewer and It returns the above error.

**Comment by jmportilla** [comment]
I'm also getting a 403 error on all of my Notebooks.

**Comment by Darkade** [comment]
Same here

**Comment by willingc** [comment]
@signalrunner831 @jmportilla @darkade Thanks for the reports. This issue (#522) is being actively worked on. Thanks for your patience.

cc/ @carreau Please close as duplicate issue. Thanks.

**Comment by Darkade** [comment]
@willingc thanks.
