### ISSUE TITLE
bokeh tutorial notebooks fail to load

### ISSUE THREAD

**Issue by mwsmith2** [jupyter/nbviewer#525]
I tried several notebooks meant as tutorials for using bokeh in jupyter, and none of the links rendered popular.  In particular, the last url I check was http://nbviewer.ipython.org/github/bokeh/bokeh-notebooks/blob/master/quickstart/quickstart.ipynb.

**Comment by bollwyvl** [comment]
@mwsmith2 we are aware of the outage: check out #522, the first report. Status will be reported there!
