### ISSUE TITLE
Failing to render a gist

### ISSUE THREAD

**Issue by moorepants** [jupyter/nbviewer#527]
I've tried rendering this gist last night and today and it continues to fail:

http://nbviewer.ipython.org/gist/5eb4863f65cbe7635dc0

Output: 
Error 503 backend read error

backend read error
Guru Mediation:

Details: cache-sjc3133-SJC 1446152444 138838197

Varnish cache server

**Comment by willingc** [comment]
Hi @moorepants, I'm not sure why it wasn't working earlier. It's rendering now when I test it. Would you mind doublechecking? Thanks.

<img width="1282" alt="screen shot 2015-10-29 at 4 04 51 pm" src="https://cloud.githubusercontent.com/assets/2680980/10834513/1c6c7a72-7e57-11e5-8dea-59a07bf78886.png">

**Comment by moorepants** [comment]
Yes, it's working now. Maybe it failed once and my cache wasn't clear.

**Comment by willingc** [comment]
@moorepants Could be. Please let us know if it happens again. I hope all is well with SymPy and PyDy. I regularly tell folks about the SciPy tutorial. Very cool stuff.

**Comment by moorepants** [comment]
Thanks Carol! I hope you are doing well. I'm now a faculty member at UC Davis and we will be using SymPy and PyDy in our courses here. I'm gearing up for it now. :)
