### ISSUE TITLE
503 backend read error - Github notebooks

### ISSUE THREAD

**Issue by kramaswamyxu** [jupyter/nbviewer#528]
I am not able to access the following links through nbviewer - getting the 503 backend read error
http://nbviewer.ipython.org/github/kramaswamyxu/
http://nbviewer.ipython.org/github/kramaswamyxu/ipython-notebooks/blob/master/survival_analysis.ipynb

Is this issue related to https://github.com/jupyter/nbviewer/issues/504 or https://github.com/jupyter/nbviewer/issues/408? Not sure as the notebooks are very small - the largest being around 300kb. And the total directory size is also very small.

**Comment by willingc** [comment]
@kramaswamyxu Thank you for the issue report. I am seeing similar errors on other notebooks. I don't think it is an issue with your notebooks.

@rgbkrk @captainsafia @minrk @carreau @ellisonbg I'm seeing this behavior on two example notebooks from the site. Anyone else seeing errors?
<img width="817" alt="screen shot 2015-10-31 at 9 13 56 am" src="https://cloud.githubusercontent.com/assets/2680980/10864595/311fdaae-7fb0-11e5-9183-09add6824532.png">
<img width="940" alt="screen shot 2015-10-31 at 9 13 44 am" src="https://cloud.githubusercontent.com/assets/2680980/10864596/31228740-7fb0-11e5-9bb4-f1bd93d83917.png">

**Comment by jakirkham** [comment]
Also seeing this.

<img width="1554" alt="screen shot 2015-10-31 at 12 44 49" src="https://cloud.githubusercontent.com/assets/3019665/10864703/445532aa-7fcd-11e5-88d1-2961e5e65ad9.png">

**Comment by minrk** [comment]
I saw this for a moment, but it appears to be working okay, now. One of the nbviewer nodes appears to be suffering some performance issues, so I'm guessing it's requests routed to this one that are failing. I've taken it out of rotation, and other nodes seem to still be doing fine.

**Comment by willingc** [comment]
@minrk Thanks for the update.

@kramaswamyxu Please retest later today and let us know if you see different results. You may need to clear your browser's cache.

**Comment by kramaswamyxu** [comment]
@willingc Sure. Will test later today and let you know. Thanks.

**Comment by kramaswamyxu** [comment]
Right now, the links are working okay.

**Comment by willingc** [comment]
@kramaswamyxu Thanks for checking, and I'm glad it is working now. Would you mind closing the issue :smiley: Thanks!

**Comment by kramaswamyxu** [comment]
Sure - I'll close it!
