### ISSUE TITLE
503 backend read error

### ISSUE THREAD

**Issue by xflr6** [jupyter/nbviewer#534]
Recently, I am getting a lot of these (seem to involve a particular node):
![screen](https://cloud.githubusercontent.com/assets/6342379/11062041/c75e4d68-87ab-11e5-9cc5-a4e82561d312.png)

**Comment by douglascamata** [comment]
Me too. I'm in France and getting 503 in every notebook I try to open, even those in nbviewer's homepage.

**Comment by damontallen** [comment]
I get 503 more often than not when opening notebooks as well.  Are there
not enough servers for the service?

**Comment by minrk** [comment]
This appears to be an intermittent issue that comes up every few days or so, where some nbviewer instances seem to get stuck. I've relaunched the problematic workers.

**Comment by douglascamata** [comment]
@minrk thanks, it's working as usual now. Do you guys have any ideas nn how to detect workers are stuck and restarting them? Maybe something like a ping message.

**Comment by Carreau** [comment]
We have some detection of which node are down, and we cannot ask too much to rackspace and fastly that is already providing us with free hosting and some free manpower. 

Though if people want to try improving the [statuspage](http://status.jupyter.org/) and the infrastructure we always welcome people to the team !

**Comment by minrk** [comment]
I think I've found the problem, and I *believe* it's a tornado bug (a Future for a failing request is never resolving). 

As for monitoring - we do have health checks, but they are all passing, since it's only the notebook rendering that's falling down. We could add a notebook-rendering health check, but that's relatively expensive. Perhaps we should anyway, though.

**Comment by rgbkrk** [comment]
> We could add a notebook-rendering health check, but that's relatively expensive. Perhaps we should anyway, though.

Seems reasonable that we could be reporting the average time to render to our status endpoint.

**Comment by minrk** [comment]
That's a good idea, but wouldn't have caught this particular bug since it's actually *never* completing.
