### ISSUE TITLE
Error 503 backend read error

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbviewer#542]
I keep seeing the following error on nbviewer. It seems to be somewhat spurious, sometimes happening, sometimes not:

```
Error 503 backend read error

backend read error

Guru Mediation:

Details: cache-sjc3122-SJC 1448056718 3937529775

Varnish cache server
```

**Comment by minrk** [comment]
Some of the old nodes running a version prior to #536 were still in rotation. I took them out yesterday, so hopefully this should stop happening.
