### ISSUE TITLE
Slides mode doesn't work anymore on nbviewer

### ISSUE THREAD

**Issue by jhillairet** [jupyter/nbviewer#543]
Dear all,

Many thanks for all your work on Jupyter, notebooks and nbviewer ! They are brilliant tools !

I've discovered this few days that all my notebooks located here : 
https://github.com/jhillairet/Fusion/tree/master/Python_Crash_Course/Slides

doesn't work anymore in with slide" mode viewer of nbviewer. The notebooks seems OK in normal mode, for e.g. :
http://nbviewer.ipython.org/github/jhillairet/Fusion/blob/master/Python_Crash_Course/Slides/5-Fusion_data.ipynb

but the "slide" mode, there is only one page showing up (can't navigate into the various slides), for e.g. : 
http://nbviewer.ipython.org/format/slides/github/jhillairet/Fusion/blob/master/Python_Crash_Course/Slides/5-Fusion_data.ipynb#/

I haven't changed anything since few weeks ago. Is it normal ? 

Best regards,

Julien

**Comment by damianavila** [comment]
There are several report across multiple channels about this... I am currently investigating the issue... thanks for the report!

**Comment by bollwyvl** [comment]
Eek. Will look into this!

**Comment by bollwyvl** [comment]
Yep, missed the release of nbconvert 4.1, and the slide template wasn't up to date.

#544 will fix it once deployed.

**Comment by damianavila** [comment]
Thanks @bollwyvl

**Comment by jhillairet** [comment]
Many thanks !
