### ISSUE TITLE
NBformat version 5

### ISSUE THREAD

**Issue by kamilmowinski** [jupyter/nbviewer#545]
Hi,
i have a problem with yours nbviewer. I have a server with ipython and it have nbformat. But when i try render it i got:

[I 151126 09:19:40 handlers:40] looking for file: '/notebooks/8cddbc65-03f5-4dea-a4a9-047d0f2944c4/8cddbc65-03f5-4dea-a4a9-047d0f2944c4.ipynb'
[E 151126 09:19:40 base:532] Failed to render file from localfile: 8cddbc65-03f5-4dea-a4a9-047d0f2944c4/8cddbc65-03f5-4dea-a4a9-047d0f2944c4.ipynb
    Traceback (most recent call last):
      File "/srv/nbviewer/nbviewer/providers/base.py", line 530, in finish_notebook
        nb = reads(json_notebook, current_nbformat)
      File "/usr/local/lib/python3.4/dist-packages/IPython/nbformat/__init__.py", line 67, in reads
        nb = reader.reads(s, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/IPython/nbformat/reader.py", line 63, in reads
        raise NBFormatError('Unsupported nbformat version %s' % major)
    IPython.nbformat.NBFormatError: Unsupported nbformat version 5

**Comment by minrk** [comment]
nbformat 5 doesn't exist, so something's definitely wrong, perhaps with the notebook you are trying to render. What version of IPython do you have? For nbviewer, you should be using at least 4.0. Try: `pip install --upgrade nbconvert` to get a recent version of the tools nbviewer depends on.

**Comment by kamilmowinski** [comment]
Ok sorry its my big bad. My work mate create own new version with some features. 
Thenk you for advice :)
