### ISSUE TITLE
Getting 503 response consistently

### ISSUE THREAD

**Issue by samjewell** [jupyter/nbviewer#548]
hey guys

I love the project, thanks so much for building this.
I'm consistently getting 503 responses when I try to view notebooks - I've tried about 4 so far:

http://nbviewer.ipython.org/url/jakevdp.github.com/downloads/notebooks/XKCD_plots.ipynb
http://nbviewer.ipython.org/urls/bitbucket.org/amjoconn/watpy-learning-to-code-with-python/raw/3441274a54c7ff6ff3e37285aafcbbd8cb4774f0/notebook/Learn%20to%20Code%20with%20Python.ipynb
http://nbviewer.ipython.org/github/ipython/ipython/blob/master/examples/Notebook/Running%20Code.ipynb

That's after the message "This notebook is taking a long time to render".

Any ideas? I'm running the latest Chrome on a macbookpro- ElCapitan.

Thanks a lot!

**Comment by willingc** [comment]
@samjewell Thanks for the report. I suspect that this is not an issue with your configuration. Looking at the http://status.jupyter.org page, the load on the tmpnb (online notebook viewer) servers seems higher than normal to me. My apologies for the inconvenience. We'll take a look at it.

Ping @captainsafia @rgbkrk

**Comment by samjewell** [comment]
@willingc OMG it works - thanks so much for fixing :-D

**Comment by willingc** [comment]
@samjewell I'm glad its working for you. Credit for fixing goes to someone else on the team. Happy coding.
