### ISSUE TITLE
Error 503 backend read error

### ISSUE THREAD

**Issue by anshul6** [jupyter/nbviewer#549]
When trying to access this link:

http://nbviewer.ipython.org/github/jmportilla/Udemy-notes/blob/master/Lec%2032%20-%20Combining%20DataFrames.ipynb

I eventually get the following error message:

Error 503 backend read error

backend read error

Guru Mediation:

Details: cache-dfw1834-DFW 1449334003 2161578451

Varnish cache server

Please help resolve this issue!

**Comment by Jay-Jay-D** [comment]
Same here.

My first thought was that my notebook has some problems, but after try with many others notebooks (including the ones in the nbviewer main page); seems that problem is nbviewer itself.

**Comment by willingc** [comment]
@anshul6 @Jay-Jay-D  Thank you for the reports on the 503 errors that you are seeing. We're currently seeing an increased load on some of our tmpnb and nbviewer servers. You can monitor the current status of Project Jupyter and nbviewer at http://status.jupyter.org  cc/@captainsafia @rgbkrk

**Comment by pik** [comment]
An increased load? I can't get a single notebook link to work and this issue is 7 days old.

**Comment by willingc** [comment]
@pik You may need to clear the cache of your browser for the links to work on your system.

**Comment by minrk** [comment]
This should be resolved by the latest nbviewer deployment.

**Comment by willingc** [comment]
:+1:
