### ISSUE TITLE
http://nbviewer.ipython.org/gist/5920182

### ISSUE THREAD

**Issue by mikerushford** [jupyter/nbviewer#550]
http://nbviewer.ipython.org/gist/5920182

400 : Bad Request

We couldn't render your notebook

Perhaps it is not valid JSON, or not the right URL.

If this should be a working notebook, please let us know.

The error was: HTTP 403: Forbidden

**Comment by willingc** [comment]
@mikerushford Hmm...I just tried the link and it displayed the notebook. Perhaps clear your browser's cache and see if that resolves it for you.

As an FYI, the link you mention directs here. You may wish to try this link as well.
http://nbviewer.ipython.org/gist/rpmuller/5920182

**Comment by frankzimper** [comment]
I'm getting the same message for http://nbviewer.ipython.org/github/ipython/ipython/blob/2.x/examples/Notebook/Running%20Code.ipynb and http://nbviewer.ipython.org/github/ipython/ipython/blob/2.x/examples/Notebook/Basic%20Output.ipynb.

Possibly others too.

**Comment by willingc** [comment]
@mikerushford @frankzimper Would you mind trying again? Thanks.

**Comment by minrk** [comment]
This is the GitHub rate limit, tracking as #572
