### ISSUE TITLE
error message while opening jupyter note book

### ISSUE THREAD

**Issue by Bhanuprasanna** [jupyter/nbviewer#553]
it worked properly, but suddenly error message appeared. 
"400 : Bad Request"
"We couldn't render your notebook
Perhaps it is not valid JSON, or not the right URL.
If this should be a working notebook, please let us know.
The error was: HTTP 403: Forbidden"

so please help me regarding this. i have to get this done by the end of this week.,

**Comment by minrk** [comment]
@Bhanuprasanna what was the URL?

**Comment by damatta2k** [comment]
Same to me.

**Comment by damatta2k** [comment]
All notebooks are down.

**Comment by Bhanuprasanna** [comment]
http://nbviewer.ipython.org/github/jmportilla/Complete-Python-Bootcamp/tree/master/

**Comment by Bhanuprasanna** [comment]
is this some technical issue or my fault.??  i donno

**Comment by SGo-Go** [comment]
Same to me: 

http://nbviewer.ipython.org/urls/raw.github.com/sgo-go/gAutoy/master/docs/notebooks/gAutoy-doc-index.ipynb

**Comment by Bhanuprasanna** [comment]
now its working..,

**Comment by damatta2k** [comment]
Fine now. Thanks!

**Comment by SGo-Go** [comment]
Thanks!

**Comment by minrk** [comment]
Looks like we hit the GitHub rate limit. I'll see if I can figure out what's causing that, since traffic doesn't seem to be unusually high.

**Comment by dsblank** [comment]
Github was having some problems, so maybe it wasn't specific to the
notebook.

**Comment by willingc** [comment]
@dsblank Thanks for the feedback.

**Comment by data-panda** [comment]
@dsblank i am getting the same error now !

**Comment by Bhanuprasanna** [comment]
can some one please help me. i am facing this issue once again.

**Comment by minrk** [comment]
@Bhanuprasanna when it's the GitHub rate limit, the only solution is to wait.

**Comment by bollwyvl** [comment]
@minrk just rolled out some awesome fixes that should solve this: #572!

Let's close this one off as the "pre-572" baseline, and handle new issues as they arise.

**Comment by willingc** [comment]
@bollwyvl Nice.
