### ISSUE TITLE
Slideviewer 400 errors.

### ISSUE THREAD

**Issue by mburke05** [jupyter/nbviewer#554]
Hi guys,

I'm attempting to view some test books to see if the slideviewer app is working (I remember Damian having said it was in development but haven't kept up to date on whether it's still functional.)

I was unable to get these notebooks to render a slideshow. I'm unsure if I'm just doing it incorrectly:

https://raw.githubusercontent.com/mburke05/work_notebooks/master/test_three.ipynb
https://github.com/mburke05/work_notebooks/blob/master/slide_test.ipynb

I figured maybe it could have something to do with rendering the lightning-viz objects (though they render fine in nbviewer). Hence the test with just inline code in test_three.ipynb

Matt

**Comment by mburke05** [comment]
Doh, just read [390](https://github.com/jupyter/nbviewer/pull/390) and saw that it was added in March! Sorry guys! Looks awesome!

**Comment by willingc** [comment]
@mburke05 I'm glad that you found what you needed. Thanks for the nice compliment. The team works hard to produce awesome :smile_cat: :surfer: :sunflower:
