### ISSUE TITLE
when import matplotlib.pyplot, message:"cannot import name ls_mapper_r"

### ISSUE THREAD

**Issue by rushlinneu** [jupyter/nbviewer#555]
``` python
D:\Anaconda2\lib\site-packages\matplotlib\lines.py in <module>()
     17 from . import artist
     18 from .artist import Artist
---> 19 from .cbook import (iterable, is_string_like, is_numlike, ls_mapper_r,
     20                     pts_to_prestep, pts_to_poststep, pts_to_midstep)
     21 

ImportError: cannot import name ls_mapper_r

——————————————————————————
```

my matplotlib version is 1.5.0 and when i go to the cbook.py, I can see ls_mapper_r 

``` python
ls_mapper = dict(_linestyles)
# The ls_mapper maps short codes for line style to their full name used
# by backends
# The reverse mapper is for mapping full names to short ones
ls_mapper_r = dict([(ls[1], ls[0]) for ls in _linestyles])
```

can anybody help?

**Comment by minrk** [comment]
I suspect this is a question for @matplotlib. Can you verify that `cbook.py` is the same file you are looking at? Perhaps try reinstalling matplotlib. Since you are using conda:

    conda remove matplotlib
    conda install matplotlib

**Comment by parente** [comment]
This issue has been inactive for a few years now and seems to pertain to matplotlib rather than nbviewer. I'm going to close it out.
