### ISSUE TITLE
New html+`thebe` format

### ISSUE THREAD

**Issue by betatim** [jupyter/nbviewer#557]
The `README` suggests starting a discussion before trying to implement a new format, so here goes:

After playing with [`thebe`](https://github.com/oreillymedia/thebe) for [my blog](betatim.github.io/posts/really-interactive-posts) I thought about adding a new format to `nbviewer` that allows users to have runnable cells in addition to the current `html` format. You can do it by [replacing a few cell templates](https://github.com/betatim/notebookexec/issues/1#issuecomment-170258471)

The geek in me would find this super cool, the realist can think of all sorts of security nightmares.

Thoughts?

//cc @rgbkrk

**Comment by rgbkrk** [comment]
What prevents us from doing this currently is a lack of encapsulation on the outputs from thebe (and the notebook in general). It *is* do-able, as we've done with [transformime](https://github.com/nteract/transformime) in the past - here's an [IFramed output area written with transformime](http://codepen.io/rgbkrk/pen/EjMydO). In order to approach that, we have to rebuild the notion of the current JavaScripts, thebe included. Folks [working on the incubator dashboards](https://github.com/jupyter-incubator/dashboards) (e.g.) have been looking to build the next generation of thebe.

/cc @parente

**Comment by parente** [comment]
Security nightmare: https://github.com/jupyter-incubator/dashboards/wiki/Deployed-Dashboard-Threat-Analysis

The repo here (https://github.com/jupyter-incubator/dashboards_nodejs_app) has the start of a NodeJS app that uses jupyter-js-services to send code and widget messages to a kernel. Unlike with Thebe, the nodejs backend has the code to execute and is responsible for controlling what the browser JS can send to the kernel.

**Comment by rgbkrk** [comment]
Ah there we go! Thank you Peter!

**Comment by betatim** [comment]
If I understood the review in the wiki page this is mostly concerned with the security aspects of running the service that does the computations, "freezing"/controlling the code that gets executed, etc. tmpnb.org seems to be happy to run "untrusted" code from arbitrary users already (with some limits).

I was thinking of as a user going to nbviewer and then executing the contents of a notebook which might then steal information from my browser via JS or do other nasty stuff. Is `transformime` related to solving this problem?

**Comment by rgbkrk** [comment]
Well, transformime paints an approach to the output areas where outputs can be either be

* restricted to only mimetypes that can't run scripts (no html, no script, sanitized svg, etc.)
* IFrames everywhere

**Comment by betatim** [comment]
My original thought was nbviewer + thebe + tmpnb = :heart: and then worried about running someone's cool notebook that contained something sneaky (that ended up stealing all my bicycles via my browser).

Is there someone else who thinks this would be a useful thing to have? Totally unrealistic to make secure and useful?

IFrames everywhere sounds like a good solution to me. But then I don't really know much about securing this kind of setup (I just know you can do evil things). No html and script seems a bit limiting as the number one reason for running a notebook instead of just viewing it would be things like the widgets.

**Comment by rgbkrk** [comment]
Totally realistic and useful.

However, Thebe itself tends to be on thin ice everytime a new notebook comes out: mismatch between kernel end of widgets, thebe's bundled ipywidgets, and whatever the notebook was actually written with. That's not Thebe's problem though, that's more a Jupyter problem in breaking up the javascript and figuring out the story with the widget area, how a kernel specifies assets, etc. I'd like to group it in with the current javascript efforts in jupyter/jupyter-js-*, I just wouldn't know where to point you.

/cc @jdfreder

**Comment by parente** [comment]
@betatim said:
> If I understood the review in the wiki page this is mostly concerned with the security aspects of running the service that does the computations, "freezing"/controlling the code that gets executed, etc. 

Yes.

> tmpnb.org seems to be happy to run "untrusted" code from arbitrary users already (with some limits).

Yes. You're limited to using whatever is installed in the tmpnb image and with no external network access. Good for simple examples. Not useful for more complex dashboards (our use case).

@rgbkrk said:
> However, Thebe itself tends to be on thin ice everytime a new notebook comes out: mismatch between kernel end of widgets, thebe's bundled ipywidgets, and whatever the notebook was actually written with. 

Yes. This is another reason why we're working on that NodeJS app and using jupyter-js-services, jupyter-js-widgets, etc. instead.

**Comment by betatim** [comment]
Simple examples is what I had in mind. For complex things you'd want mybinder/everware or your solution for complex dashboards.

My conclusion for the moment is that building something on top of thebe means setting yourself up for disappointment as it will break very quickly/easily. Instead contribute to/create a thebe like tool from the things in jupyter/jupyter-js-*. Once that exists, come back and add a "don't just view [Norvig's latest notebook](https://nbviewer.ipython.org/url/norvig.com/ipython/Scrabble.ipynb) but actually run it!" mode to nbviewer.

**Comment by rgbkrk** [comment]
> Once that exists, come back and add a "don't just view Norvig's latest notebook but actually run it!" mode to nbviewer.

All aboard that :train:!

**Comment by parente** [comment]
>  Instead contribute to/create a thebe like tool from the things in jupyter/jupyter-js-*.

I think some of the code in that nodejs app is what would be needed as the basis for that tool. We didn't build another general purpose tool like Thebe because it seems like jupyter-js-* is now providing the libraries you need to fit remote kernel access and execution into whatever app context you want (e.g., nbviewer, your blog, GitHub rendering of noteboks?!). Maybe there's a higher level library abstraction that makes it easier to work with those underlying JS APIs, but IMHO it's better to have that fall out over time after some use cases exists rather than try to guess what it would be up front.

</my 2 cents>

**Comment by bollwyvl** [comment]
Hadn't seen that notebook: I'm not sure I would play PN in scrabble, and I
even used to be pretty good. People that write algorithms and books (much
less books about algorithms) are really scary opponents. Totally want to
make a widget version, though. Widgle? Probably still get sued, somehow.

I love the idea: nbviewer.*.org may yet not be the right place for the
compute to live, but we do need something more that is the go-to way to
share some ephemeral compute against library x,y,z! As we're talking about
the nbviewer-lite family, i.e. django-notebook, flask-notebook, it would be
interesting to explore what options someone who wanted an embedded
static-to-computable publishing flow might be like.

I think the binder approach (i.e. per-repo custom containers) has really
matured nicely. There has been no direct nbviewer integration, but there's
nothing stopping someone from putting the binder markdown link in their
notebook today. Mr Norvig uses his own URL to host, so he wouldn't be able
to use it natively. I'd throw one up myself, but there's no license info in
that document either... and i don't want to be infringing. gosh, that would
be a great stick to encourage people to pick licenses: no license metadata,
no nbviewer for you :(

Still would like to see req.txt/env.yml/Dockerfile be embeddable right in
the notebook, and binder be able to accept drive-by uploads... but compute
ain't free :)

**Comment by vivekkathiri** [comment]
hot
would 10/10 code again

**Comment by parente** [comment]
mybinder.org is filling the role of notebook execution as a service nicely thanks to @betatim and the mybinder team. #585 is open to track ideas for linking from nbviewer to binder. Any objections to closing this issue?

**Comment by rgbkrk** [comment]
Let's close it, I think it's outside the scope of this repo.
