### ISSUE TITLE
Notebook in Complete Python bootcamp..

### ISSUE THREAD

**Issue by beto9** [jupyter/nbviewer#559]
The 'zip' Notebook gives and error:
The error was: HTTP 403: Forbidden
I would also suggest the Notebooks are prefaced with an ordinal number depending on their appearance in the course.

**Comment by bollwyvl** [comment]
Hi! This might be a mis-filed issue... or it might not!

This repo is for the development of the nbviewer.jupyter.org website itself. If you are trying to use nbviewer to view a restricted repo, nbviewer might not be able to see it.

If, however, you are trying to reach a notebook in a public repo and can't see it, it might be of a class of problem that we occasionally see.

If you can share the link to the notebook that is erroring, that would help a great deal!

**Comment by beto9** [comment]
I went back to the same notebook a few minutes later and the issue was solved.
However I re-state my suggestion about ordering the notebooks by as they appear in the course.
Thank you!
