### ISSUE TITLE
add authentication for locally installed nbviewer 

### ISSUE THREAD

**Issue by vasimkachhi** [jupyter/nbviewer#560]
i have locally installed nbviewer on my server .but i am unable to give authentication to it.I mean is their any way i can give my locally installed nbviewer user-name and password(authentication).

Thanks in advance ,
Vasim Kachhi

**Comment by bollwyvl** [comment]
Here's the issue: the mission is to provide viewing of publicly-accessible notebooks. `http://nbviewer.*.org` will never support authorization/authentication directly. While we'd love to add social features, comments, etc. all of these distract from the service we provide: show notebooks at consistent URLs hosted somewhere publicly on the internet.

If you need local/corporate authentication, probably the best way to add "cheap" authentication would be to proxy it through another server, such as nginx or apache httpd, and have that layer handle everything over their robust LDAP support. Recall, though, that it is dangerous to host a rendered notebook on the same domain as a place where someone has credentials to, say, hit a REST endpoint and delete things. The easy answer, stripping javascript, will break user expectations far more than any loss of potential functionality that needs identity (comments, etc).

Authorization is a whole other kettle of fish. For example, you couldn't easily have the server pass along user credentials to another source of notebooks (i.e. sharepoint, confluence, etc.) so the server will only be able to see "public intranet" resources.

We have been talking about some integrations with popular python (and other?) web frameworks, which would go in separate repos. So there would be `flask-notebooks`,  and `django-notebooks`, making use of the framework's authn/authz scheme, hosted on a separate port, etc. the `jupyter/nbviewer` repo would continue to be the "global" instance, while the smaller, simpler repos. I still need to put a proposal together at the jupyter level (not here on nbviewer), but we do want to serve your needs!
