### ISSUE TITLE
better caching

### ISSUE THREAD

**Issue by minrk** [jupyter/nbviewer#564]
Traffic has increased to the point where we are hitting the GitHub API rate limit every couple of days. The main way that I see for us to deal with this is to cache our GitHub API requests more aggressively.

Right now, our caching strategy is very basic. We either cache a complete rendered result or nothing at all. We don't cache the results of any intermediate GitHub API requests.

I think there are a few things we can do to mitigate some of these things:

1. introduce caching of GitHub API request results
2. increase the baseline cache time from 10 minutes to 1 hour
3. increase cache duration when traffic is high
4. allow fallback on older cached values we wouldn't normally serve when rate limits are being hit

One alternative is to proactively aim for raw GitHub URLs when we can guess them (e.g. just for notebooks), skipping API requests in some cases, but that seems like being a bad API citizen, to me.

**Comment by bollwyvl** [comment]
Thanks so much for running this down.

API request caching is good. The errors are no fun for anybody. Also, if we're thinking about adding diff viewing (or really any other useful feature), the number of requests will go even higher.

I would say while were at it, it would be nice to also do raw fetched caching for the regular URL client as well.

I guess we're pretty much talking about caching in the `fetch` methods on the [github]
(https://github.com/jupyter/nbviewer/blob/master/nbviewer/providers/github/client.py#L57) and [url](
https://github.com/jupyter/nbviewer/blob/master/nbviewer/providers/url/client.py#L33
) clients?

It would be nice if we could get both by using something like [this](https://github.com/ByteInternet/tornado-client-cache/blob/master/tornado_client_cache.py), but perhaps as a subclass, not as a patch, and take care of it once at [app creation](https://github.com/jupyter/nbviewer/blob/master/nbviewer/app.py#L168).

**Comment by minrk** [comment]
Yeah, we should be able to pick up an existing cache implementation. Though we already have memcache hooked up, so perhaps we want to plug that in instead. The only tricky thing I see is continuing to support the semi-secret `flush_cache` flag, which forces a rerender bypassing the cache. That gets harder if we have multiple levels of caching, because we need to propagate an `ignore_cache` flag down to the fetching clients.

It would be nice if we could rely on caching and have an `If-Modified-Since`-style HEAD request to the GitHub API to reduce our load.
