### ISSUE TITLE
error with POMDPDistributions.jl

### ISSUE THREAD

**Issue by rguptatx** [jupyter/nbviewer#567]
_
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.7 (2015-03-23 21:36 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org release
|__/                   |  x86_64-linux-gnu

julia> Pkg.clone("https://github.com/sisl/MCTS.jl")
INFO: Cloning MCTS from https://github.com/sisl/MCTS.jl
INFO: Computing changes...

julia> # install the POMDPs.jl interface
       Pkg.clone("https://github.com/sisl/POMDPs.jl.git")
INFO: Cloning POMDPs from https://github.com/sisl/POMDPs.jl.git
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> # install the Value Iteration solver
       Pkg.clone("https://github.com/sisl/DiscreteValueIteration.jl")
INFO: Cloning DiscreteValueIteration from https://github.com/sisl/DiscreteValueIteration.jl
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> # install a helper module for handling distriubtions
       Pkg.clone("https://github.com/sisl/POMDPDistributions.jl")
INFO: Cloning POMDPDistributions from https://github.com/sisl/POMDPDistributions.jl
INFO: Computing changes...
ERROR: unknown package Compat required by POMDPDistributions
 in error at error.jl:21
 in requirements at ./pkg/query.jl:9
 in resolve at ./pkg/entry.jl:369
 in clone at pkg/entry.jl:159
 in clone at pkg/entry.jl:175
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in __cd#228__ at ./pkg/dir.jl:28
 in clone at pkg.jl:30

**Comment by bollwyvl** [comment]
Hi! This appears to be misfiled! You may wish to check the repo you linked to:
https://github.com/sisl/POMDPDistributions.jl
