### ISSUE TITLE
Jupyter notebook gives "400 : Bad Request"

### ISSUE THREAD

**Issue by rmjc** [jupyter/nbviewer#571]
Hello, 

The Jupyter notebook for the VIP (https://github.com/vortex-exoplanet/VIP) tutorial gives the error 400 : Bad Request:

http://nbviewer.jupyter.org/github/vortex-exoplanet/VIP/blob/master/tutorial/Tutorial_VIP.ipynb

**Comment by ResidentMario** [comment]
I am having the same issue with all of my notebooks.

[This](https://github.com/jupyter/nbviewer/issues/406) is the last time this happened AFAIK.

**Comment by minrk** [comment]
All these links look to be working okay now. Perhaps a brief rate limit?

**Comment by minrk** [comment]
Checked the logs, and this was the GitHub rate limit again. Hopefully traffic will calm down shortly. Closing since we are already tracking the rate limit issue as part of #564.

**Comment by pramitchoudhary** [comment]
Hi guys,
    Is there a size restriction on the notebooks that nbviewer can render? Some of the notebooks are not getting rendered e.g. https://github.com/datascienceinc/Skater/blob/master/examples/rule_list_notebooks/WIP_rental_listing_enquires.ipynb
Is there a workaround?
