### ISSUE TITLE
Problem rendering local notebooks using the nbviewer container

### ISSUE THREAD

**Issue by lfergar** [jupyter/nbviewer#573]
Hi! I am trying to use the nbviewer docker container to render local playbooks using --localfiles. But I keep getting this error: 

```
> [I 160216 21:58:55 handlers:55] create http://localhost:8080/localfile/simple.ipynb => /url/localhost:8080/localfile/simple.ipynb
> [I 160216 21:58:55 log:53] 302 POST /create/ (10.0.12.35) 3.01ms referer=http://icsv-ipythub02.esss.lu.se:8080/
> [I 160216 21:58:55 handlers:40] looking for file: '/tmp/simple.ipynb'
> [I 160216 21:58:55 base:531] rendering 561 B notebook from simple.ipynb
> [I 160216 21:58:55 log:53] 200 GET /localfile/simple.ipynb (::1) 36.86ms
> [E 160216 21:58:55 base:525] Failed to render file from url: http://localhost:8080/localfile/simple.ipynb
>     Traceback (most recent call last):
>       File "/srv/nbviewer/src/nbformat/nbformat/reader.py", line 14, in parse_json
>         nb_dict = json.loads(s, **kwargs)
>       File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
>         return _default_decoder.decode(s)
>       File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
>         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>       File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
>         raise ValueError(errmsg("Expecting value", s, err.value)) from None
>     ValueError: Expecting value: line 10 column 1 (char 9)
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "/srv/nbviewer/nbviewer/providers/base.py", line 523, in finish_notebook
>         nb = reads(json_notebook, current_nbformat)
>       File "/srv/nbviewer/src/nbformat/nbformat/__init__.py", line 74, in reads
>         nb = reader.reads(s, **kwargs)
>       File "/srv/nbviewer/src/nbformat/nbformat/reader.py", line 58, in reads
>         nb_dict = parse_json(s, **kwargs)
>       File "/srv/nbviewer/src/nbformat/nbformat/reader.py", line 17, in parse_json
>         raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
>     nbformat.reader.NotJSONError: Notebook does not appear to be JSON: '\n\n\n\n\n\n\n\n\n<!DOCTYPE html>\n<htm...
> [W 160216 21:58:55 web:1521] 400 GET /url/localhost%3A8080/localfile/simple.ipynb (10.0.12.35): Error reading JSON notebook
> [W 160216 21:58:55 log:53] 400 GET /url/localhost%3A8080/localfile/simple.ipynb (10.0.12.35) 60.05ms referer=http://icsv-ipythub02.esss.lu.se:8080/ user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36

```

I am completely sure that the notebook is in JSON format and not in HTML. I am using simple.ipynb from https://ipython.org/ipython-doc/2/notebook/nbconvert.html:

```
> {
>  "metadata": {
>   "name": "simple"
>  },
>  "nbformat": 3,
>  "nbformat_minor": 0,
>  "worksheets": [
>   {
>    "cells": [
>     {
>      "cell_type": "markdown",
>      "metadata": {},
>      "source": "The simplest notebook."
>     },
>     {
>      "cell_type": "code",
>      "collapsed": false,
>      "input": "print \"Hello, IPython\"",
>      "language": "python",
>      "metadata": {},
>      "outputs": [
>       {
>        "output_type": "stream",
>        "stream": "stdout",
>        "text": "Hello, IPython\n"
>       }
>      ],
>      "prompt_number": 1
>     }
>    ],
>    "metadata": {}
>   }
>  ]
> }

```

And I am running the container this way: 

> docker run -p 8080:8080 -v /mnt/nfs/public:/tmp jupyter/nbviewer python3 -m nbviewer --localfiles=/tmp --port=8080 --debug --no-cache

This is the URL in the browser: 

> http://localhost:8080/localfile/simple.ipynb

I must be doing something terribly wrong, but I can't see what. Could anyone point me in the right direction? Thanks!

**Comment by lfergar** [comment]
The same notebook is rendered properly when using a URL to Gist. 

It seems that there is a problem with the local provider in the nbviewer docker container. When using the local provider the JSON notebook is rendered properly, but then finish_notebook is called again. This time  the HTML file that was produced in the first step is passed as the JSON document. That produces the error.

**Comment by mickeydonkey** [comment]
same problem, and I'm sure a url like `file://localhost/home/usr_name/Untitled.ipynb` can lead to a local notebook. and I get the error `400 : Bad Request`The error was: Resolving timed out after 10000 milliseconds.

**Comment by minrk** [comment]
You can't use a link to `localhost`, because nbviewer's interpretation of localhost (the nbviewer service machine itself) is different from yours. Even if you are using it in a container, that might not work, because localhost in the container is not the host machine unless you use `--net=host`. If you want to get a rendering of a local file on the nbviewer machine, you would not use `localhost`, which would make a web request to a server on localhost, but `localfiles/path/to/notebook`, where the path is relative to the localfiles root when you launch the server.

**Comment by smartinsightsfromdata** [comment]
@lfergar did you manage to make this work?

I'm struggling to identify what are the steps...

**Comment by parente** [comment]
This question has been inactive for a long time. I'm going to close it out.

@minrk's last suggestion should help resolve the problem for anyone using nbviewer with local files. If you visit `/localfiles/` in your browser, you should see a navigable view of the local filesystem and can click through the available folders and notebooks.
