### ISSUE TITLE
email address does not render in notebook

### ISSUE THREAD

**Issue by paraschas** [jupyter/nbviewer#582]
I'd like to report an issue. An email address in this notebook ([link to the relevant section](http://nbviewer.jupyter.org/github/paraschas/ce400-Machine-Learning/blob/master/Using%20machine%20learning%20to%20detect%20physical%20phenomena%20in%20large%20bodies%20of%20data.ipynb#License)) does not render at all when opened with Jupyter nbviewer. It is rendering correctly with the local IPython Notebook server, and the GiHub viewer though.

![email missing in nbviewer](https://cloud.githubusercontent.com/assets/1269230/13379131/675ff368-de26-11e5-8d1e-1fa62e02e218.png)

![email ok in local ipython notebook server](https://cloud.githubusercontent.com/assets/1269230/13379133/676b3566-de26-11e5-9cd0-bd0961e8e99e.png)

![email ok in github viewer](https://cloud.githubusercontent.com/assets/1269230/13379132/67676b5c-de26-11e5-9f54-73dfef45f641.png)

I'd be happy to be of assistance to resolve this issue and thank your for this wonderful application and ecosystem.

**Comment by Carreau** [comment]
O_o, yes indeed, it is transformed to `<d.akridas@gmail.com></d.akridas@gmail.com>` .
Will investigate thanks.

**Comment by bollwyvl** [comment]
Yeah, so, I am definitely seeing this in issue in mistune (master/0.7.2/0.7.1):
```python
mistune.markdown(
    "Copyright (c) 2016 Dimitrios Paraschas <paraschas@gmail.com>, Dimitrios Akridas <d.akridas@gmail.com>")
```

```html
'<p>Copyright (c) 2016 Dimitrios Paraschas <a href="mailto:paraschas@gmail.com">paraschas@gmail.com</a>, Dimitrios Akridas &lt;d.akridas@gmail.com&gt;</p>\n'
```

but when i change the tests to having multiple email items in one line, i don't see the behavior... still looking into it...

**Comment by paraschas** [comment]
The issue now seems to be solved.
