### ISSUE TITLE
Accessing a certain page throws 500 error

### ISSUE THREAD

**Issue by sakshivaghela** [jupyter/nbviewer#583]
http://nbviewer.jupyter.org/github/jmportilla/Python-for-Algorithms--Data-Structures--and-Interviews/blob/master/Array%20Sequences/Array%20Sequences%20Interview%20Questions/Array%20Sequence%20Interview%20Questions%20-%20SOLUTIONS/Unique%20Characters%20in%20String%20-%20SOLUTION.ipynb

This link
<img width="1204" alt="screen shot 2016-03-03 at 7 39 20 pm" src="https://cloud.githubusercontent.com/assets/1557651/13514529/b6c12f04-e177-11e5-926a-2273f546105b.png">
 throws a 500 error

**Comment by minrk** [comment]
This should be fixed by #584.

**Comment by minrk** [comment]
Deployed nbviewer, and the above link appears to be working, now.
