### ISSUE TITLE
Github Enterprise 400 Bad Request

### ISSUE THREAD

**Issue by Drunkar** [jupyter/nbviewer#587]
Hi, thank you for great useful library.

When I used nbviewer docker container for Github Enterprise, I got 400 Bad Request.
It seems to be redirected to the login page.
Does anyone can run and render *.ipynb with Github Enterprise?

Thanks.

#### docker run command:

```
docker run --name nbviewer -p 8080:8080 -e 'GITHUB_API_TOKEN=<USER_NAME>:<ACCESS_TOKEN>' -e 'GITHUB_API_URL=http://<GITHUB_ENTERPRISE_URL>/api/v3/' jupyter/nbviewer
```

#### error log:

```
[E 160324 22:16:14 base:525] Failed to render file from url: http://**** (My repository URL)
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/nbformat/reader.py", line 14, in parse_json
        nb_dict = json.loads(s, **kwargs)
      File "/opt/conda/lib/python3.5/json/__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "/opt/conda/lib/python3.5/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/opt/conda/lib/python3.5/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/mine/nbviewer/nbviewer/providers/base.py", line 523, in finish_notebook
        nb = reads(json_notebook, current_nbformat)
      File "/opt/conda/lib/python3.5/site-packages/nbformat/__init__.py", line 74, in reads
        nb = reader.reads(s, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/nbformat/reader.py", line 58, in reads
        nb_dict = parse_json(s, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/nbformat/reader.py", line 17, in parse_json
        raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
    nbformat.reader.NotJSONError: Notebook does not appear to be JSON: '<!DOCTYPE html>\n<html lang="en" class=...
```

**Comment by willingc** [comment]
@bollwyvl @rgbkrk Any thoughts?

**Comment by rgbkrk** [comment]
Since I don't use nbviewer with GitHub enterprise, I'm of no use. Someone else implemented it.

One shot in the dark - I noticed the URL above is `http` rather than `https`. What's in the `Notebook does not appear to be JSON` response? I'm guessing that's very telling for how the GHE server responded.

**Comment by Drunkar** [comment]
Thanks @willingc , @rgbkrk !

Finally I solved it.
There were two problems. One is mine, and the other is in the code.

#### my mistake

I set enviroment argument as ``GITHUB_API_TOKEN=<USER_NAME>:<ACCESS_TOKEN>``, 
but github api requires only access_token.
Correct docker run command is below:

```
docker run --name nbviewer -p 8080:8080 -e 'GITHUB_API_TOKEN=<ACCESS_TOKEN>' -e 'GITHUB_API_URL=http://<GITHUB_ENTERPRISE_URL>/api/v3/' jupyter/nbviewer
```

#### code problem

Suppose that my github enterprise url is ``http://ghe.lgtm.me``.
After run a container, access nbviewer and type ipynb file path like below then push go.

```
http://ghe.lgtm.me/mine/awesome-jupyter/blob/master/awesome-lgtm.ipynb
```

It will get ``400 Bad Request`` page.
If I use ``github.com`` instead ``ghe.lgtm.me``, it worked.

The problem is, an URLHandler is called when I type my GHE url, not Github*Handler.
This is url rewrite problem.

I'm thinking about adding rewrite rules to ``nbviewer/nbviewer/providers/github/handlers.py`` using ``os.environ.get('GITHUB_API_URL')``. 
Could I make this pull request ?

**Comment by rgbkrk** [comment]
Sounds like a good PR.

**Comment by Drunkar** [comment]
Thank you for merging my PR !

**Comment by Deborah-Digges** [comment]
@Drunkar @rgbkrk Which release has this change gone in?

**Comment by rgbkrk** [comment]
We never make "proper" releases of nbviewer, mostly because we're continually shipping it. If anything, you can ref the commit at c019e1ace691561184f1fc8fe643a6c74c0faf61.

**Comment by Deborah-Digges** [comment]
Is it also part of the latest docker image?
