### ISSUE TITLE
latex align environment in markdown cell cannot be rendered correctly unless there is an empty line above it.

### ISSUE THREAD

**Issue by hzzyyy** [jupyter/nbviewer#590]
Please take a look at this link where a minimal example reproducing the problem is presented.
http://nbviewer.jupyter.org/github/hzzyyy/try/blob/master/latex%20align%20env%20bug.ipynb

**Comment by minrk** [comment]
There are several cases where an empty line is needed to render exactly right, and there are a few subtle differences like this between the markdown rendering we use in nbconvert (mistune) and the live notebook (marked).

**Comment by hzzyyy** [comment]
One way of avoiding this problem on the user side is to enclose the align environment with $$. for example:
$$
\begin{align}
\end{align}
$$

**Comment by mgeier** [comment]
@hzzyyy Note that using `$$` to enclose the environment will not work if you convert the notebook to LaTeX!

The only proper way to do it is to place the LaTeX environment in a paragraph on its own (i.e. insert empty lines to separate the environment from other text paragraphs), as @minrk said.

BTW, this also looks nicer when you edit the Markdown cell!

**Comment by parente** [comment]
@hzzyyy The first cell in the original notebook to reproduce the bug renders correctly today on nbviewer. It still doesn't work on GitHub, but we don't control that implementation.

I'm going to close this out as resolved sometime in the past 2 years.
