### ISSUE TITLE
404 from Gist ID's

### ISSUE THREAD

**Issue by moorepants** [jupyter/nbviewer#594]
I have this gist:

https://gist.github.com/moorepants/e6d784ab3fe427c2f5919414a44ef5e0

If I paste the gist id "e6d784ab3fe427c2f5919414a44ef5e0" into nbviewer I get a 404. I've also tried the full link above. The link to the raw file does work:

https://gist.githubusercontent.com/moorepants/e6d784ab3fe427c2f5919414a44ef5e0/raw/a802fcfea1af8eca3e1e614b6476d9e863f11330/plate_stiffness.ipynb

I'd like the gist ID to work so that the nbviewer link will update when I update the gist.

**Comment by rgbkrk** [comment]
Interesting, doesn't work via http://nbviewer.jupyter.org/gist/moorepants/e6d784ab3fe427c2f5919414a44ef5e0 either, whereas other gists of mine (and others) appear to be working just fine.

**Comment by rgbkrk** [comment]
Seems like nbviewer is unable to render newer gists, which have a much longer ID than previously. Example: 9022b31d77403c834a91b407c93035b3

I'm guessing this has to do with the regex for gist IDs, since old gist IDs have the same format (yet shorter).

**Comment by bollwyvl** [comment]
Yup. Was previously pegged at 20. I'll do some looking, but we probably
just need to open it up, perhaps to a slightly absurd maximum, say 256,
unless there is a compelling reason to allow .*?

**Comment by rgbkrk** [comment]
256 sounds good, that should solve it [once and for all](https://www.youtube.com/watch?v=gONcDfFrPis)

**Comment by minrk** [comment]
Fixed by #595. I'm not sure there's a point to putting a maximum length in the regex, so I just unpinned the length so it's >= 20.

**Comment by bollwyvl** [comment]
Welp, there's the old 2000ish limit for IE, but yeah, it seems fine if "an unlimited stream of hex just goes to gist".

I can think of a few cases, for other meaningful hex-ish things... a full git SHA (whatever that would mean) would be nice to have, but i don't know who would dereference that for the general case, or if it's even meaningful without a namespace. collisions happen :)

**Comment by minrk** [comment]
Working now.
