### ISSUE TITLE
Can't visit 'localhost:8080' after running in a docker

### ISSUE THREAD

**Issue by mickeydonkey** [jupyter/nbviewer#600]
Hi developers:
I'm new to docker. I run the following on debian 8.  I follow the 'quick run' instruction, after`sudo docker run -p 8080:8080 jupyter/nbviewer`,  I can't visit `http://localhost:8080` in a local browser. it shows
```
tao@localhost:~$ sudo docker run -p 80:808 jupyter/nbviewer
[I 160407 14:53:53 app:122] Not indexing notebooks
[I 160407 14:53:53 app:142] Using in-memory cache
[I 160407 14:53:53 app:288] Listening on port 8080
```
and in another terminal I can see nbviewer is running in one container but it seems no program is listening on port 8080
```
tao@localhost:~$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                           NAMES
e93ca7908f2e        jupyter/nbviewer    "python3 -m nbviewer "   31 minutes ago      Up 31 minutes       8080/tcp, 0.0.0.0:80->808/tcp   furious_perlman
tao@localhost:~$ netstat -lt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 localhost:4545          *:*                     LISTEN     
tcp        0      0 *:5900                  *:*                     LISTEN     
tcp        0      0 localhost:41263         *:*                     LISTEN     
tcp        0      0 *:sunrpc                *:*                     LISTEN     
tcp        0      0 *:ssh                   *:*                     LISTEN     
tcp        0      0 *:34007                 *:*                     LISTEN     
tcp        0      0 *:postgresql            *:*                     LISTEN     
tcp        0      0 *:smtp                  *:*                     LISTEN     
tcp6       0      0 [::]:44872              [::]:*                  LISTEN     
tcp6       0      0 [::]:5900               [::]:*                  LISTEN     
tcp6       0      0 [::]:sunrpc             [::]:*                  LISTEN     
tcp6       0      0 [::]:http               [::]:*                  LISTEN     
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN     
tcp6       0      0 [::]:postgresql         [::]:*                  LISTEN     
tcp6       0      0 [::]:smtp               [::]:*                  LISTEN     

```
Any help is appreciated

**Comment by minrk** [comment]
It looks like you are forwarding `80` to `808` (not `8080`). In this case, you would connect to `80`, not `8080`. Becaues `docker run -p 80:8080` means forwarding local port 80 to the container's port 8080.

**Comment by mickeydonkey** [comment]
Thank you  @minrk .Yes, I deliberately change the port to some number other than 8080. No matter which port I use, after `docker run -p xx:xx jupyter/nbviewer`, it always shows `Listening on port 8080`, which makes me confused. Actually I tried all ports, 80, 808 and 8080 in this case, but none of them could be connected. Any comment?

**Comment by mickeydonkey** [comment]
After switch to Ubuntu 14.04, and I can make it now. could this be some firewall issue?

**Comment by mickeydonkey** [comment]
Finally successfully visit nbviewer hosted on Debian. I've troubled myself -- the `-p` should be set as `8080:8080`, otherwise, nbviewer can't be visited.  This is not perfect for the project, Nevertheless I am happy.

**Comment by minrk** [comment]
The 'listening on 8080' is a message coming from the container. It is listening on port 8080 *inside the container*, but then docker may expose that internal port as a different port on the host. The port that is relevant to you is the docker-exported port, which may or may not be the same as the one in the container.

Glad you got it worked out. It could have been a firewall issue, but I don't know what your firewall setup was.

**Comment by soumyadeep6845** [comment]
Hi @minrk, @taoluo,
There's a [bug](https://github.com/soumyadeep6845/code-review-assistant-backend/issues/14) more or less similar to the above issue.
Any help would be welcome!
