### ISSUE TITLE
Error 503 backend read error

### ISSUE THREAD

**Issue by medellinfein** [jupyter/nbviewer#601]
When trying to access any of the notebooks in ["a gallery of interesting notebooks"](https://github.com/ipython/ipython/wiki/A-gallery-of-interesting-IPython-Notebooks#entire-books-or-other-large-collections-of-notebooks-on-a-topic), I get the following error:

> _Error 503 backend read error_
> 
> backend read error
> 
> Guru Mediation:
> 
> Details: cache-dfw1834-DFW 1449334003 2161578451
> 
> Varnish cache server

I know this issue has come up in the past. However, when I checked on the [Jupyter status page](http://status.jupyter.org/), everything is listed as being (supposedly) working normally:

Thanks.

**Comment by medellinfein** [comment]
Also, please note that this is happening even in Google Chrome incognito mode, so this is not a browser cache issue.

**Comment by Markus92** [comment]
Happening here (Netherlands) in Firefox, Edge and Chrome. Different servers too, both FRA and AMS.

**Comment by medellinfein** [comment]
Looks like it is back up. Outage is (now) noted on the status page:

>nbviewer down
>nbviewer went down. Not sure what brought it down, but it's up now. We will investigate.

**Comment by willingc** [comment]
@Markus92 and @medellinfein Thanks for submitting this; we appreciate you letting us know. Sorry for the inconvenience. Thanks again :cake:

**Comment by medellinfein** [comment]
Getting that same error (described above) again.

**Comment by willingc** [comment]
@medellinfein Thanks for letting us know. Sorry for the inconvenience. I've notified devs on issue #607 to resolve this.

**Comment by buyi1128** [comment]
so how to solve this problem? is there anyone to find a solution ?

**Comment by parente** [comment]
The 503 error typically happens when there is an issue with the operation of the hosted public instance. As nbviewer.jupyter.org seems to be healthy right now, I'm going to close this as resolved. If there's a particular action you're taking that repeatedly leads to 503 errors, please comment to let us know.
