### ISSUE TITLE
Youtube embeds don't work

### ISSUE THREAD

**Issue by habi** [jupyter/nbviewer#603]
I've tried to embed a Youtube link in a notebook I'm sharing with some collaborators in a (private) GitHub repository.
In the GitHub viewer, the video does not show up.
I've made a small example <del>and there it also doesn't show up when looking at it with the [nbviewer](http://nbviewer.jupyter.org).</del>

The example can be found [in this gist](https://gist.github.com/habi/2489079e25e58d27c381afa8ca2f34a2)<del>, but cannot </del>be loaded directly with the [nbviewer URL here](http://nbviewer.jupyter.org/gist/habi/2489079e25e58d27c381afa8ca2f34a2).

It would be really cool if Youtube embeds work.

**Comment by minrk** [comment]
@habi that isn't a notebook, it's a Python snippet with the `.ipynb` extension, which is not valid. To view a notebook on nbviewer, it must be an entire .ipynb JSON file, including the output.

**Comment by habi** [comment]
Sorry, that was the first time I've used a gist to share a notebook.
It's corrected now.

- [The GitHub online viewer](https://gist.github.com/habi/2489079e25e58d27c381afa8ca2f34a2) does *not* show the video.
- [nbviewer does show it](http://nbviewer.jupyter.org/gist/habi/2489079e25e58d27c381afa8ca2f34a2), as expected...

**Comment by minrk** [comment]
GitHub scrubs some HTML and javascript that nbviewer doesn't, so not everything can be displayed there. I'm guessing that's the issue, and there isn't really anything we can do about it.

**Comment by habi** [comment]
Ok, that makes sense.

**Comment by dudung** [comment]
And it is still not supported in 2022.
