### ISSUE TITLE
Cells rendered next to each other instead of below each other

### ISSUE THREAD

**Issue by sboeser** [jupyter/nbviewer#606]
Rendering [this](http://butler.physik.uni-mainz.de/sboeser/lectures/2016SS_CidW/Notebooks_files/Lecture_01.ipynb) Python3 notebook in `nbviewer` results in all cells being rendered next to each other (instead of below each other as expected).

Using Chrome Version 50.0.2661.86 on OSX 10.10.5.

**Comment by bollwyvl** [comment]
Oddly, I kind of love it.

Also occurs in nbconvert:
<img width="1440" alt="screen shot 2016-04-26 at 8 55 45 am" src="https://cloud.githubusercontent.com/assets/45380/14818741/aed2572a-0b8c-11e6-96cb-9b027332df10.png">

I haven't started the bisect yet to figure out which cell is the offender...

**Comment by bollwyvl** [comment]
Well, that was easy: the very first cell:
```markdown
<div id='toc'/>
```

The behavior of that is different for dynamically generated, in-browser HTML and dead-pixel HTML. Even though that works, `div`s can't actually be empty tags. Try:

```markdown
<div id='toc'></div>
```

Hooray!

**Comment by sboeser** [comment]
Great - thanks a lot!
