### ISSUE TITLE
nbviewer cuts the notebook into slices

### ISSUE THREAD

**Issue by sakluk** [jupyter/nbviewer#608]
I faced a peculiar problem when I tried to render one of my notebooks with jupyter/nbviewer. The github rendering works fine, but the [jupyter nbviewer](http://nbviewer.jupyter.org/) decided to cut the notebook into slices. The following links illustrate the situation:

In [Github all is fine:](https://github.com/sakluk/probability-and-statistics/blob/master/Lab%204.%20Towards%20Normal%20distribution.ipynb), but in [jupyter nbviewer results are chopped into pieces](http://nbviewer.jupyter.org/github/sakluk/probability-and-statistics/blob/master/Lab%204.%20Towards%20Normal%20distribution.ipynb)

Has this already been solved earlier? Is there something wrong in my Notebook?

**Comment by bollwyvl** [comment]
Yeah... there's probably some bad html in there. Look for something like:
- an explicitly closed tag that can't be used that way, i.e. <div/>
- a not closed tag that must be closed: i.e. <br>

Yep, it's your <br> at the bottom of the first markdown cell...

**Comment by sakluk** [comment]
Problem solved. It was due to nested styles. 
I commented out the first <div style > line and after that it worked nicely both in github and nbviewer. Thank you for hint. (And sorry for delayed reply). Below you can find the corrected code.

    "",
    "<div style=\"height: 300px; float: left\">\n",
    "<img src=\"https://upload.wikimedia.org/wikipedia/commons/1/1b/Abraham_de_moivre.jpg\" alt=\"Abraham de Moivre\" style=\"height:300px;\">\n",
    "</div>\n",
    "<div style=\"height: 300px; float: left\">\n",
    "<img src=\"http://blog.michaelgaio.com/wp-content/uploads/2012/09/gambling-ca-1800.jpg\" alt=\"Gambling\" style=\"height:300px;\">\n",
    "</div>\n",
    "",
