### ISSUE TITLE
Python commands not executing.

### ISSUE THREAD

**Issue by swardencinal** [jupyter/nbviewer#610]
Hello-
I'm following two tutorial trying to learn this to use with high school students:

http://opentechschool.github.io/python-data-intro/core/notebook.html
http://bebi103.caltech.edu/2015/tutorials/t0b_intro_to_jupyter_notebooks.html#What-is-Jupyter

![jupytercapture](https://cloud.githubusercontent.com/assets/16160164/15434505/01413af2-1e6c-11e6-9302-d71d09ac4f13.PNG)

When I type a Python command it is not executing.  There must be something else I need to know.

**Comment by bollwyvl** [comment]
Maybe not the right repo (try https://github.com/jupyter/help/issues for
more eyes!), but this should be pretty easy: you'll either want to:
- click the "run" button in the notebook toolbar or
- press shift+enter to run the current cell and stay there or
- press control+enter (or flower+enter on Mac) to run the current cell and
advance to the next one

There's also "run all", which will do what it says, but stop if there's an
error.

For even more goodness:
- click the keyboard toolbar button for a cheat sheet or
- press ctrl+shift+p to launch the spiffy command palette, which lets you
search all of the available commands.

Thanks for using, and even better, teaching with, jupyter! There is a
growing community of educators of all stripes using notebooks...

https://groups.google.com/forum/m/#!forum/jupyter-education

Good luck! If this answers your question, feel free to close this issue!

**Comment by minrk** [comment]
From the screenshot, the broken-link icon indicates that you don't have a connection to the kernel, which would be why you can't run any code. Can you refresh the page? Do you get any messages about failure to connect?

**Comment by parente** [comment]
This issue has been inactive for a while and so I'm going to close it.

@swardencinal please feel free to ask further your questions in the [jupyter/help issue tracker](http://github.com/jupyter/help) or the [Jupyter Google Group](https://groups.google.com/forum/#!forum/jupyter).
