### ISSUE TITLE
Images don't load in gists

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbviewer#611]
Reported by @fperez 

http://nbviewer.jupyter.org/gist/fperez/8619565ce133033fc32fa85a25ab6d3b/Light%20data%20with%20Google%20Science%20Journal.ipynb

The image links seem to not actually be correct PNG data:

http://nbviewer.jupyter.org/gist/fperez/8619565ce133033fc32fa85a25ab6d3b/sj-screenshot.png

**Comment by fperez** [comment]
For reference (in case I update the gist), this is what our render looks like (and the problem is the same on github's native rendering):

![image](https://cloud.githubusercontent.com/assets/57394/15454979/96198158-1ffb-11e6-84a2-48ebbb9b75bb.png)

And this is what it looks like in the live notebook:

![image](https://cloud.githubusercontent.com/assets/57394/15454982/afa4592c-1ffb-11e6-8b69-c3a657acedf4.png)

The [gist is here](https://gist.github.com/fperez/8619565ce133033fc32fa85a25ab6d3b).

**Comment by minrk** [comment]
The URL is right, but GitHub is giving us the PNG coerced as text (basically `pngbytes.decode('utf8', 'replace')` and not telling us about it. We fallback on GitHub raw URLs when they tell us data is truncated. We can special-case images, I suppose.

**Comment by minrk** [comment]
#612 should fix it by always getting gist image data from the raw URL.

**Comment by fperez** [comment]
It's interesting that this is different in regular repos than in gists.  Here is [the same notebook on a normal repo](https://github.com/fperez/science-journal-demo/blob/master/Light%20data%20with%20Google%20Science%20Journal.ipynb) and it renders fine.

Pinging @arfon (sorry for hitting you directly, I'm sure you'll redirect appropriately :), we can work around it on nbviewer, but it would be good if native gist rendering didn't have this problem.  No idea why gists and normal repos are different on your side, but worth mentioning the problem so perhaps you can address it.

**Comment by fperez** [comment]
Thanks @minrk!

**Comment by minrk** [comment]
Yeah, the gist API doesn't handle non-text files at all, but the GitHub API handles them fine with base64-encoding. I'm not sure why the two APIs differ.

**Comment by bayesfactor** [comment]
I'm having a similar issue. I create a notebook with images in Google colab, then save it as a GitHub gist, and sosmetimes the images don't render in the gist (though they do in colab)

**Comment by DiGyt** [comment]
> 
> 
> I'm having a similar issue. I create a notebook with images in Google colab, then save it as a GitHub gist, and sosmetimes the images don't render in the gist (though they do in colab)

Same for me (ipynb files created with Colab and saved as gists). Looks like especially large jpegs don't get rendered while smaller jpgs (from the same source and with the same additional arguments) do.
