### ISSUE TITLE
Nbviewer does not manipulate XSS problem of Markdown cell.

### ISSUE THREAD

**Issue by seanDot7** [jupyter/nbviewer#613]
If the .ipynb file contains markdown content with XSS attack, nbviewer will ignore it.

**Comment by Carreau** [comment]
Hum, can you give an example of what you see, and what you expect ?

**Comment by seanDot7** [comment]
Hi, the figure is my test python notebook. And the script in the Markdown cell will be executed by browser, however, script tags should be eliminated for security.

**Comment by Carreau** [comment]
> however, script tags should be eliminated for security.

That's true if you have sensitive information and run on authenticated context. Which is not the case for nbviewer. So a XSS would do nothing. There is no need to sanitize.

**Comment by seanDot7** [comment]
OK, got it.
Thank you.
