### ISSUE TITLE
ipython.min.css cannot be found

### ISSUE THREAD

**Issue by rs2** [jupyter/nbviewer#614]
https://github.com/jupyter/nbviewer/blob/master/nbviewer/static/less/notebook.less#L1

**Comment by minrk** [comment]
Can you provide more information? What are you trying to do when you see this?

**Comment by parente** [comment]
This issue has been inactive for a while so I'm going to close it. Using the docker image or the pip installable package (doc to be addressed in #615) yields a working nbviewer instance locally.
