### ISSUE TITLE
When I run "Image Classification and Filter Visualization" by using Google-net, I get some trouble.

### ISSUE THREAD

**Issue by Simon4john** [jupyter/nbviewer#620]
## when I use Googlenet instead of Caffenet, I get this:

#  My code:
net.blobs['data'].data[...] = transformed_image
output = net.forward()
output_prob = output['prob'][0]  # the output probability vector for the first image in the batch
print 'predicted class is:', output_prob.argmax()

#  error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-c5d1c39289dd> in <module>()
      1 # copy the image data into the memory allocated for the net
----> 2 net.blobs['data'].data[...] = transformed_image
      3 ### perform classification
      4 output = net.forward()
      5 output_prob = output['prob'][0]  # the output probability vector for the first image in the batch

ValueError: could not broadcast input array from shape (3,224,224) into shape (50,3,227,227)

## but when I comment this part code, everything is okay!
net.blobs['data'].reshape(50,        # batch size
                          3,         # 3-channel (BGR) images
                          227, 227)  # image size is 227x227

**Comment by bollwyvl** [comment]
Hi @Simon4john! This is the repo for http://nbviewer.org, a humble website that shows notebooks. You'll perhaps want to run down the repo for Googlenet! I couldn't find anything by simple googling, sorry I couldn't be of more help!
