### ISSUE TITLE
Github Enterprise: Top-right button "View on Github" links to https://github.com instead of Github Enterprise URL

### ISSUE THREAD

**Issue by juanrg** [jupyter/nbviewer#621]
Hi!

There is a little bug in the github enterprise version of the github provider. The little "View on github" button is hardcoded, so it will always link directly to github even when setting GITHUB_API_URL. For clarity, I am talking about this one:

![nbviewer_github](https://cloud.githubusercontent.com/assets/2692663/17670248/4a3b5488-6311-11e6-8fb0-37f5eadc5a97.png)

I have a solution by adding another system variable, GITHUB_URL. It could be extracted from GITHUB_API_URL, but it is probably safer to keep them separate. Can send a pull request if this solution is fine with you.

**Comment by parente** [comment]
A second env var, or parsing of the API env var, seems as good a fix as any for this issue.

**Comment by vaguiar** [comment]
@parente Wanted to check if this is still and issue? https://github.com/jupyter/nbviewer/pull/623 seems to provide a fix. 

I checked with @ivanov at the PyCon19 sprints and he suggested asking for more clarification.

**Comment by parente** [comment]
@vaguiar I missed the referenced PR when doing a bulk triage of all the nbviewer issues. I think it's safe to close until/unless someone with GitHub enterprise can say there's still an issue.

Thanks for checking. Good luck sprinting!
