### ISSUE TITLE
Support pluggable dashboard layout metadata in nbviewer

### ISSUE THREAD

**Issue by parente** [jupyter/nbviewer#626]
At PyData Carolinas, I had a couple conversations about supporting a static view of the report and grid layout info added by the dashboard extension in nbviewer. This would allow users to show/hide cells and arrange them. I imagine another view mode button could be added to nbviewer, like the one for slides, to support it.

I don't like the idea of jamming more and more native support for different views for different notebook extensions into nbviewer. I imagine we could make the `template/formats` and `providers` a bit more pluggable so that people can write their own nbviewer extensions and refer to them by paths on disk for templates and python packages/modules for providers. Sort of like what we did in kernel gateway for new modes / personalities. 

Is there any interest in this?

**Comment by rgbkrk** [comment]
Are dashboards at a state where you could make a PR to nbformat with the dashboard metadata?

**Comment by parente** [comment]
The layout metadata spec is pretty well fleshed out:

http://jupyter-dashboards-layout.readthedocs.io/en/latest/metadata.html

But is that critical? I'm not saying dashboards need to be the **one** metadata format for layout. Rather, I'd like a pluggable API in nbviewer for supporting whatever notebook viewing extensions one cares to implement.

**Comment by rgbkrk** [comment]
I'm certainly a fan of seeing them live on nbviewer. We do have the slides viewer after all.

**Comment by bollwyvl** [comment]
Yeah, that was the idea of breaking out the formatters in the first place,
whether as a light wrapper around some nbconvert settings, or something
more aggressive... as long as they can survive not getting to run any
arbitrary user code when rendering.

I think dashboard and nbpresent would both be fine candidates for expansion
in this area... though nbpresent is troublesome as it is basically a
duplication of the slides format. Indeed a single notebook could exist with
all that metadata available, which would make the format area get pretty
busy, so we may have to consider sooner other ui for picking alternate
views. We've talked about pdf in the past, which is probably still too
"expensive" to do reliably.

The harder problem would be if you wanted multiple, non-nbconvert-based
nbextensions to compose... that sounds like a ui/uri nightmare, unless it
was shifted to the notebook authoring side, where a notebook could signal
in metadata that it required some things to be available... this might be
more easily handled initially by extensions providing their own check for
being statically rendered from cdn.

**Comment by minrk** [comment]
If the layout metadata is pretty stable, I'd be happy to see support of it in nbviewer (and/or nbconvert).

**Comment by parente** [comment]
I clearly never found time to work on this idea and the jupyter/dashboards project is in maintenance mode. I think it's best to close this issue.
