### ISSUE TITLE
Can't connect to github enterprise that uses self-signed certificate

### ISSUE THREAD

**Issue by yechangyao** [jupyter/nbviewer#627]
I run github enterprise in my organization and use self-signed certificate. when I start jupyter docker container, It doesn't work and shows the following error.

```
We couldn't render your notebook

Perhaps it is not valid JSON, or not the right URL.

If this should be a working notebook, please let us know.

The error was: SSL certificate problem: self signed certificate

```

So any solutions? Thanks

**Comment by minrk** [comment]
There's probably a way to disable SSL certificate checking in the http library. Is there no way for your setup to use a trusted certificate? [letsencrypt](https://letsencrypt.org) provides free certificates for any domain.

**Comment by yechangyao** [comment]
@minrk Thanks for your advice. As you say, a trusted certificate is the best way, but we can not do that right now because of some reasons. Could you please show me how to disable ssl certificate checking in docker container?

**Comment by minrk** [comment]
I'm not 100% sure, but based on [these docs](http://www.tornadoweb.org/en/stable/httpclient.html#request-objects), I think you want to add `kwargs['validate_cert'] = False` [here](https://github.com/jupyter/nbviewer/blob/c8f1f492bff96e68dc7f619f49a815242ebd7603/nbviewer/providers/github/client.py#L53), where the request to the GitHub API is made.

**Comment by yechangyao** [comment]
I tried ```kwargs['validate_cert'] = False```, but nothing changed...

**Comment by yechangyao** [comment]
```kwargs['validate_cert'] = False```  worked.  
And ```future = self.client.fetch(url, callback, validate_cert=False, **kwargs) ``` will work too.

When I input url like https://ip/username/repo ,certificate error is showed and fails. After many trials, entering username or uasername/repo works properly for me. Thanks.
