### ISSUE TITLE
nbviewer down

### ISSUE THREAD

**Issue by doolingdavid** [jupyter/nbviewer#628]
on 15 Sep 2016 9:55 Mountain Time US, it looks like nbviewer is down. I cannot see my own notebooks/slides or anyone elses.

The error is:
Error 503 first byte timeout

first byte timeout

Guru Mediation:
Details: cache-den6024-DEN 1473954785 2285586391

Varnish cache server

**Comment by bollwyvl** [comment]
Thanks for the report. Occasionally, the internet gets sad. Looks like it's back up!
