### ISSUE TITLE
Printing Jupyter Notebooks from Jupyter running under Anaconda's Navigator

### ISSUE THREAD

**Issue by Dipugee** [jupyter/nbviewer#629]

**Comment by bollwyvl** [comment]
Hi there @Dipugee: this is the repo for the code that runs https://nbviewer.org. You may want to try your request (with some more detail!) on https://github.com/ContinuumIO/anaconda-issues/issues

Thanks!

**Comment by Dipugee** [comment]
Thanks Nicholas.

This is what I posted on the site you sent me a link to. If you, or any one else here, has any suggestions on how to share my Jupyter files with my client, who can read only pdf files, I would appreciate learning about those. Python and Jupyter are new to me and my client has no access to any of those tools either.

Thanks.

Dipu


__________________________________
Hi:

I am using Jupyter under Navigator 1.2.3 on my MacOS 10.12. I created an html output file using nbviewer and saved it on my Mac. The print preview of this html file looks ok on my screen  and  there are no line wrap arounds. However, the .pdf file wraps the lines and destroys the readability of the Notebook. I need to share this as a .pdf with a client who does not have Anaconda, Navigator or Jupyter,nor are they knowledgeable about github etc. How do I share this Notebook with them so that it looks exactly like the Jupyter notebook I see on my screen?

Here is the pdf of the html file…


_______________________________________

Thanks

Dipu


Dipankar Ganguly
Consultant: Strategy/Technology/Commercialization
Bothell, WA
Cell: 408-203-8814
email: dipugee@gmail.com
http://www.linkedin.com/in/dipugee
