### ISSUE TITLE
lets encrypt

### ISSUE THREAD

**Issue by mrgum** [jupyter/nbviewer#633]
From [http://nbviewer.jupyter.org/faq](http://nbviewer.jupyter.org/faq) 

> Can I access Notebook Viewer over https?
> 
> You can, but you will probably get a warning that the website does not have a valid certificate. We are not sure it is worth paying for an SSL certificate as the viewer should not expose any sensitive information. If you need to embed an html notebook on another site, please use local export with nbconvert.

[https://letsencrypt.org/](https://letsencrypt.org/) would let you do this without cost

**Comment by Carreau** [comment]
That's a good point. We haven't updated this page in a while. Do you want to try sending a PR that update the language on this page ?

**Comment by srinivasreddy** [comment]
@minrk  Please close this issue as the PR is merged.

**Comment by minrk** [comment]
Thanks!
