### ISSUE TITLE
Error 503 first byte timeout

### ISSUE THREAD

**Issue by JamiesHQ** [jupyter/nbviewer#634]
Receiving 503 first byte timeout error during OpenHatch Open Source hack day at GHC16:

Error 503 first byte timeout
first byte timeout
Guru Mediation:
Details: cache-atl6238-ATL 1477067527 3863992883 

@rgbkrk & @minrk - ideas? thanks!

**Comment by rgbkrk** [comment]
GitHub had an outage during the past hour that was intermittent. Is this still coming up?

**Comment by JamiesHQ** [comment]
@rgbkrk : Nope fixed! Thanks!
