### ISSUE TITLE
bokeh widgets notebook unavailable

### ISSUE THREAD

**Issue by joshgabriel** [jupyter/nbviewer#635]
http://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/tutorial/04%20-%20interactions.ipynb

is the broken link appearing with a 404 error.

**Comment by bollwyvl** [comment]
Where does this link appear?

Navigating [up one layer](http://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/tree/master/tutorial/) it appears that "interactions" is now the 3rd notebook, so:

> http://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/tutorial/03%20-%20interactions.ipynb
