### ISSUE TITLE
Does nbviewer ever execute code cells?

### ISSUE THREAD

**Issue by connercowling** [jupyter/nbviewer#637]
I would imagine the answer is no (perhaps except when you're running your own instance?) – but I'm interested in any nitty-gritty details. Thanks.

**Comment by bollwyvl** [comment]
No, the current code base does not support this... and probably never will!

If you _really_ wanted it locally, one could add a custom format that would execute cells, it would require add a new [format](https://github.com/jupyter/nbviewer/blob/master/nbviewer/formats.py)... I reckon just creating an nbconvert Exporter subclass that had the execution preprocessor would do the trick.

And, of course, we would strongly urge you not to run untrusted, user-creatable notebooks in any environment that wasn't well understood and isolated: one could imagine ripping out the process pool used in render.py and replacing it with a bunch of single-use Docker containers... but again, this is some complexity that we wouldn't take on in this codebase :)

A big gotcha about "running notebooks" is capturing all of the dependencies for the notebook in question... this is being [discussed over on nbformat](https://github.com/jupyter/nbformat/issues/49).

Hope this helps frame the issue!
