### ISSUE TITLE
notebook rendering on github does not display all equations

### ISSUE THREAD

**Issue by Fjanks** [jupyter/nbviewer#638]
I'm not sure if this is the right place to report it, but if I understood correctly github uses nbviewer to render notebooks.  
I have a notebook with a markdown cell containing three equations. In jupyter notebook all three equations are displayed, nbconvert --to pdf and --to html also works and the output using http://nbviewer.jupyter.org is also correct. However, on github only one of the three equations is displayed. 
Here is the example:
https://github.com/MPIDS/introduction_to_programming/blob/1cad5050eb02e66a66cbf158ac74521cc7615ba0/basics/basics-part1-exercises-without-solutions.ipynb

**Comment by minrk** [comment]
Thanks for the repot. Unfortunately, the only avenue for this is the GitHub support form. We don't have control over how they are calling nbconvert.

**Comment by Fjanks** [comment]
Ok, thanks for the info. I wrote to the GitHub support.
