### ISSUE TITLE
GitHub fails to display some notebooks that work via nbviewer.jupyter.org

### ISSUE THREAD

**Issue by DaneWeber** [jupyter/nbviewer#644]
nbviewer.jupyter.org works for this simple notebook:
http://nbviewer.jupyter.org/github/fluffums/MixerRepulsionMotes/blob/master/Simple%20J%20Notebook.ipynb

The in-page viewer for GitHub fails:
https://github.com/Fluffums/MixerRepulsionMotes/blob/master/Simple%20J%20Notebook.ipynb

The message I see using Chrome is "Sorry, something went wrong. Reload?"

Based on http://blog.jupyter.org/2015/05/07/rendering-notebooks-on-github/ this is place to report this issue.

**Comment by minrk** [comment]
nbviewer doesn't power the GitHub rendering, that is an internal github project. It is based on nbconvert, though, same as nbviewer. Perhaps it's something to do with the mimetype? That would be odd, but there might be an error on GitHub's side where they check something that nbviewer does not.

**Comment by DaneWeber** [comment]
Issue has been resolved.

**Comment by sansinghsanjay** [comment]
Hi DaneWeber,

Can you please explain that how you resolved this.

I am also getting error: "Sorry, something went wrong. Reload?". I am using chrome browser on Ubuntu.

Thanks & Regards

**Comment by sansinghsanjay** [comment]
Hi @DaneWeber 

I found its solution. If a github ipynb doesn't work then we can open that ipynb in https://nbviewer.jupyter.org/

I got this solution from the discussions on https://github.com/iurisegtovich/PyTherm-applied-thermodynamics/issues/11#issuecomment-323972161

**Comment by DaneWeber** [comment]
@sansinghsanjay - that's the work-around I was using when I created this issue. Would you mind sharing the link to your problematic notebook? I'd be interested in seeing if it fails for me too.

**Comment by sansinghsanjay** [comment]
@DaneWeber 

Following ipynb was not opening on my chrome + Ubuntu-16.04:
https://github.com/NikolasEnt/Vehicle-Detection-and-Tracking/blob/master/VehicheDetect.ipynb

But above ipynb worked when I opened it with https://nbviewer.jupyter.org/

**Comment by mpacer** [comment]
If this is an issue with os × browser interactions, that seems to be weirder than a question of how GitHub internally renders the notebooks. Does GH rendering work for some notebooks and not others? Do you have a minimal test case? The example you gave is a bit complicated to be able to determine the cause of the issue.

**Comment by DaneWeber** [comment]
@sansinghsanjay - you should definitely start your own issue. Perhaps also include a screenshot of what it looks like for you.

I'm able to open the GitHub example you provided in Chrome on Windows 10 and in Firefox in Ubuntu 16.04.

As an aside, if you do end up needing to determine which OS + browser is the problem, MS provides free VMs for testing in Windows:
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by rkwhatelse** [comment]
> Hi @DaneWeber
> 
> I found its solution. If a github ipynb doesn't work then we can open that ipynb in https://nbviewer.jupyter.org/
> 
> I got this solution from the discussions on [iurisegtovich/PyTherm-applied-thermodynamics#11 (comment)](https://github.com/iurisegtovich/PyTherm-applied-thermodynamics/issues/11#issuecomment-323972161)

Thank you, Sanjay
Your solution helped me for the same issue.

**Comment by yashkumaratri** [comment]
I am now facing this issue on Chrome+Ubuntu, It worked well on Chromium earlier but after chrome the notebooks have stopped.

Any idea why?
