### ISSUE TITLE
Review the service load and capacity

### ISSUE THREAD

**Issue by willingc** [jupyter/nbviewer#645]
As Jupyter has grown in popularity, usage of services such as nbviewer have seen significant growth as well. Let's look at the logs of load this year and determine if sufficient capacity exists for user demand and reliability.

Reference: https://github.com/jupyter/nbviewer/issues/607#issuecomment-263856385

cc @minrk

**Comment by minrk** [comment]
I'll have a look at the logs. I think this was an intermittent issue with the underlying carina service, causing things to slow down, or possibly some kind of slowdown that happenened in our running nbviewer instances, which had been up uninterrupted for 16 weeks.

nbviewer's been pretty stable for some time now. Our main limiting factor is GitHub API rate limit, but I don't think we've hit that in a while. We should hit that way before we actually exceed the working capacity of our current nbviewer deployment, but adding capacity under load is easy to do.

**Comment by parente** [comment]
Is it OK to close this issue? It's been inactive for quite some time, and I'm guessing (hoping?) the original problem that prompted the look-see was resolved.
