### ISSUE TITLE
nbviewer fail to render latex < in some cases

### ISSUE THREAD

**Issue by hzzyyy** [jupyter/nbviewer#647]
Hi,

I found that < is hard because it interfere with html. I've done experiments with 6 different cases and hope this can help you guys to find a solution.

How it is rendered on nbviewer:
http://nbviewer.jupyter.org/github/hzzyyy/try/blob/master/latex%20parenthesis%20bug.ipynb

How it is rendered on github:
https://github.com/hzzyyy/try/blob/master/latex%20parenthesis%20bug.ipynb

github rendered all 6 cases correctly.

If github can do it, I believe nbviewer can also do it : )

Cheers
Zhangyi

**Comment by minrk** [comment]
Thanks for the bug notebook! I've moved this over to https://github.com/jupyter/nbconvert/issues/504

**Comment by michaelpacer** [comment]
Technically, whether github counts as rendering these "correctly" depends on how strictly you want to interpret MathJax (and pandoc if we're thinking about pdf output). 

Having no spaces around < and > is [explicitly discouraged in the MathJax docs](http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents).

And for some of the examples that "work" in the notebook, in html export, and in the github viewer (and actually, for simple cases, for pdf export), these are breaking [pandoc's conventions for using `$…$`, with the `tex_math_dollars` option](http://pandoc.org/MANUAL.html#math) which state, with added emphasis:

> **The opening $ must have a non-space character immediately to its right, while the closing $ must have a non-space character immediately to its left,** and must not be followed immediately by a digit.

I'm not saying that we *shouldn't* support these, but that if we do we're flouting these explicit conventions.

**Comment by parente** [comment]
The nbviewer rendering of the provided notebooks appears correct and matches the GitHub rendering when I view it today. I believe the underlying issue was fixed in https://github.com/jupyter/nbconvert/pull/514 and so I'm going to close this issue.
