### ISSUE TITLE
slide show style improvement

### ISSUE THREAD

**Issue by hzzyyy** [jupyter/nbviewer#648]
Hi,

I found the nbviewer slide show super useful. However, it currently have two issues:

1. The font size are too small
2. The prompt are not hidden, as a result all slides have empty space on the left (contents not centered).

To address this issue, I've written the following html file:
https://github.com/hzzyyy/Presentations/blob/master/slides.html

And at the end of my sides, I add one cell:

`from IPython.core.display import HTML`
`HTML(filename='../slides.html')`

The slides can be rendered with the modification:
http://nbviewer.jupyter.org/format/slides/github/hzzyyy/Presentations/blob/master/Model%20Selection/Slides.ipynb#/

I hope my sharing can help nbviewer improve the slide rendering or at least provide the user a work around.

Cheers
Zhangyi

**Comment by damianavila** [comment]
Thanks for your input!

I agree with you that the font-size is small. And the prompt thing is a valid critic as well.
We should, in fact, make some changes on those directions in the nbcnvert package which is the thing creating the slides under the hood in nbviewer.

In fact, there are some issues opened in nbconvert repo about the enhancements needed for the slides.

Cheers.

**Comment by hzzyyy** [comment]
Thanks, I will creat the ticket at the right place.

Zhangyi

**Comment by parente** [comment]
It looks like everyone involved agreed slide improvements should be tracked in the nbconvert project and so I'm going to close this issue.
