### ISSUE TITLE
503 error when accessing Notebook Help

### ISSUE THREAD

**Issue by JamiesHQ** [jupyter/nbviewer#649]
I'm going through a demo I'm giving tomorrow and am getting a 503 error when I try to access Notebook Help from a notebook I'm running locally.

Error 503 first byte timeout
first byte timeout
Guru Mediation:
Details: cache-sjc3121-SJC 1481605825 2927712700
Varnish cache server

**Comment by cueas-rickmoore** [comment]
Getting the same error frequently.

Also getting this one:

Error 503 No healthy backends
No healthy backends
Guru Mediation:
Details: cache-iad2134-IAD 1481642433 1999735646
Varnish cache server

**Comment by medellinfein** [comment]
see issue [#607](https://github.com/jupyter/nbviewer/issues/607)

**Comment by minrk** [comment]
We've been deployed on Carina for a while, which used to work quite well. It's going through a transition right now, and has caused some disruptions in recent weeks. I've put up a new instance on a regular server, which should be more stable.

**Comment by parente** [comment]
Going to close this out as a transient operations issue resolved a year+ ago.
