### ISSUE TITLE
CSS alignment / sizing issues after widgets addition

### ISSUE THREAD

**Issue by parente** [jupyter/nbviewer#658]
After #652, the navbar and breadcrumb bars alignment and sizing are off in Chrome:

![screen shot 2016-12-31 at 2 30 11 pm](https://cloud.githubusercontent.com/assets/153745/21579000/e8666efc-cf65-11e6-9821-02726af7b8c7.png)

When I edit my /etc/hosts so that unpkg.com goes to 127.0.0.1 (to prevent the loading of the widgets embed.js script):

![screen shot 2016-12-31 at 2 31 00 pm](https://cloud.githubusercontent.com/assets/153745/21579011/1d09e300-cf66-11e6-9eaf-ccbe05d3da9d.png)

I looked at the CSS a bit and haven't noticed any styling changes on the elements in question. Maybe a page-wide box model change is taking effect?

/cc @SylvainCorlay

**Comment by SylvainCorlay** [comment]
Some css is included from the widget cdn.
