### ISSUE TITLE
Consecutive mathjax `$$` equations are ignored :-P

### ISSUE THREAD

**Issue by hughperkins** [jupyter/nbviewer#662]
The following:

```
$$
a^2
$$

$$
b^2
$$
```
... will only be rendered as the second equation, displaying as if one had written only:

```
$$
b^2
$$
```
This is a dangerous bug!  There is no warning or message given about it.  One can easily send notebooks to friends, and so on, and not notice that what they read is missing 75% of your equations :-P

A workaround is to put `nbsp;` in between the equations, but its ugly, but better than missing equations...

```
$$
a^2
$$
&nbsp;

$$
b^2
$$
```

Example of this effect: https://github.com/hughperkins/selfstudy-IBP/blob/9b9173d16542ee4846d272053c52f10dc1933f97/ibp_section3.ipynb

eg , there should be two equations between the first sentence `Latent feature values for N objects`, and the next sentence `where:`

**Comment by parente** [comment]
https://nbviewer.jupyter.org/gist/parente/263b96c181cf96ce4e0c12da1382fd3c is a notebook containing a single markdown cell with:

```
$$
a^2
$$

$$
b^2
$$
```

Both equations currently render for me on nbviewer. 

However, when I view the same notebook as a github gist (https://gist.github.com/parente/263b96c181cf96ce4e0c12da1382fd3c) I only see the second equation as reported. We do not have access to the implementation GitHub uses to render notebooks on the GitHub website (it's not nbviewer), so we're unable to fix this problem.

@hughperkins I'm going to close this out as both equations appear to render correctly on the nbviewer.jupyter.org site today.
