### ISSUE TITLE
Anaconda line numbers

### ISSUE THREAD

**Issue by scubasam9** [jupyter/nbviewer#666]
Hi, 
How do I format the workbook to enable line numbers as in the screenshot below?

![image](https://cloud.githubusercontent.com/assets/25328467/22618152/846d46d6-eacd-11e6-8997-a3e17a565b50.png)

**Comment by parente** [comment]
In your notebook editor, one way is to hit Escape to enter command mode and then press L.

nbviewer (the notebook viewer site) does not support line number display as far as I know.

**Comment by scubasam9** [comment]
perfect, thank you parente,
