### ISSUE TITLE
Working.. This notebook is taking a long time to render. Please wait, the page will load in a few seconds. 

### ISSUE THREAD

**Issue by cornhundred** [jupyter/nbviewer#677]
Notebooks are giving this message and not loading 

"Working.. This notebook is taking a long time to render. Please wait, the page will load in a few seconds." 

I noticed it for a few of my notebooks and this one linked from the homepage
[http://nbviewer.jupyter.org/github/ipython/ipython/blob/4.0.x/examples/IPython%20Kernel/Index.ipynb](http://nbviewer.jupyter.org/github/ipython/ipython/blob/4.0.x/examples/IPython%20Kernel/Index.ipynb)

It seems to have been doing this for the past few hours.

**Comment by cornhundred** [comment]
It's working again.

**Comment by minrk** [comment]
Thanks! This was caused by a bug in an update to the new relic agent. Pinning new relic to `<2.80` has fixed it.

**Comment by minrk** [comment]
newrelic has a fix, and the next release ( > 2.80.0.60) should work.

**Comment by ItafAHMADI** [comment]
Working...
This notebook is taking a long time to render.Please wait, the page will reload in a few seconds.
I ve been given this error for my notebook 
https://github.axa.com/itaf-ahmadi-stag/Trepan-based-on-Craven-s-paper/blob/master/trepan_starting_kit.ipynb
