### ISSUE TITLE
Following simple source not working

### ISSUE THREAD

**Issue by sheetal-psl** [jupyter/nbviewer#682]
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Hello world"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

**Comment by sheetal-psl** [comment]
I created a simple notebook using python3 and tried creating a gist. However, something goes wrong.

**Comment by minrk** [comment]
What goes wrong? What do you expect to happen and what happens?

**Comment by sheetal-psl** [comment]
I expect to see a heading - Hello World
Instead I get error that - something went wrong.

I do not see the notebook contents

**Comment by minrk** [comment]
Where do you see the error? Can you share an nbviewer URL that has an error?

**Comment by sheetal-psl** [comment]
Here is the URL http://nbviewer.jupyter.org/gist/sheetal-psl/b78dd39fb93cfe6dc3dd056cee2fdab5

**Comment by parente** [comment]
The file content in that gist appears to be using non-breaking space characters (\xa0) instead of regular spaces. Trying to decode it as JSON fails in Python after fetching it.

Here's a notebook showing the JSON decode error, the problematic characters, and the fact that nbformat says the notebook is valid after replacing those characters: 
https://nbviewer.jupyter.org/gist/parente/c16f4ae661d82447102a825c14911508

**Comment by parente** [comment]
@sheetal-psl I'm going to close this out since I believe fixing those space characters should resolve your problem. Feel free to comment if you're having further trouble.
