### ISSUE TITLE
I dont know what is going wrong with this ipynb file.

### ISSUE THREAD

**Issue by CallMeDek** [jupyter/nbviewer#684]
![1](https://cloud.githubusercontent.com/assets/22671339/24434524/09bb50c8-146b-11e7-9d94-4cb14b4e9c51.PNG)

There are more codes after indicating with a red box but it doesn't work! it doesn't show more behind that on https://nbviewer.jupyter.org. Could you tell me the reason and how i can solve it

Here is the URL for you
https://nbviewer.jupyter.org/github/smu405/s/blob/master/ds2_3_4_web_crawling.ipynb

**Comment by minrk** [comment]
Try putting the `<style>` tag in backticks, so that it is properly escaped:

    css selector는 html의 <style>태그 첫 '{'

e.g.

    css selector는 html의 `<style>` 태그 첫 `'{'`

The page is interpreting the `<style>` bit as an opening tag that doesn't close until the end of the page.

**Comment by CallMeDek** [comment]
Thank you for your answer. its working now.

**Comment by parente** [comment]
It looks like this issue has been resolved. If not, feel free to reopen.
