### ISSUE TITLE
Breadcrumbs, up-a-level navigation for localfiles

### ISSUE THREAD

**Issue by parente** [jupyter/nbviewer#689]
Mostly a note to self: When browsing notebooks in local mode, getting back to the directory listing requires a back button clicking (assuming the user came from a directory view) or hacking the URL to go up a level. Consider showing the breadcrumb bar and/or having a "go up one level" link.

This might also apply when browsing github repos which also have a directory listing view.

**Comment by pelson** [comment]
This works for me on master using localfile. I guess this can be closed @parente?

**Comment by parente** [comment]
Was fixed in #705.
