### ISSUE TITLE
Bugzilla attachment notebooks cannot be rendered

### ISSUE THREAD

**Issue by fbertsch** [jupyter/nbviewer#690]
We attach ipynb's to bugzilla bugs, e.g. [0]. I would expect that this URL is visible and able to be opened by nbviewer, but instead it is a 400.

[0] https://bug1348008.bmoattachments.org/attachment.cgi?id=8860059

**Comment by fbertsch** [comment]
We changed the mime type to application/json, but it still doesn't work.

**Comment by parente** [comment]
The query string (`?id=8860059`) is very likely the culprit as reported in #725.
