### ISSUE TITLE
WARNING cdn.mathjax.org end-of-life IN 5 DAYS

### ISSUE THREAD

**Issue by Naereen** [jupyter/nbviewer#693]
Apparently, the live version of [nbviewer](https://nbviewer.jupyter.org/) still uses the official MathJax CDN. It closes **in 5 days**!

See https://www.mathjax.org/cdn-shutting-down/ for more details on migrating to another service.

> Basically, a complete find-and-replace of `https://cdn.mathjax.org/mathjax/2.7-latest/` (as is used right now) to `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/` could probably be enough.

**Comment by parente** [comment]
Fixed in #685 but probably not deployed yet.

@minrk, if you'd like help doing the nbviewer updates / deployments, let me know. I'll need some guidance but am happy to take some of the burden off your shoulders.

**Comment by minrk** [comment]
It's one command to upgrade the nbviewer instances these days, so no burden. I was waiting for the DockerHub build after #685, but forgot about it by the time the build was done. Should be updated now (may take a bit for caches to flush). I'll make sure you have the keys and such to do it in the future.

**Comment by Naereen** [comment]
Hi. Thanks for the quick reply.
It seems fixed to me.

One of the drawbacks of shutting down the cdn.mathjax.org CDN is that now, the latest version is not easy to include. Instead, the version 2.7 is hard referenced here.

I don't think that's very important, but if any awesome new features (or bug fix) come in the next MathJax version, it could be useful to update the version used by nbviewer, right?
