### ISSUE TITLE
Using javascript magic is potentially dangerous from within nbviewer

### ISSUE THREAD

**Issue by mpacer** [jupyter/nbviewer#696]
If you go to this notebook from the  [IPython docs](http://nbviewer.jupyter.org/github/ipython/ipython/blob/3.x/examples/IPython%20Kernel/Rich%20Output.ipynb), you will see that it triggers two alerts. This seems inadvisable as it would be a opportunity for malicious notebooks to inject general javascript into viewers' browsers. Maybe, I'm overly worried, but it seems like we should write a preprocessor to make sure that this doesn't occur.

@rgbkrk @minrk

**Comment by rgbkrk** [comment]
We generally assume that nbviewer is an unsafe place, which is why/how Bokeh and other display themselves on the page.

**Comment by rgbkrk** [comment]
Long term view, I'd prefer all HTML and JS mimetype output to be iframed.

**Comment by kiwi0fruit** [comment]
@mpacer How bad is this for the one who views the notebook? (At the moment I'm investigating [this use case](https://github.com/jupyter/nbviewer/issues/778) for nbviewer)
