### ISSUE TITLE
Markdown rendering issue for ipython notebooks in Github but not nbviewer

### ISSUE THREAD

**Issue by redwanhuq** [jupyter/nbviewer#703]
(I wasn't certain where to raise this issue but the nbviewer blog recommended this repo.). 

**Issue**: For ipython notebooks viewed in Github (but not nbviewer), if there is any Markdown-formatted text nested between inline LaTeX _within the same paragraph block_, the Markdown formatting does not render correctly.

For example, take a look at this [ipython notebook](https://github.com/redwanhuq/machine-learning/blob/master/sms_spam_filter.ipynb). If you search for the word "subsets", you'll notice that the 1st example displays as "\<em>subsets\</em>", instead of italicized Markdown rendering. (FYI in the ipython notebook editor, I'm using the proper Markdown syntax, i.e., \*subsets*) Whereas, the same notebook in nbviewer [doesn't exhibit this issue](http://nbviewer.jupyter.org/github/redwanhuq/machine-learning/blob/master/sms_spam_filter.ipynb). 

Oddly, if the Markdown-formatted text is flanked by inline LaTeX either before or after (but not both) within the same paragraph block, then the issue doesn't appear at all in Github viewer.

**Comment by mpacer** [comment]
This is not an nbviewer issue — this has to do with GitHub's internal rendering which is generally speaking less up-to-date than nbviewer since we (specifically upstream nbconvert) control nbviewer. 

@minrk can I be added as a maintainer so I can help address issues like this?

**Comment by rgbkrk** [comment]
@mpacer - done!

**Comment by mpacer** [comment]
@rgbrk grazie!
