### ISSUE TITLE
IPython view doesn't appear ubuntu 

### ISSUE THREAD

**Issue by IdeoG** [jupyter/nbviewer#707]
Hello,
I downloaded jupyter notebook and ipython via terminal: 

pip3 install jupyter 
apt install ipython

Then i used my script with matplotlib library, i expected to see new IPython window, like this:
![image](https://user-images.githubusercontent.com/20797092/27951631-411785a4-630e-11e7-89d0-0098f3719580.png)
but i see this:
![image](https://user-images.githubusercontent.com/20797092/27951736-92f86d66-630e-11e7-8260-acd57087e2e4.png)
I tried to comment %matplotlib notebook, but nothing works.
Could you help me to get my desire view?

Best regards,
Alex.

**Comment by parente** [comment]
`%matplotlib notebook` causes matplotlib renderings to appear inline in the notebook. If you'd like the plot to appear in a separate window on your local desktop machine, try `%matplotlib qt`. If that doesn't work, other rendering backends to try on your machine are visible by running `%matplotlib --list`.
