### ISSUE TITLE
[question] jupyter nbviewer

### ISSUE THREAD

**Issue by mclpy** [jupyter/nbviewer#711]
Hello, 

I have a notebook in my bitbucket repository with the following url: https://bitbucket.org/calpe/notebooks/raw/tip/july17_phd_meeting.ipynb

I would like to open it with a jupyter nbviewer with the url: http://nbviewer.jupyter.org/urls/bitbucket.org/calpe/notebooks/raw/tip/july17_phd_meeting.ipynb

Always I get an error saying: 
400: Bad request
We couldn't render your notebook
Perhaps it is not valid JSON, or not the right URL.
If this should be a working notebook, please let us know.
The error was: Error reading JSON notebook

Do you have an idea what can cause that? 

Thanks!

**Comment by thorade** [comment]
That repository is private/hidden, so nobody except yourself can access it.
Try opening the following link while being logged out of bitbucket:
https://bitbucket.org/calpe/notebboks
it won't work, while the following works:
https://bitbucket.org/calpe/fluiddyn

https://bitbucket.org/calpe
