### ISSUE TITLE
[Feature request] nbviewer badge?

### ISSUE THREAD

**Issue by Zsailer** [jupyter/nbviewer#714]
Does nbviewer have it's own badge to include in github `README` files?

I'm imagining something like:

![nbviewer-badge](https://user-images.githubusercontent.com/2791223/29387450-e5654c72-8294-11e7-95e4-090419520edb.png)

If not, it might be worth adding. I often include badges from Binder to executable notebooks. It would be great to have a badge for static nbviewer notebooks as well.

Currently, I just use this custom made badge.

**Comment by Zsailer** [comment]
@rgbkrk Thanks! 😃

**Comment by mpacer** [comment]
Might I suggest making it an svg so that the characters render more cleanly?

**Comment by Zsailer** [comment]
Yeah, I actually made an SVG version first. The png above was just for posting here.  

Here is an example repo where I use this badge:
https://github.com/harmslab/notebooks-nonlinear-high-order-epistasis

**Comment by mpacer** [comment]
Ok not to be totally nitpicky but you probably want to use the official brand guide's colour:

![](https://img.shields.io/badge/render-nbviewer-orange.svg?colorB=f37626&colorA=4d4d4d)

which i realise is almost indistinguishable from 
![](https://img.shields.io/badge/render-nbviewer-orange.svg)

but why not be careful if we can 😄 .

**Comment by Zsailer** [comment]
Good point, @mpacer! I totally agree 👍 Thanks for pointing that out. I'll adjust the colors. 

Do y'all think a nbviewer badge (SVG) should exist in this repo? and if so, where would it live? `nbviewer/static/img`?

**Comment by parente** [comment]
@Zsailer Maybe it's better for it to go into https://github.com/jupyter/design so that the design team is aware of it and can update it along with other assets when necessary. We can give an example of how to use it in the doc here, even if it resides over there.

**Comment by Zsailer** [comment]
@parente That makes sense. I'll submit a PR over there. 

I'll point the docs to the badge once it gets accepted.

**Comment by parente** [comment]
I believe this issue was resolved some time ago and that it can be closed. @Zsailer, thanks for the work on the badge. If you'd like to submit a PR adding instructions on how to use it to the README, we can definitely get that merged.

**Comment by Zsailer** [comment]
@parente Thanks, sounds good! 

I'm headed to SciPy this week, so I'll put it on my list to add documentation for the badge.

**Comment by dsblank** [comment]
I was looking to place a nbviewer badge to open up a notebook in nbviewer. It would be great if that were available when viewing the page from nbviewer. Or if there were easy instructions to construct my own. Did I miss it?

**Comment by dsblank** [comment]
So, this turned out to be way harder than it should be because github doesn't allow clicking on badges from their rendered notebooks, and they have a few restrictions on displaying SVG images. So far, this is what I have that creates a clickable link, and displays somewhat in the right place:

![screenshot from 2019-01-03 10-15-25](https://user-images.githubusercontent.com/168568/50645025-8aa67880-0f40-11e9-9902-e6ac4c3b4487.png)

The source for that is:

```html
*This page is available as an executable or viewable **Jupyter Notebook**:* <br/>
<a href="https://mybinder.org/v2/gh/comet-ml/comet-examples/master?filepath=notebooks%2FComet-REST-API.ipynb" 
   target="_parent">
   <img align="left" 
      src="https://mybinder.org/badge_logo.svg">
</a>
<a href="https://nbviewer.jupyter.org/github/comet-ml/comet-examples/blob/master/notebooks/Comet-REST-API.ipynb" 
   target="_parent">
   <img align="right" 
      src="https://raw.githubusercontent.com/jupyter/design/master/logos/Badges/nbviewer_badge.png" 
      width="109" height="20">
</a>
```

**Comment by parente** [comment]
Yow. OK. Not sure how to improve on that when the badge is embedded in the notebook itself and viewed on GitHub. Putting the badge in a project README should be straightforward Markdown (I hope).

**Comment by tfiers** [comment]
Pure Markdown version (using the svg instead of the png for auto-scaling):

```markdown
[![nbviewer](https://raw.githubusercontent.com/jupyter/design/master/logos/Badges/nbviewer_badge.svg)](https://nbviewer.jupyter.org/...)
```

[![nbviewer](https://raw.githubusercontent.com/jupyter/design/master/logos/Badges/nbviewer_badge.svg)](https://nbviewer.jupyter.org/...)
