### ISSUE TITLE
Jupyter widgets 7.0 update

### ISSUE THREAD

**Issue by jasongrout** [jupyter/nbviewer#717]
https://github.com/jupyter/nbviewer/blob/5ac2643d687f4e78c5b8a4d50ead8255b2c65bb1/nbviewer/templates/layout.html#L160 is very specific to Jupyter widgets 6.x. It should be updated to support both widgets 6.x and 7.x (which would require checking the metadata and determining which version, and then either using that embed url or using the new embed URL (see http://ipywidgets.readthedocs.io/en/stable/migration_guides.html?highlight=migrate#updating-embedded-widgets)

**Comment by labarba** [comment]
I would love to see this fix! It will make my new lesson shine on nbviewer:
http://go.gwu.edu/engcomp2lesson4

Commenting here to get a notification with updates!

**Comment by cornhundred** [comment]
You can still get widgets to display on nbviewer if you save them using ipywidgets/jupyter-widgets version 6.0, see [example](http://nbviewer.jupyter.org/github/MaayanLab/clustergrammer-widget/blob/master/Running_clustergrammer_widget.ipynb)
