### ISSUE TITLE
[question/request] nbviewer release

### ISSUE THREAD

**Issue by shyam334** [jupyter/nbviewer#720]
I see that you guys were working on publishing nbviewer to pypi. ( #709 #704 )
But I can't seem to find the package in pypi yet. (Am I not looking in the right places)
If not released, Can I request a release.
Thanks.

**Comment by parente** [comment]
@minrk I've had good success using [versioneer](https://github.com/warner/python-versioneer) in other projects. Any concerns if I add it here? It removes the need to manually bump versions in setup.py and bases versions on git tags.

**Comment by minrk** [comment]
@parente nope, go for it

**Comment by parente** [comment]
Cool. I’ll get to it this weekend and push a release to pypi

**Comment by parente** [comment]
Small snafu when pushing the 1.0.0 to pypi so I pushed a 1.0.1 immediately following it. I'll add a section to the README with the steps to follow to cut new releases soon.
