### ISSUE TITLE
Why is the notebook CSS not the latest 5.x

### ISSUE THREAD

**Issue by oscar6echo** [jupyter/nbviewer#721]
This is more a nbconvert issue [#679](https://github.com/jupyter/nbconvert/issues/679) but can not be corrected only in the case of nbviewer, as it is a community service.

**Comment by parente** [comment]
nbviewer was updated to use 5.1.0 of the notebook assets. Now that 5.2 is out, we'll need to do the same.

@gnestor I think you have a nice checklist for notebook releases now that you create in the notebook repo. Mind adding a note to "update nbviewer use of notebook assets" to it? Feel free to tag me on it during releases. (I'm not looking to add more work to your plate.)

**Comment by gnestor** [comment]
Sure thing! I just added to the checklist and created a PR with "Allow maintainers to edit" checked, so you make changes if need be: https://github.com/jupyter/nbviewer/pull/732

**Comment by parente** [comment]
The notebook assets need to be updated again to 5.5.0. PR #779 should address it.

I'm going to close this issue since the update process will be recurring any time a new notebook release is made. We'll either have to remember to do it or handle it when someone reminds us.
