### ISSUE TITLE
kernel connection problem 

### ISSUE THREAD

**Issue by didiji** [jupyter/nbviewer#722]
Hi,
I'm experiencing ongoing kernel connection problems.
With no apparent reason I'm getting either 'kernel busy' or 'no kernel connection' issues. 
Any suggestions of how to solve this?
Thank you !

**Comment by sanderspanjaard** [comment]
Hi, 
I experience comparable issue, the message is 'Not connected'. Indeed how to solve this?

Thanks!

**Comment by parente** [comment]
@didiji @sanderspanjaard You might want to try posting your questions on the Jupyter Google Group. This issue tracker is for the nbviewer component which offers read-only viewing of notebook documents. It sounds like you're having trouble with Jupyter Notebook or JupyterLab, the interactive notebook authoring environments.

https://groups.google.com/forum/#!forum/jupyter
