### ISSUE TITLE
Algorithms in TensorFlow

### ISSUE THREAD

**Issue by divya1md** [jupyter/nbviewer#723]
I want to know about algorithms in Tensorflow using Python.
By using algorithms like K-nn, Apriori, NavieBayes, Random Forest I wanna process a dataset using TensorFlow and find accuracy rate for each algorithm and plot the graph using ggplot2.

Please respond as soon as possible
Thank you.

**Comment by parente** [comment]
Hi @divya1md. This issue tracker is for the Jupyter Notebook viewer project hosted at https://nbviewer.jupyter.org. You might want to try posting your question on the Tensorflow mailing list or Stackoverflow. Cheers!
