### ISSUE TITLE
Make widgets URL configurable

### ISSUE THREAD

**Issue by jasongrout** [jupyter/nbviewer#739]
See https://github.com/jupyter/nbviewer/pull/738#issuecomment-343522415

We'd like to make the widgets 6 and widgets 7 URLs configurable. It probably makes most sense to just search the codebase for `mathjax_url` and do something similar for the widgets URLs.

**Comment by bollwyvl** [comment]
Extending on this, while I ❤️ widgets, we should have an approach for configuring and displaying more (versions of) mime renderers, as well as tests for these things actually working.

Thinking about the prototypical PR, the simplest case would patch a single file that handles:
- known mimetype discovery
- (optional) sub-mimetype discovery (if the mimetype isn't itself versioned)
  - e.g. "parse this JSON, look for json pointer" or, perhaps "search for this regex"
- URL for the renderer
  - ideally, these would all be sourced from one place, i.e. unpkg/jsdelivr, and be like `{'pac}`
- [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) hash
- where to report that it is broken (_not_ an nbviewer issue)
- a notebook we can use to test whether it works
  - presumably also a css selector for a working render

The initial stable would be, presumably, 
- everything shipped by default in [JupyterLab](https://github.com/jupyterlab/jupyterlab/blob/1b7756c7dcda710ed673dadd11f18c1f7794ee0c/jupyterlab/package.app.json#L110), 
- [jupyter-renderers](https://github.com/jupyterlab/jupyter-renderers/issues/3)
- "second party" stuff that would strenuously the test dependency chain (i.e. bqplot)

**Comment by jasongrout** [comment]
@bollwyvl - I love how you think big. Can you open a new issue (if one hasn't been opened already) with your expanded idea?

**Comment by jasongrout** [comment]
This issue (making ipywidgets url configurable) was fixed by #738.
