### ISSUE TITLE
PR 728 broke our nbviewer

### ISSUE THREAD

**Issue by MarkusTeufelberger** [jupyter/nbviewer#743]
In #728 a new check if "other" has read rights on files was introduced as well as replacing abspath with realpath.

Both changes are breaking our nbviewer deployment. What is the reasoning behind these decisions and if they are desirable for whatever reason, what can be done about this (e.g. submit a "rawfile" handler that exhibits the previous functionality)?

**Comment by minrk** [comment]
I don't think the permission changes should have been made. Feel free to open a PR that changes the access check to the owner process and puts the 'world-readable-only' behind an option.

**Comment by parente** [comment]
/cc @pelson

From the original PR:

> To explain my usecase further: I'm running nbviewer under its own dedicated user, and don't want any back-doors to allow people to list/cat files that aren't visible to everybody anyway. Doing so means I no longer need to worry about somebody getting hold of things like ssh keys etc., and prevents filesystem permissions user-hopping. I would argue that this change in behaviour is a much safer default.

**Comment by MarkusTeufelberger** [comment]
I have no problem in making this configurable or even the default behavior. Currently is is simply removed functionality though.

**Comment by MarkusTeufelberger** [comment]
Ok, I would need the following 2 changes:

* abspath instead of realpath to support symlinks
* less stringent checks in can_show (e.g. about "other" read access)

As far as I've seen, nbviewer is configured almost exclusively via command line parameters - is there some general guideline on naming or should I just invent something, probably prefixed with `localfile_`?

Suggested config setting names: `localfile_abspath` (will use abspath instead of realpath) and `localfile_only_world_readable` (changing the default to the previous state but if this is set, then the check for world readable is enforced).

Is this an acceptable way of going forward? If yes, I'll start working on the code for that...

**Comment by MarkusTeufelberger** [comment]
PRs created, I hope that was everything. Feedback is of course welcome. :-)

**Comment by pelson** [comment]
Thanks for pinging me on this @parente, and apologies for the pain @MarkusTeufelberger. Great work on the PRs.

Out of interest, is there anything preventing your users visiting ``~/.ssh/id_rsa`` via a symlink? I guess you have isolated your machine so that you don't really mind what they visit.

Given the PRs have been merged, I think this issue can now be closed. Agree @MarkusTeufelberger?

**Comment by MarkusTeufelberger** [comment]
> Out of interest, is there anything preventing your users visiting ~/.ssh/id_rsa via a symlink?

Docker. Which also protects from having accidentally too permissive settings on this file for example.

> Agree @MarkusTeufelberger?

Yes, if there still are some issues, I'll just open a new issue or PR.
