### ISSUE TITLE
Scrolling in windows

### ISSUE THREAD

**Issue by jonathanrobie** [jupyter/nbviewer#750]
I am checking in notebooks that show output scrolling in windows.  On GitHub and in nbviewer, the scrollable windows are lost.

For example, this has scrollable windows in Jupyter, but not in nbviewer.

https://github.com/biblicalhumanities/greek-new-testament/blob/master/labnotes/dative-direct-objects.ipynb

http://nbviewer.jupyter.org/github/biblicalhumanities/greek-new-testament/blob/master/labnotes/dative-direct-objects.ipynb

I can fix this by converting to HTML and modifying the CSS for div.output_area, but I would love it if this would Just Work.  Any suggestions?

**Comment by parente** [comment]
I suspect the HTML emitted by nbconvert doesn't provide an indication of the [`scrolled` attribute value in the notebook file format](https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.schema.json#L212) and so there's not a way to style those outputs accordingly on nbviewer. (There's only [one mention of the attribute in the nbconvert code base](https://github.com/jupyter/nbconvert/search?q=scrolled&unscoped_q=scrolled) and it's in the code to strip metadata.)

I can see benefits to matching the nbviewer rendering as closely as possible to what an author sees in the notebook editing environment. I can also see people used to the current behavior being surprised if it changes suddenly. At any rate, I think the change would need to be proposed and discussed in the nbconvert repo to affect nbviewer. GitHub's implementation is private and may or may not be impacted by changes in nbviewer.

The only workaround I can think of in the meantime is to include a cell in your notebook like:

```
%%html
<style>
.nbviewer div.output_area {
  overflow-y: auto;
  max-height: 500px; /* or value of your choosing */
}
</style>
```

to make all outputs past a certain length scrollable.

**Comment by krinsman** [comment]
@jonathanrobie Were you able to open an issue with NBConvert 
https://github.com/jupyter/nbconvert
to address this issue?

I am tentatively closing this issue as resolved (at least on the side of NBViewer). Please let me know whether it should be reopened.
