### ISSUE TITLE
Sets not callable

### ISSUE THREAD

**Issue by dtbhatt** [jupyter/nbviewer#751]
Maybe I'm missing a syntax or maybe i need to install an application but for the SET exercise, each time I run the code to verify it is converting, creating, or unionising the sets, the output shows "Set not callable"

convert the following list to a set ['rap','house','electronic music','rap']¶
In [30]:

newSet
newSet = set(['rap','house','electronic music','rap'])
​
newSet
​
​
​
​
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-aae6a0c45970> in <module>()
----> 1 newSet = set(['rap','house','electronic music','rap'])
      2 
      3 newSet
      4 
      5 

TypeError: 'set' object is not callable

**Comment by bollwyvl** [comment]
This looks unrelated to `nbviewer`!

You may have set [autocall](https://ipython.org/ipython-doc/3/api/generated/IPython.core.autocall.html) somehow...
