### ISSUE TITLE
Notebook validation failed

### ISSUE THREAD

**Issue by FENGSHAN95** [jupyter/nbviewer#752]
It always gives me this error msg (below) when there is a jupyter widget in the code.
However, the progress bar always doesn't work, with only 'A Jupyter Widget' showing below the code.

Notebook Validation failed: {'version_major': 2, 'version_minor': 0, 'model_id': 'cb0d5407d8bf4818ab290a3d27430195'} is not valid under any of the given schemas:
{
 "version_major": 2,
 "version_minor": 0,
 "model_id": "cb0d5407d8bf4818ab290a3d27430195"
}

**Comment by bollwyvl** [comment]
If you can provide a link to an example notebook, that would help a lot!

**Comment by parente** [comment]
This issue has been inactive for some time and so I'm going to close it. 

@FENGSHAN95 if you're able to provide a link to a problematic notebook, feel free to comment here and we can try to help you out.
