### ISSUE TITLE
Suggestion: add a button to edit a copy of the notebook using try.jupyter.org

### ISSUE THREAD

**Issue by pjmtavares** [jupyter/nbviewer#754]
This would be a great way to make it zero-effort for newcomers to try out Jupyter.

**Comment by bollwyvl** [comment]
Thanks for the suggestion... tmpnb is not currently supported! For things backed by GitHub, we have considered a "view on [binder](https://mybinder.org)" button (#585), which is probably about the only way we'd do this. 

For everything else... the potential for abuse is a bit high.
