### ISSUE TITLE
Unable to download form nbviewer

### ISSUE THREAD

**Issue by meltaylor78** [jupyter/nbviewer#756]
Hi,
I have an issue when I try to download the Jupyter books. When I click the download button in the top right it just opens up a page of code (of the given book) but does not initiate a download
![screen grab](https://user-images.githubusercontent.com/16169674/34963001-287e3b9c-fa3e-11e7-85c4-3e2ea772fd00.jpg)
. 

Has anyone seen this issue? 
I used Firefox (also tried Internet Explore)

**Comment by bollwyvl** [comment]
Can't tell where that notebook came from, but we basically redirect to the raw source. If they are hosting it with a "readable" mime type, it will just display.

Try using the right mouse button and "Save Link As..."... or when you get to the page, press Ctrl+S, or use the File->Save menu to save it locally!

Thanks for using nbviewer!
