### ISSUE TITLE
Error 503 No healthy backends

### ISSUE THREAD

**Issue by igorrates** [jupyter/nbviewer#758]
Hi guys,

Any idea why it's not possible to access https://nbviewer.jupyter.org/

Error 503 No healthy backends
No healthy backends

Guru Mediation:
Details: cache-bos8234-BOS 1516977539 2493363251

Varnish cache server

**Comment by snotskie** [comment]
I had the same issue (#759). It appears to be working now

**Comment by Afreen04** [comment]
@willingc this seems to be resolved. Can it be closed? 
Also, Issue #759 is a duplication.

**Comment by igorrates** [comment]
Yeah. It's working. Thank you. Issue closed

**Comment by SimonBiggs** [comment]
Sorry to post on an old issue, but this appears to be occurring again.

Cheers,
Simon

**Comment by krinsman** [comment]
@SimonBiggs See https://github.com/jupyter/nbviewer/issues/857
