### ISSUE TITLE
How to add custom domain to the nbviewer rendered url?

### ISSUE THREAD

**Issue by Srinivasb0** [jupyter/nbviewer#769]
How I can run the nbviewer in my servers and return URL should contain public IP/domain name.

For example:
https://nbviewer.jupyter.org/github/Srinivasb0/Data_Science_tutorial/blob/master/Job_Analysis_for_DataScientist.ipynb

To:
https://xyz.com/github/Srinivasb0/Data_Science_tutorial/blob/master/Job_Analysis_for_DataScientist.ipynb

If it is possible, please help me with the procedure to solve this

**Comment by Srinivasb0** [comment]
Hi @parente I stopped working on this, due to other reasons. So I don't have much info about this

**Comment by parente** [comment]
No problem. I'm going to close this out then. Feel free to ask again if you resume working on it.
