### ISSUE TITLE
No module name calysto_kernel

### ISSUE THREAD

**Issue by devhot** [jupyter/nbviewer#782]
Hi 
I m tying to install  Calysto Scheme, but when I send command "python3 -m calysto_kernel install --user" ,the errro pop saying "No module name calysto_kernel" .

Anyone could tell me how to fix it?

**Comment by dsblank** [comment]
You should be asking this question over here: https://github.com/Calysto/calysto_scheme/issues

And before that, you should read the installation instructions here: https://github.com/Calysto/calysto_scheme#calysto-scheme as it seems you missed a step.

**Comment by parente** [comment]
I'm going to close this as it's not related to nbviewer.
