### ISSUE TITLE
Error 400 on ipython homepage

### ISSUE THREAD

**Issue by Larrylogoh** [jupyter/nbviewer#787]
**Describe the bug**
The link to the official example collection does not work

**To Reproduce**
1. Go to 'ipython.org'
2. Click on 'official example collection'
3. See error

**Expected behavior**
Expected to see the official example collection

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : firefox
 - Version : 61

**Comment by parente** [comment]
Thanks @Larrylogoh. I submitted PR to ipython/ipython to fix the broken notebook. In the meantime, http://nbviewer.jupyter.org/github/ipython/ipython/tree/master/examples/ is the folder containing the examples on nbviewer.
