### ISSUE TITLE
udacity/boston housing pricing projects

### ISSUE THREAD

**Issue by nandi1609** [jupyter/nbviewer#791]
/opt/conda/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

**Comment by parente** [comment]
Hi @nandi1609. If you have a question about the scitkit-learn project and these deprecation warnings, you'll probably want to ask it using one of the [scikit-learn mailing list](http://scikit-learn.org/stable/support.html). This is the issue tracker for nbviewer which lets you view Jupyter Notebooks people share online.
