### ISSUE TITLE
Nbviewer

### ISSUE THREAD

**Issue by mitch103** [jupyter/nbviewer#795]
Hi! Thanks for using Jupyter Notebook Viewer (nbviewer) and taking the time to report a bug you've encountered. Please use the template below to tell us about the problem.

If you've found a bug in a different Jupyter project (e.g., [Jupyter Notebook](http://github.com/jupyter/notebook), [JupyterLab](http://github.com/jupyterlab/jupyterlab), [JupyterHub](http://github.com/jupyterhub/jupyterhub), etc.), please open an issue using that project's issue tracker instead.

If you need help using or installing Jupyter Notebook Viewer, please use the [jupyter/help](https://github.com/jupyter/help) issue tracker instead.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Everytime I try to convert my ipynb file to a nbviewer it gives me a 400 error

**Comment by parente** [comment]
HI @mitch103 . Please provide the information requested in the issue template, especially a link to a notebook that demonstrates the problem you're facing, and we might be able to help debug your issue.

**Comment by parente** [comment]
Closing this out as inactive. Need a link to the notebook to help debug.
