### ISSUE TITLE
API GET requests are refused due to Content Secirity Policy directive connect-src

### ISSUE THREAD

**Issue by cornhundred** [jupyter/nbviewer#797]
**Describe the bug**
My widget (https://github.com/maayanlab/clustergrammer-widget) makes GET requests to two web applications to obtain biological information about a user's dataset (see https://clustergrammer.readthedocs.io/biology_specific_features.html#mouseover-gene-name-and-description). As of a few weeks ago I noticed that GET requests are no longer working for NBViewer rendered notebooks. I'm getting an error: `Refused to connect to <API endpoint> because it violates the following Content Security Policy directive: "connect-src" 'none'".`.

**To Reproduce**
1. Go to http://nbviewer.jupyter.org/github/MaayanLab/clustergrammer-widget/blob/master/Running_clustergrammer_widget.ipynb
2. Open the developer console and mouse over a row name (e.g. ROS1) in the first heatmap. The same error can be found by clicking the red DNA icon and clicking a library (red circle). 
3. See error in the console about Content Security Policy

**Expected behavior**
Normally the Javascript library (clustergrammer_widget) receives data from an API (https://github.com/MaayanLab/clustergrammer-widget/blob/master/js/src/example.js#L256 or https://github.com/MaayanLab/clustergrammer-widget/blob/master/js/src/example.js#L296) and shows a gene name/description or shows enrichment analysis results, respectively. These GET requests are working normally in static HTML Jupyter notebook files with embedded widgets (you can download this file https://github.com/MaayanLab/clustergrammer-widget/blob/master/Running_clustergrammer_widget.html to verify).

**Screenshots**
The screenshot shows the desired behavior when mousing over a row name
<img width="615" alt="screen shot 2018-09-27 at 10 18 26 am" src="https://user-images.githubusercontent.com/8352840/46152284-b548ad00-c23e-11e8-82f0-85b642a965a0.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, Safari, Mozilla
 - Version

**Additional context**

**Comment by cornhundred** [comment]
I'm not sure about the security issues but it has been very useful for my widget to be able to make GET requests to get gene names/descriptions and POST requests to perform enrichment analysis on sets of genes. It would be great if we could get this working on NBViewer again.

Also, the API endpoints I'm using are `HTTPS` - I'm not sure if that helps.

**Comment by cornhundred** [comment]
By the way that turned out to be fortunate timing with that change, here is my [JupyterCon talk](https://www.youtube.com/watch?v=82epZkmfkrE&feature=youtu.be&t=20m10s) demonstrating the cross origin request enrichment analysis on NBViewer on 8-23-2018 :)

**Comment by parente** [comment]
@cornhundred I've redeployed the public nbviewer with `--content_security_policy=connect-src *` to return it to the original behavior. The mouseover popups on the clustergrammar widget show descriptions again without error.

**Comment by cornhundred** [comment]
Thanks @parente I appreciate the change!

**Comment by alshan** [comment]
@parente It seems that `connect-src 'none'` is back lately at the public nbviewer: https://github.com/jupyter/nbviewer/issues/964

Could you comment please? it's really frustrating.

**Comment by parente** [comment]
Updated in https://github.com/jupyter/nbviewer/issues/964#issuecomment-723452085
