### ISSUE TITLE
python: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xct24** [jupyter/nbviewer#800]
Tried to do a quick run of nbviewer but got this error. 
Can't find any solution after some preliminary research. 
My local python version is 3.6.5

Thank you!

**Comment by parente** [comment]
@xct24 Are you using the provided docker image? Pip installing and running nbviewer that way?

**Comment by xct24** [comment]
> @xct24 Are you using the provided docker image? Pip installing and running nbviewer that way?

What I did was only 
```shell
$ docker pull jupyter/nbviewer
$ docker run -p 8080:8080 jupyter/nbviewer
```
as instructed by the readme.md

**Comment by xct24** [comment]
I decided to not use the official docker image but built one myself, and it worked properly.
