### ISSUE TITLE
Color Brewer notebook bad request

### ISSUE THREAD

**Issue by margaridaCF** [jupyter/nbviewer#803]
**Describe the bug**
I followed the link on https://moderndata.plot.ly/color-scales-in-ipython-notebook/ and I get a 400: Bad Request

**To Reproduce**
1. Go to ' https://moderndata.plot.ly/color-scales-in-ipython-notebook/'
2. Click on 'See this IPython notebook for full usage.'
3. Error
400 : Bad Request
We couldn't render your notebook
Perhaps it is not valid JSON, or not the right URL.
If this should be a working notebook, please let us know.
The error was: Error reading JSON notebook

**Expected behavior**
I was expecting a functioning notebook.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser [Firefox]
 - Version [62.0 64-bits]

**Comment by parente** [comment]
@margaridaCF  It looks like that notebook gist is corrupted. Here's the raw view:

https://gist.githubusercontent.com/jackparmer/4696226c9b6b931bbdf6/raw/7582189b0fd08a24ec21458f878d2d9cf32e0534/colorlover.ipynb

Scroll to the bottom and see if you see what I see: the JSON is truncated incorrectly.

I've left a comment on the gist to notify the author of the problem.
