### ISSUE TITLE
Will the page be automatically deleted?

### ISSUE THREAD

**Issue by yueruchen** [jupyter/nbviewer#804]
Hi, thanks for providing a useful tool.

I am using nbviewer to show my CV in the internet. But I want to delete it now. After I delete my CV in the github repo the URL of nbviewer can still be accessd. But I see in the FAQ that nbviewer does not store the file. How did it happen?

**Comment by parente** [comment]
@yueruchen nbviewer caches notebooks it renders for some amount of time: https://github.com/jupyter/nbviewer/issues/295. Try visiting the URL with `?flush_cache=true` on the end.

**Comment by krinsman** [comment]
@yueruchen Did the above answer help you with your question? I am tentatively closing this issue as resolved. Please let me know whether it should be reopened.
