### ISSUE TITLE
Underscore in variable name not displayed in last line of cell

### ISSUE THREAD

**Issue by sdruskat** [jupyter/nbviewer#817]
**Describe the bug**
I have come across an example of a rendered Python cell where the underscore in the variable name in the last line of the cell is not displayed.

Copying and pasting the cell contents into a text editor (Sublime Text 3), the underscore is there and displayed correctly.

**To Reproduce**
1. Go to <https://nbviewer.jupyter.org/github/sdruskat/hexatomic.github.io/blob/src/src/static/ipynb/Hexatomic%20Project%20-%20Documentation%20Tooling%20Evaluation.ipynb>
3. Scroll down to `In [12]:`

**Expected behavior**
The last line of the cell should be displayed as
```
scored_avg
```

**Screenshots**

![grafik](https://user-images.githubusercontent.com/3007126/52787713-f7905080-305e-11e9-8909-5b75a0d8a996.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Browser: Firefox
 - Version: 65.0

**Comment by parente** [comment]
After the latest deploy which pulled in the stylesheets from notebook 5.7.8, the underscore in the last cell seems to be rendering OK for me on Firefox 66.0. Can you confirm @sdruskat and close if the issue is fixed for you?

**Comment by sdruskat** [comment]
Confirmed fixed. Thanks.
