### ISSUE TITLE
nbviewer.jupyter.org: External images are not updated

### ISSUE THREAD

**Issue by jhermann** [jupyter/nbviewer#820]
If you have links to externalized images in a notebook (but located in the same git repo), when those images change, they are not updated by https://nbviewer.jupyter.org/, even when adding `?flush_cache=true`.

**To Reproduce**
Compare these 2 URLs:

* https://nbviewer.jupyter.org/github/jhermann/jupyter-by-example/blob/master/how-tos/cleanup.ipynb
* https://github.com/jhermann/jupyter-by-example/blob/master/how-tos/cleanup.ipynb

Note the different images – at least at the time of this writing, and yes, also with flushed caches and after Shift-Ctrl-R.

**Expected behavior**
Update the git clone, *at least* when explicit cache flushing is requested.

**Comment by parente** [comment]
nbviewer uses the GitHub REST API to fetch files (e.g., https://github.com/jupyter/nbviewer/blob/master/nbviewer/providers/github/client.py#L116). I'm not aware of any other explicit caching happening in the code other than the one you mentioned which is overridden by `flush_cache` and the caching done by your browser.

**Comment by jhermann** [comment]
Hmmm, in the end, the new image *did* show up – maybe something on GitHub's side.

Anyway, closing, if someone else stumbles over this, there might be more diagnostic input…
