### ISSUE TITLE
Fix compatibility with tornado 6

### ISSUE THREAD

**Issue by parente** [jupyter/nbviewer#822]
`gen.Task` no longer exists. I tried quickly porting the logic wholesale into nbviewer but notebook rendering then hung with the notebook fetch promise never resolving. I'm pinning to `tornado<6` in #821 so I can deploy a fix for the jupyter-widgets styling bug. We'll need to revisit tornado compat.

**Comment by Seanspt** [comment]
Same request here. When trying to add nbviewer to our jupyterhub, the following error occurred.
```bash
[E 190513 15:18:16 ioloop:763] Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f58dc07c518>>, <Future finished exception=AttributeError("module 'tornado.gen' has no attribute 'Task'")>)
    Traceback (most recent call last):
      File "/opt/conda/envs/jupyterhub/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
        ret = callback()
      File "/opt/conda/envs/jupyterhub/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
        future.result()
      File "/opt/conda/envs/jupyterhub/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.send(value)
      File "/opt/conda/envs/jupyterhub/lib/python3.7/site-packages/nbviewer/providers/url/client.py", line 80, in _fetch_impl
        response = yield gen.Task(super(NBViewerAsyncHTTPClient, self).fetch_impl, request)
    AttributeError: module 'tornado.gen' has no attribute 'Task'
```

**Comment by krinsman** [comment]
Tornado 6 is incompatible with Python 2.7. So NBViewer needs to drop Python 2.7 compatibility in order to upgrade to Tornado 6. I might be able to work on this if you want, since I have some experience updating to Tornado 6 (which uses Python 3's built-in asyncio module, the first version of Tornado to do so). At least see here: https://github.com/NERSC/sshspawner/pull/14

**Comment by krinsman** [comment]
I've fixed this problem in my fork of NBViewer, see here: https://github.com/krinsman/nbviewer/tree/step6

passes tests: https://travis-ci.com/krinsman/nbviewer/builds/120096069

Right now I have a PR open for branch step2, and then this is step6 -- so should I open PR's also for step3, step4, step5, and step6? (Each of which would depend on the previous PR?) Or Would it be better to keep one PR open at a time?

**Comment by parente** [comment]
@krinsman Go ahead and open all your PRs. Just mention the sequence in which they need to be reviewed/merged in the comments.

**Comment by krinsman** [comment]
This was addressed when that branch was merged, so I am closing this issue as out of date.
