### ISSUE TITLE
Widget not rendering on NBViewer

### ISSUE THREAD

**Issue by cornhundred** [jupyter/nbviewer#823]
**Describe the bug**
Notebooks on NBViewer are not being rendered with the interactive Widget Clustergrammer-Widget. I'm seeing the error:

`Failed to load resource: the server responded with a status of 404 ()`
and 
`unpkg.com/jupyter-js-widgets@0.15/dist/embed.js:1 `

Static HTML versions of the notebook are being rendered correctly (e.g. https://github.com/MaayanLab/clustergrammer-widget/blob/master/Running_clustergrammer_widget.html). 

However, a different newer widget, Clustergrammer2, is rendering correctly on NBViewer (see https://nbviewer.jupyter.org/github/ismms-himc/clustergrammer2-notebooks/blob/master/notebooks/3.0_10X_Genomics_2700_Dataset_NBViewer.ipynb)

**To Reproduce**
1. Go to https://nbviewer.jupyter.org/github/MaayanLab/clustergrammer-widget/blob/master/Running_clustergrammer_widget.ipynb
2. No widgets are appearing after the commands `net.widget()` 
3. See `Failed to load resource` error in developer console

**Expected behavior**
The heatmap widgets should be rendered after each `net.widget()`

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Macbook pro
 - OS: MacOS Mojave
 - Browser Chrome
 - Version Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by parente** [comment]
In my late night endeavor to push a workaround to #818, I failed to recognize that the @jupyter-widgets/html-manager and jupyter-js-widgets packages versions are independent. I'll need to push a change that allows both to be set independently on the command line unfortunately.

**Comment by cornhundred** [comment]
@parente thanks for the response. What do you mean by on the command line? Are the old and new widgets expected to work after the update?

**Comment by parente** [comment]
Yes. Both should work. #824 has some more details.

**Comment by cornhundred** [comment]
Ok thanks. I'll check later.

**Comment by parente** [comment]
Might be a bit. Need to get the PR to pass, wait for DockerHub to build the latest image, and then deploy it to the public site. I'll try to get it done tomorrow morning at the latest.

**Comment by cornhundred** [comment]
Okay, great. No need to rush :)

**Comment by parente** [comment]
https://nbviewer.jupyter.org/github/MaayanLab/clustergrammer-widget/blob/master/Running_clustergrammer_widget.ipynb appears to be working for me now. Give it a try and feel free to close if you confirm it's working.

**Comment by cornhundred** [comment]
@parente it's working on my end. Thanks for the help!
