### ISSUE TITLE
Insufficient error logging in localfile provider

### ISSUE THREAD

**Issue by krishnatg** [jupyter/nbviewer#828]
If the nbviewer is started with the `--localfiles` option and there are incorrect access permissions given to the provided directory path, nbviewer throws a `404` error when the `/localfile` URL is hit. However, there are no additional error logs to help understand the gap. I had to resort to adding debug logs to pinpoint the problem, and figured it might make sense to get them added here.

**Comment by parente** [comment]
Closed by #829. Thanks!
