### ISSUE TITLE
404 not found for notebook on website

### ISSUE THREAD

**Issue by mbhall88** [jupyter/nbviewer#832]
When I try and view https://github.com/mbhall88/pandora_simulations/blob/master/scripts/results.ipynb on https://nbviewer.jupyter.org/ I get "404 not found".  

I have tried accessing the notebook with URL, through my github username, and by specifying the repository. Notebooks in my other repositories seem to render fine.

**Comment by parente** [comment]
https://nbviewer.jupyter.org/github/mbhall88/pandora_simulations/blob/master/scripts/results.ipynb seems to be working fine for me. I visited nbviewer.jupyter.org and copy/pasted the GitHub URL from the description exactly as given.

Alternatively, I can enter `mbhall/pandora_simulations` on the front page of nbviewer, click *Go!*, and then click through the directory tree listings to get to *results.ipynb*.

**Comment by mbhall88** [comment]
Ahh classic "Ask IT for help" - it now works for me too. Weird. Apologies for the spam.
