### ISSUE TITLE
nbviewer doesn't like {} <> delimiters in markup

### ISSUE THREAD

**Issue by crmccreary** [jupyter/nbviewer#85]
In my notebook http://nbviewer.ipython.org/5685640 , markup cells with latex code containing {} and <> delimiters fails to render

**Comment by parente** [comment]
I see latex cells containing `<>` and `{}` in the notebook linked as part of the original issue description rendering correctly on nbviewer today. I'm going to close this issue as resolved sometime in the past 5 years.

Please feel free to open a new issue with a link to a small notebook demonstrating the problem if you're able to reproduce this issue today.
