### ISSUE TITLE
Not compatible with Github Enterprise 

### ISSUE THREAD

**Issue by mskimm** [jupyter/nbviewer#850]
**Describe the bug**
 - #841 is not compatible with Github Enterprise.
 - https://github.com/jupyter/nbviewer/blob/7cf4b33afa623035ad0c321ead54501f79b54e38/nbviewer/providers/github/handlers.py#L164
     - `https://github\.com` should be fixed appropriately.

**To Reproduce**
If GITHUB_API_URL is a URL of Github Enterprise, the code in the previous section always fails.

**Expected behavior**
should work for Github Enterprise.

**Comment by krinsman** [comment]
@mskimm Is this still an issue while running the master version of NBViewer?

**Comment by krinsman** [comment]
@mskimm I think this was successfully closed by your merged PR, so I am tentatively closing this issue. Please let me know if you think it should be reopened!
