### ISSUE TITLE
Error 503: GitHub API rate limit exceeded. Try again soon. (new issue)

### ISSUE THREAD

**Issue by cornhundred** [jupyter/nbviewer#855]
**Describe the bug**
I'm getting this error 

Error 503: GitHub API rate limit exceeded. Try again soon.

on this page

https://nbviewer.jupyter.org/github/giannarelli-lab/Single-Cell-Immune-Profiling-of-Atherosclerotic-Plaques/blob/master/notebooks/1.1_CITE-seq_GEX_PBMC_and_Plaque.ipynb?flush_cache=true

but not this page 

https://nbviewer.jupyter.org/github/giannarelli-lab/Single-Cell-Immune-Profiling-of-Atherosclerotic-Plaques/blob/master/notebooks/1.0_CITE-seq_ADT_PBMC_and_Plaque.ipynb?flush_cache=true

These notebooks are from the same GitHub repo: https://github.com/giannarelli-lab/

**To Reproduce**
1. Go to https://nbviewer.jupyter.org/github/giannarelli-lab/Single-Cell-Immune-Profiling-of-Atherosclerotic-Plaques/blob/master/notebooks/1.1_CITE-seq_GEX_PBMC_and_Plaque.ipynb?flush_cache=true
2. See 503 error

**Expected behavior**
The notebook should be rendered. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
The links worked earlier. I'm making this issue because I can't re-open this duplicate issue: https://github.com/jupyter/nbviewer/issues/673

**Comment by cornhundred** [comment]
It is working now. I'll close the issue if the problem does not persist for the rest of the day or so.

**Comment by cornhundred** [comment]
Looks like this is expected behavior https://github.com/jupyter/nbviewer/issues/856

**Comment by krinsman** [comment]
For thoroughness (so all of these issues are cross-linked):
https://github.com/jupyter/nbviewer/issues/673
https://github.com/jupyter/nbviewer/issues/856
https://developer.github.com/v3/#rate-limiting
