### ISSUE TITLE
Error 503: No healthy backends

### ISSUE THREAD

**Issue by krinsman** [jupyter/nbviewer#857]
copied from here: https://github.com/jupyter/nbviewer/issues/856#issuecomment-542569805

> I am not sure this is related to the current issue, but links to notebooks at http://qutip.org/tutorials do not work right now.
> Also https://nbviewer.jupyter.org itself gives a 503 error.

Seemingly relevant threads:
https://github.com/jupyter/nbviewer/issues/759
https://github.com/jupyter/nbviewer/issues/758
https://github.com/jupyter/nbviewer/issues/746
https://github.com/jupyter/nbviewer/issues/607
https://github.com/jupyter/nbviewer/issues/534

(This should probably be marked as a duplicate obviously, although on the other hand it would be nice to figure out a fix to prevent this from happening again in the future.)

**Comment by andreaaraldo** [comment]
Still happening today, and also in recent days to others - see [#759 ](https://github.com/jupyter/nbviewer/issues/759#issuecomment-812329544)
