### ISSUE TITLE
404 on public github notebook

### ISSUE THREAD

**Issue by moorepants** [jupyter/nbviewer#859]
Hi! Thanks for using Jupyter Notebook Viewer (nbviewer) and taking the time to report a bug you've encountered. Please use the template below to tell us about the problem.

If you've found a bug in a different Jupyter project (e.g., [Jupyter Notebook](http://github.com/jupyter/notebook), [JupyterLab](http://github.com/jupyterlab/jupyterlab), [JupyterHub](http://github.com/jupyterhub/jupyterhub), etc.), please open an issue using that project's issue tracker instead.

If you need help using or installing Jupyter Notebook Viewer, please use the [jupyter/help](https://github.com/jupyter/help) issue tracker instead.

**Describe the bug**

**To Reproduce**

Paste this URL into nbviewer:

https://github.com/moorepants/mae223/blob/master/content/homework-notebooks/mae223-ps01.ipynb

I'm getting 404 not found.

**Expected behavior**

I'd expect to see the notebook rendered with nbviewer.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by moorepants** [comment]
Here is the nbviewer link:

https://nbviewer.jupyter.org/github/moorepants/mae223/blob/master/content/homework-notebooks/mae223-ps01.ipynb

**Comment by moorepants** [comment]
Nevermind. ?flush_cache=true fixed it.

**Comment by krinsman** [comment]
Yeah, I've found the `flush_cache` query argument to be magical (or at least quite helpful) in my experience too.
