### ISSUE TITLE
404 Error, View as Slide on localfile provider.

### ISSUE THREAD

**Issue by tamutamu** [jupyter/nbviewer#862]
**Describe the bug**
In localfile provider,  when `View as Slide` button click, it raises 404 error.

**To Reproduce**
1. Go to 'http://localhost:9999/localfile/test.ipynb'
2. Click on 'View as Slide'
3. See error, 404 Not Found.
    Navigate url is `http://localhost:9999/localfile/slides/localfile/test.ipynb`.

**Additional Information**
Url `http://localhost:9999/format/slides/localfile/test.ipynb` is correct behavior.

**Comment by krinsman** [comment]
@tamutamu  I agree with you, that sounds like the wrong URL from what I recall.

Can you include screenshots of the steps? This will sound incredibly stupid of me, but I don't remember where the "View as Slide" button is/don't remember having seen it before. I want to reproduce this error locally but am currently not sure how.

**Comment by gschex1112** [comment]
I'm having the same issue. The "view as slides" button is the one that looks like a wrapped present.

![image](https://user-images.githubusercontent.com/46825428/71767400-f451bd80-2ed9-11ea-8bd6-dd0eda5739d0.png)

**Comment by krinsman** [comment]
Do you have permissions to view the notebook in question? Permissions errors are exposed to the end-user as 404 errors.

**Comment by sjangeli** [comment]
I'm also getting a 404 error when clicking the "View as Slides" button. Here is a link to a project I'm working on: https://github.com/sjangeli/Thinkful-Data-Science Projects/blob/master/Unsupervised%20Learning%20Capstone.ipynb

Renders correctly in nbviewer but it seemingly can't find the file when I click "View as Slides" It should be a publicly accessible file.

**Comment by krinsman** [comment]
My guess is that there is a typo/mistake in the Jinja template here? 
https://github.com/jupyter/nbviewer/blob/master/nbviewer/templates/notebook.html#L6

Based on the URL in the original bug report. Admittedly I've never really used much of the alternative format features myself so I'm not entirely sure of this.

**Comment by wesszabo** [comment]
I uploaded a notebook into github, nbviewer is nice, but I'm also getting a 404 error when clicking the "View as Slides" button.  
"Remote HTTP 404: slides/github/wesszabo/Differential-Equations/blob/276b5518abeffbf6ac8bfd095217e0b3f329a509/4. gyakorlat hatványsor 1. .ipynb not found among 3 files"

**Comment by krinsman** [comment]
@wesszabo To confirm, the link for viewing the notebook regularly does work, even though viewing it as slides doesn't? What is the GitHub URL for the notebook in order to reproduce the error?

**Comment by wesszabo** [comment]
[https://github.com/wesszabo/Differential-Equations/blob/Power-Series-Solutions/4.%20gyakorlat%20hatv%C3%A1nysor%201.%20.ipynb](url)

**Comment by astrojuanlu** [comment]
I have experience this myself regularly in the past months. @wesszabo link still gives 404.

- Notebook: https://github.com/sjangeli/Thinkful-Data-Science-Projects/blob/master/Unsupervised%20Learning%20Capstone.ipynb
- nbviewer: https://github.com/sjangeli/Thinkful-Data-Science-Projects/blob/master/Unsupervised%20Learning%20Capstone.ipynb
- "View as slides" link: https://nbviewer.jupyter.org/github/sjangeli/Thinkful-Data-Science-Projects/blob/master/slides/github/sjangeli/Thinkful-Data-Science-Projects/blob/master/Unsupervised%20Learning%20Capstone.ipynb (404 :warning: )
- Correct "View as slides" link: https://nbviewer.jupyter.org/format/slides/github/sjangeli/Thinkful-Data-Science-Projects/blob/master/Unsupervised%20Learning%20Capstone.ipynb :heavy_check_mark: 

@krinsman Is this enough to reproduce the bug?

**Comment by propertone** [comment]
Any updates on fixing this? The link is clearly broken for all providers

**Comment by propertone** [comment]
Fix proposed in #989

**Comment by astrojuanlu** [comment]
I understand that the fix hasn't been deployed yet?
