### ISSUE TITLE
Repo and user links do not work with GHE

### ISSUE THREAD

**Issue by ivan-gomes** [jupyter/nbviewer#863]
**Describe the bug**
When configured to integrate with GitHub Enterprise, links to repositories and users/orgs do not work.

Examples:
* https://ghe.mycompany.com/ivangomes
* https://ghe.mycompany.com/ivangomes/myproject 

**To Reproduce**
Enter GHE URL like https://ghe.mycompany.com/ivangomes in an nbviewer deployment configured with GHE.

**Expected behavior**
Get redirected to https://nbviewer.mycompany.com/github/ivangomes and see the navigation UI, like in https://nbviewer.jupyter.org/github/jupyter/nbviewer/tree/master/

**Additional context**
Related to #850.

**Comment by krinsman** [comment]
@ivan-gomes Sorry for the slow response!

What version of NBViewer are you using? In particular, are you using the master version of NBViewer? https://github.com/jupyter/nbviewer/pull/851

**Comment by ivan-gomes** [comment]
Yes I am using the master branch of nbviewer, with latest commit https://github.com/jupyter/nbviewer/commit/8a8fd298b446096dddc874da57e99dd22a2d8d97. #851 does fix some GHE compatibility like being able to look up `org/repo` or just `org`, but when the full URL is included, e.g. `https://ghe.mycompany.com/ivangomes` it does not work. This issue and corresponding PR specifically addresses that.

**Comment by krinsman** [comment]
This makes more sense to me now.

To clarify, when you say `org/repo`, do you mean `<nbviewer_base_url>/github/org/repo`? `ivangomes/myrepo`, `<nbviewer_base_url>/github/ivangomes/myrepo`? Etc.?

**Comment by ivan-gomes** [comment]
Assuming my repository is https://ghe.mycompany.com/ivangomes/myproject, if I typed `ivangomes/myproject` into the search box on the nbviewer home page it would redirect to `<nbviewer_base_url/github/ivangomes/myproject` properly as of https://github.com/jupyter/nbviewer/commit/8a8fd298b446096dddc874da57e99dd22a2d8d97.

However, if I instead entered the full URL, i.e. `https://ghe.mycompany.com/ivangomes/myproject` into the same search box it would instead redirect to `<nbviewer_base_url/url/https%3A%2F%2Fghe.mycompany.com%2Fivangomes%2Fmyproject` and respond 404. This issue is to address this case.

**Comment by krinsman** [comment]
This makes sense to me, and seems like a really good feature enhancement!
