### ISSUE TITLE
Gist support does not work with GHE

### ISSUE THREAD

**Issue by ivan-gomes** [jupyter/nbviewer#865]
**Describe the bug**
When configured to integrate with GitHub Enterprise, Gists do not work.

**To Reproduce**
Enter Gist URL, e.g. https://ghe.mycompany.com/gist/c3ca62e42d590f81c3a906824b2528b0, in an nbviewer configured `GITHUB_API_URL=https://ghe.mycompany.com/v3/api/`.

**Expected behavior**
The notebook in the Gist is rendered in nbviewer.

**Additional context**
Related to #850 and #863.

**Comment by krinsman** [comment]
Ditto the comments on #863

**Comment by ivan-gomes** [comment]
I am using the master branch of nbviewer, with latest commit https://github.com/jupyter/nbviewer/commit/8a8fd298b446096dddc874da57e99dd22a2d8d97.
