### ISSUE TITLE
Raw download link does not work with GHE

### ISSUE THREAD

**Issue by ivan-gomes** [jupyter/nbviewer#867]
**Describe the bug**
When configured to integrate with GitHub Enterprise, raw download links for notebooks do not work.

**To Reproduce**
With a notebook from GHE open, e.g. https://nbviewer.mycompany.com/github/ivangomes/myproject/index.ipynb, in an nbviewer configured GITHUB_API_URL=https://ghe.mycompany.com/v3/api/, click the download button on the top right and get a 404.

**Expected behavior**
File download from GHE starts.

**Additional context**
Related to #850, #863, #865.

**Comment by krinsman** [comment]
Ditto the comments on #863

**Comment by ivan-gomes** [comment]
I am using the master branch of nbviewer, with latest commit https://github.com/jupyter/nbviewer/commit/8a8fd298b446096dddc874da57e99dd22a2d8d97.
