### ISSUE TITLE
from cgi import escape fails under python 3.8; import from html instead 

### ISSUE THREAD

**Issue by MiddleFork** [jupyter/nbviewer#869]
**Describe the bug**
Importing 'escape' from cgi fails under python3.8 
at line 15 of providers/base.py

**To Reproduce**
>>> from cgi import escape

**Expected behavior**
Successful import

**Screenshots**
>>> from cgi import escape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'escape' from 'cgi' 

**Resolution**
replace line 15 of providers/base.py with
`from html import escape`

**Comment by krinsman** [comment]
Thank you for pointing this out as well as the quick fix!
