### ISSUE TITLE
`?flush_cache` doesn't update my notebook

### ISSUE THREAD

**Issue by YousefSaber** [jupyter/nbviewer#903]
this link is for my Julia notebook rendering on NBViewer 

https://nbviewer.jupyter.org/github/YousefSaber/Jupyter-Noteboos/blob/master/JuliaInput.ipynb?flush_cache=true

I still see the error 

![image](https://user-images.githubusercontent.com/33742499/75010978-25388280-5487-11ea-8ccb-fc0312ee899f.png)

the link of the same notebook on Github 

https://github.com/YousefSaber/Jupyter-Noteboos/blob/master/JuliaInput.ipynb

although I appended `?flush_cache=true` to my URL it wasn't updated instantly. 

maybe after 10 minutes or sometime this may be fixed but why it wasn't fixed instantly with `?flush_cache=true` the command just waiting for long isn't convenient. 

also, your [FAQ](https://nbviewer.jupyter.org/faq) URL is broken.

**Comment by krinsman** [comment]
I get a 404 when I visit this page: https://github.com/YousefSaber/Jupyter-Notebooks/blob/master/JuliaInput.ipynb

Regarding `?flush_cache`, I believe it doesn't do here what you seem to think it does. In particular, NBViewer would get the URL for the notebook from the GitHub API. So if the GitHub API doesn't fix it instantly, then there isn't anything NBViewer can do.

I'll open a separate issue about the FAQ URL.

**Comment by YousefSaber** [comment]
@krinsman sorry I've renamed my Repo the new URL is
https://github.com/YousefSaber/Jupyter-Notebooks/blob/master/Julia%20NB/JuliaInput.ipynb
I also have done some modifications to my notebook this time without even using the code NBViewer could sync and update with my notebook when rendering.
according to your reply, there is no point in opening the issue here you are free to close this issue then if you want.
but you may try to reproduce this issue( it may or may not occur again) on your devices and then send feedback to Github about that. 
currently, I've no issues from what I've experienced recently but this issue may surface again.

**Comment by krinsman** [comment]
I agree with you, it would be good idea to let GitHub know about this. I don't know how -- ironically, their code isn't open source and they don't have a GitHub repo for it, as far as I am aware.

I'm sorry that this issue has negatively impacted your experience closing NBViewer. If I or you or any of the rest of us can find out a way to fix this on our end (I guess by somehow circumventing the problem in the GitHub API), then we should investigate implementing it. Until then, your suggestion to close this issue makes sense to me, although I wish there was more we could do at the moment.
