### ISSUE TITLE
404 Error on valid notebook URL

### ISSUE THREAD

**Issue by bockjo** [jupyter/nbviewer#912]
Dear Team,

I would like to view the following notebook on nbviewer, but I get an "404 File not found" Error. 

[COVID-Analysis_v7.ipynb](https://github.com/bockjo/Miscellaneous/blob/master/COVID-Analysis_v7.ipynb)

Thanks for helping out!
Best
Johannes

**Comment by bockjo** [comment]
The same error occurs for the following file:
[Small_COVID-Analysis.ipynb](https://github.com/bockjo/Miscellaneous/blob/master/Small_COVID-Analysis.ipynb)

**Comment by krinsman** [comment]
Thank you for contributing to NBViewer!

Sorry about the slow response. It's working for me right now? https://nbviewer.jupyter.org/github/bockjo/Miscellaneous/blob/master/COVID-Analysis_v7.ipynb

NBViewer gets the notebooks from the GitHub API, so maybe the GitHub API isn't quick enough to update new notebooks you've uploaded to GitHub?

**Comment by krinsman** [comment]
@bockjo Currently I can't reproduce this error, so I am tentatively closing this issue. The problem seems to be with the GitHub API, and not NBViewer.

Please let me know if I should reopen it.
