### ISSUE TITLE
400 error on valid github notebook

### ISSUE THREAD

**Issue by jwrichar** [jupyter/nbviewer#915]
I get a 400 Bad Request (Error reading JSON notebook) on the following nb: https://nbviewer.jupyter.org/github/jwrichar/COVID19-mortality/blob/master/US%20County%20COVID-19%20Maps.ipynb

It is able to access the GitHub repo without any problem and the other notebooks render properly:
![image](https://user-images.githubusercontent.com/52940005/78283312-726e3200-74d2-11ea-8e04-3c6d48d572bd.png)

The particular notebook that is failing is ~30MB.  Is there a size limit that I am unaware of?

Screenshot of the error page:
![image](https://user-images.githubusercontent.com/52940005/78283411-992c6880-74d2-11ea-8311-61c575ea04aa.png)

**Comment by krinsman** [comment]
The relevant section of the code seems to be here: https://github.com/jupyter/nbviewer/blob/b2946f3df383873fe8fe0ffa044c24fd1cefb897/nbviewer/providers/base.py#L703

That is calling the function `reads` in NBFormat:
https://github.com/jupyter/nbformat/blob/16032b927d19c2860efdd46762c3020761cb0154/nbformat/v4/nbjson.py#L25

Looking at the documentation for the `json` library I'm not sure why `json.loads` would necessarily return a `ValueError`. https://docs.python.org/3/library/json.html

I think this might make more sense to open as an issue with NBFormat? https://github.com/jupyter/nbformat
What do you think @jwrichar

**Comment by krinsman** [comment]
Hi again @jwrichar the link works for me now:
https://nbviewer.jupyter.org/github/jwrichar/COVID19-mortality/blob/master/US%20County%20COVID-19%20Maps.ipynb

Can you confirm whether you are still having this issue?

**Comment by jwrichar** [comment]
@krinsman thanks for the quick reply - it works for me now, as well!

I've noticed that sometimes it takes a few hours for nbviewer to pull the latest branch status.  Perhaps this is all that was happening here 🤷‍♂
