### ISSUE TITLE
404 : Not Found

### ISSUE THREAD

**Issue by fangohr** [jupyter/nbviewer#916]
**Describe the bug**

When trying to view this notebook  https://github.com/fangohr/coronavirus-2020/blob/master/index.ipynb
through nbviewer (using this url: https://nbviewer.jupyter.org/github/fangohr/coronavirus-2020/blob/master/index.ipynb), I see a 

```
404 : Not Found
Remote HTTP 404: index.ipynb not found among 10 files
```

reported.

**Expected behavior**

To see rendering of the notebook 

**Desktop (please complete the following information):**
 - OSX, Chrome, Safari

**Additional context**
- Other 404 reports: #912 (the example in there is also broken at the moment)
- I have used that feature and nbviewer link two days ago (1 April) succesfully, and also yesterday I think.

![Screenshot 2020-04-03 at 10 22 52](https://user-images.githubusercontent.com/4489119/78339690-2b954080-7595-11ea-9561-6faf2cc18f68.png)

**Comment by krinsman** [comment]
Hi @fangohr thank you for contributing to NBViewer!

The link is working for me now: https://nbviewer.jupyter.org/github/fangohr/coronavirus-2020/blob/master/index.ipynb

Are you still experiencing this issue?

This seems related to a previous issue: https://github.com/jupyter/nbviewer/issues/912

**Comment by fangohr** [comment]
Hi @krinsman - thank you for the welcoming message, and thank you for looking into this. Thanks also for an awesome project and (nbviewer) service!

Yes, it is working now for me, too! So this seems to be an awkward observation (bug somewhere?) that is sometimes present and sometimes not. (Consistent with #912)

No idea how to debug this. 

If you have logs, could you check them at the time when I reported the issue? I definitely visited the URL a few times a few minutes before I submitted the issue.

Many thanks!

**Comment by krinsman** [comment]
As far as I can tell, this seems to be a result of a time lag on the part of the GitHub API, which we have no control over. I don't have access to the server logs, so I think the best I can do for now is to close this tentatively. Please let me know if any new information comes up so we can reopen this.

**Comment by reubens9** [comment]
Good day, I am currently experiencing the same issue. I have tried changing a few things that I thought could be causing the issue but I am unable to solve it.

Here is the link to the notebook that won't render: https://nbviewer.jupyter.org/github/reubens9/Process-Dynamics-CPN321/blob/master/1_Modelling/2_Modelling_equations.ipynb

Thanks in advance!

**Comment by iqbalAhmadKabir** [comment]
I also faced the same issue but "Copy peramlink" helped me.
