### ISSUE TITLE
Plotly graphs are blank on the viewer

### ISSUE THREAD

**Issue by rajtulluri** [jupyter/nbviewer#925]
Plotly graphs leave a blank space when viewed on the viewer. The plots seem fine when viewed on the jupyter notebook locally.
Here is a link to the notebook - https://nbviewer.jupyter.org/github/rajtulluri/Exploring-Ebay-Car-Sales/blob/master/Exploring%20Ebay%20Car%20listings%20-%20Germany.ipynb
The jupyter notebook versions are - 
jupyter core 4.6.3
jupyter notebook 6.0.3
nbconvert 5.6.1
nbformat 4.4.0

(A higher nbformat version causes validation error in the notebook)

**Comment by Shubhi550** [comment]
Facing the same problem. I used Google Colab where the graphs were plotted fine, but I am getting blank outputs instead of plotly graphs on github and viewer.
