### ISSUE TITLE
400 Bad Request, something to do with Plotly?

### ISSUE THREAD

**Issue by nshyam97** [jupyter/nbviewer#926]
Seem to be having an issue now with my notebook which contains Plotly plots. Returns a 400 Bad Request when trying to load on nbviewer as well. Not sure what the problem is entirely. Dev tools Network shows a 400 from GitHub trying to get the file but I have tried accessing it through my username in nbviewer and also doesn't seem to work.

https://nbviewer.jupyter.org/github/nshyam97/Google-Community-Mobility-Report/blob/master/report.ipynb

This is the link. Running on Safari but also does not work in Chrome for just that notebook in my repos. 

I have also attached a screenshot.

![Screenshot 2020-05-13 at 18 52 02](https://user-images.githubusercontent.com/22037803/81847022-e75d6e80-954a-11ea-9279-98c4b73da11f.png)

**Comment by nshyam97** [comment]
Seemed to have fixed itself

**Comment by bashir-abubakar** [comment]
I have this same issue as well. How did you fix it ???
