### ISSUE TITLE
Not able to access ipynb file

### ISSUE THREAD

**Issue by kuldeep27396** [jupyter/nbviewer#929]
Hi! Thanks for using Jupyter Notebook Viewer (nbviewer) and taking the time to report a bug you've encountered. Please use the template below to tell us about the problem.

If you've found a bug in a different Jupyter project (e.g., [Jupyter Notebook](http://github.com/jupyter/notebook), [JupyterLab](http://github.com/jupyterlab/jupyterlab), [JupyterHub](http://github.com/jupyterhub/jupyterhub), etc.), please open an issue using that project's issue tracker instead.

If you need help using or installing Jupyter Notebook Viewer, please use the [jupyter/help](https://github.com/jupyter/help) issue tracker instead.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kuldeep27396** [comment]
https://github.com/kuldeep27396/Data-Science-and-Machine-Learning-My-self-Education/blob/master/Module%202:%20Data%20Science:%20Exploratory%20Data%20Analysis%20and%20Data%20Visualization/Exploratory%20Data%20Analysis.ipynb

**Comment by parente** [comment]
Thanks for the report. GitHub has their own notebook rendering implementation which is not based on the code here in jupyter/nbviewer as far as I know. 

The link you provided, 
https://github.com/kuldeep27396/Data-Science-and-Machine-Learning-My-self-Education/blob/master/Module%202:%20Data%20Science:%20Exploratory%20Data%20Analysis%20and%20Data%20Visualization/Exploratory%20Data%20Analysis.ipynb, does seem to render for me today after processing for a while.

For what it's worth, nbviewer does render the notebook successfully as well: https://nbviewer.jupyter.org/github/kuldeep27396/Data-Science-and-Machine-Learning-My-self-Education/blob/master/Module%202%3A%20Data%20Science%3A%20Exploratory%20Data%20Analysis%20and%20Data%20Visualization/Exploratory%20Data%20Analysis.ipynb

**Comment by kuldeep27396** [comment]
Yes It worked after one day, not sure what was wrong that time.
Thanks,

Kuldeep Pal
*Mob*: +917693973279
Connect on Skype <https://join.skype.com/invite/u3BFb2bpCb1N>
My Linkedin <https://www.linkedin.com/in/kuldeeppal27396/> | What's App
<https://api.whatsapp.com/send?phone=+917693973279>
*Mail*: kuldeep27396@gmail.com

**Comment by kuldeep27396** [comment]
worked for me a well the next day.
