### ISSUE TITLE
Add extension to link Github with nbviewer

### ISSUE THREAD

**Issue by btel** [jupyter/nbviewer#93]
On nbviewer page link  a userscript which modifies Github page, so that the current ipynb file can be opened with nbviewer.

There are at least two implementations of such scripts:

1) https://gist.github.com/btel/5813784
2) https://gist.github.com/punchagan/5882879

(1) adds a button to GH filebrowser; (2) embeds the rendered notebook with GH frame. 

Both scripts can be installed with Greasemonkey (Firefox) or Tampermonkey (Chrome). To install, install the browser extension and then click on "raw" link on the Gist page with the script.

**Comment by Carreau** [comment]
Closing as now gihub/gist render ipynb

**Comment by rgbkrk** [comment]
:+1:
