### ISSUE TITLE
Cannot access some URL

### ISSUE THREAD

**Issue by scholi** [jupyter/nbviewer#930]
Hi! TI have two ipynb hosted on bitbucket and strangely I can see one with nbviewer, but the other 
 makes a 400 : Bad Request
Error reading JSON notebook

**Describe the bug**
This works: https://nbviewer.jupyter.org/urls/bitbucket.org/fluximag/pyfluxim/raw/15a88fc6a21f10e7cafb4141c45c00e39f514574/doc/LL_data_example1.ipynb
This doesn't: https://nbviewer.jupyter.org/urls/bitbucket.org/fluximag/pyfluxim/raw/15a88fc6a21f10e7cafb4141c45c00e39f514574/doc/Flux_data_example1.ipynb

The file exists and is publicly available under: https://bitbucket.org/fluximag/pyfluxim/raw/15a88fc6a21f10e7cafb4141c45c00e39f514574/doc/Flux_data_example1.ipynb

**To Reproduce**
1. Got to url: https://nbviewer.jupyter.org/urls/bitbucket.org/fluximag/pyfluxim/raw/15a88fc6a21f10e7cafb4141c45c00e39f514574/doc/Flux_data_example1.ipynb
2. See error 400

**Desktop (please complete the following information):**
 -browser: [chrome]

**Comment by parente** [comment]
FWIW, The link originally causing a 400 is working when I visit it today:

https://nbviewer.jupyter.org/urls/bitbucket.org/fluximag/pyfluxim/raw/15a88fc6a21f10e7cafb4141c45c00e39f514574/doc/Flux_data_example1.ipynb

**Comment by scholi** [comment]
True it works now. Not sure what was srong. Closing
