### ISSUE TITLE
404 error on valid notebook

### ISSUE THREAD

**Issue by aakhmetz** [jupyter/nbviewer#936]
Hello, I do have the same problem. 

While I can see the github tree from https://nbviewer.jupyter.org/github/contactmodel/COVID19-Japan-Reff/tree/master/scripts/, when I click on the script C I get the error: "Remote HTTP 404: scripts/C. Calculating the Rt in RStan.ipynb not found among 16 files"

This can be related to #935 and #912 (which was closed)

Thank you for checking

**Comment by aakhmetz** [comment]
I think 19 days is enough to close this issue. Thank you for your help

**Comment by kellytdunn** [comment]
What was the resolution of this? Were you able to access your file on nbviewer finally?
