### ISSUE TITLE
400 Bad Request : Error Reading JSON Notebook

### ISSUE THREAD

**Issue by LLLichtenstein** [jupyter/nbviewer#941]
Hi! Thanks for using Jupyter Notebook Viewer (nbviewer) and taking the time to report a bug you've encountered. Please use the template below to tell us about the problem.

If you've found a bug in a different Jupyter project (e.g., [Jupyter Notebook](http://github.com/jupyter/notebook), [JupyterLab](http://github.com/jupyterlab/jupyterlab), [JupyterHub](http://github.com/jupyterhub/jupyterhub), etc.), please open an issue using that project's issue tracker instead.

If you need help using or installing Jupyter Notebook Viewer, please use the [jupyter/help](https://github.com/jupyter/help) issue tracker instead.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
The error occurred while submitting the URL for a Jupyter Notebook on IBM Watson Studio.
The URL is https://dataplatform.cloud.ibm.com/analytics/notebooks/v2/5326a91a-2053-492d-8654-49f52ed917b4?projectid=c2497cd9-ea82-4f48-8f7d-45f7bdaf324e&projectTitle=Course%209%20-%20Applied%20Data%20Science%20Capstone&context=cpdaas

**Comment by LLLichtenstein** [comment]
The error occurred while submitting the URL for a Jupyter Notebook on IBM Watson Studio.
The URL is https://dataplatform.cloud.ibm.com/analytics/notebooks/v2/5326a91a-2053-492d-8654-49f52ed917b4?projectid=c2497cd9-ea82-4f48-8f7d-45f7bdaf324e&projectTitle=Course%209%20-%20Applied%20Data%20Science%20Capstone&context=cpdaas

**Comment by LLLichtenstein** [comment]
problem solved

**Comment by z-j-king** [comment]
I'm having a similar issue, what was your solution?
