### ISSUE TITLE
Markdown/text cells are not wrapped in a cell div

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbviewer#95]
In the live notebook, all cells live inside a div with a cell class.  This allow you to style that cell element in CSS.  But in nbviewer, the text cells don't have this wrapper class, so cell level styling is ignored on nbviewer.  This may be a problem with nbconvert rather than nbviewer.

**Comment by bollwyvl** [comment]
This appears to be fixed as of #413, though likely this was an upstream fix.
