### ISSUE TITLE
The image built by dockerfile of master branch is not working

### ISSUE THREAD

**Issue by onevirus** [jupyter/nbviewer#958]
**Describe the bug**
Currently, the image built by dockerfile of master branch is not working.
It looks nbviewer uses nbconvert.exporters.export.
However, that module is removed from nbconvert>=6.0.

**To Reproduce**
It's easy to reproduce.
Just follow https://github.com/jupyter/nbviewer#with-docker
```bash
git clone https://github.com/jupyter/nbviewer.git
cd nbviewer
docker build -t nbviewer .
docker run -p 8080:8080 -it nbviewer
```
or copy & paste this scripts.

**Expected behavior**
Run nbviewer container without error.

**Screenshots**
I paste error logs instead.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.7/site-packages/nbviewer/__main__.py", line 1, in <module>
>     from nbviewer.app import main
>   File "/usr/local/lib/python3.7/site-packages/nbviewer/app.py", line 19, in <module>
>     from nbconvert.exporters.export import exporter_map
> ModuleNotFoundError: No module named 'nbconvert.exporters.export'

**Desktop (please complete the following information):**
 - OS: iOS
 - Catalina 10.15.6

**Comment by robindebois** [comment]
Hey @onevirus,
Please check if my fork solves the problem for you.
