### ISSUE TITLE
Nested Lists Inconsistency

### ISSUE THREAD

**Issue by ivanov** [jupyter/nbviewer#98]
Originally reported by @ptwobrussell

```
1. numbered
 * bullet
1. numbered
```

Renders properly in the live notebook, but as 1.2.3. in nbviewer...

```
1. numbered
    * bullet
1. numbered
```

Inserting 4 spaces in front of the bullet (instead of one) makes it render properly.

Example notebook here:
http://nbviewer.ipython.org/6107232

**Comment by bollwyvl** [comment]
Looks to be fixed as of #413, but likely it was an upstream fix.
