### ISSUE TITLE
Image 'width' does not seem to be honored by nbviewer

### ISSUE THREAD

**Issue by certik** [jupyter/nbviewer#99]
Here is a notebook:

http://nbviewer.ipython.org/urls/raw.github.com/certik/climate/master/Sea%2520Ice%2520Index.ipynb

If you scroll all the way down, you will see a huge png image. But if you open it in ipython, it will format correctly.

**Comment by bollwyvl** [comment]
There no longer appears to be a huge png. Please reopen if this is still an issue!

**Comment by certik** [comment]
Indeed, this is fixed now. Thanks @bollwyvl!
